<!-- iCheck for checkboxes and radio inputs -->
<link href="<?php echo $this->baseUrl("plugins/iCheck/all.css"); ?>" rel="stylesheet" type="text/css" />
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Comprar Crédito
        <small>efetuar recarga</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="<?php echo $this->baseUrl("/"); ?>"><i class="fa fa-dashboard"></i> Início</a></li>
        <li class="active"> Comprar Crédito</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
     <div class="row">
          <div class="col-xs-12">
           <div class="box box-danger">
            <div class="box-body">
              <label>Valor Crédito</label>
              <div class="input-group col-md-1">
                <div class="input-group-addon">
                  R$
                </div>
                <input type="text" name="credito"  class="form-control dinheiro" placeholder="Valor" />
              </div><!-- /.input group -->
            </div><!-- /.box-body -->
            <div class="box-body">
              <div class="form-group">
                <label>
                  <input type="radio" name="r2" class="minimal-red" checked/> Cartão de Crédito
                </label>
                <label>
                  <input type="radio" name="r2" class="minimal-red" /> Boleto Bancário
                </label>
              </div>
              <!-- Minimal red style -->
              <div class="form-group">
                <img src="<?php echo $this->baseUrl("dist/img/credit/visa.png"); ?>" alt="Visa"/>
                <img src="<?php echo $this->baseUrl("dist/img/credit/mastercard.png"); ?>" alt="Mastercard"/>
                <img src="<?php echo $this->baseUrl("dist/img/credit/american-express.png"); ?>" alt="American Express"/>
                <img src="<?php echo $this->baseUrl("dist/img/credit/paypal2.png"); ?>" alt="Paypal"/>
              </div>
            </div><!-- /.box-body -->
            <div class="box-body">
              <h4>Preencha os Dados do Cartão</h4>
              <label>Nome do Titular</label>
              <div class="input-group margin-bottom col-md-4">
                <div class="input-group-addon">
                  <i class="fa fa-user"></i>
                </div>
                <input type="text" name="nome" class="form-control" placeholder="Nome do Titular" />
              </div><!-- /.input group -->
              <label>Número do Cartão</label>
              <div class="input-group margin-bottom col-md-4">
                <div class="input-group-addon">
                  <i class="fa fa-credit-card"></i>
                </div>
                <input type="text" name="email" class="form-control" placeholder="Número do Cartão" />
              </div><!-- /.input group -->
              <label>Data de Validade</label>
              <div class="input-group margin-bottom col-md-1">
              <div class="input-group-addon">
                <i class="fa fa-calendar"></i>
              </div>
              <input type="text" name="validade" class="form-control" placeholder="mm/aaaa" data-inputmask="'alias': 'mm/yyyy'" data-mask />
              </div><!-- /.input group -->
              <label>Código de Segurança</label>
              <div class="input-group margin-bottom col-md-1">
                <div class="input-group-addon">
                  <i class="fa fa-credit-card"></i>
                </div>
                <input type="text" name="codigo" class="form-control inteiro" placeholder="XXX" />
              </div><!-- /.input group -->
              <div class="row">
               <div class="col-xs-4">
                   <button class="btn btn-success pull-left"><i class="fa fa-credit-card"></i> Confirmar Compra</button>
               </div><!-- /.col -->
              </div>
            </div><!-- /.box-body -->
           </div><!-- /.box -->
          </div><!-- /.col -->
         </div><!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- InputMask -->
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.date.extensions.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.extensions.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.maskMoney.js"); ?>" ></script>

<!-- iCheck 1.0.1 -->
<script src="<?php echo $this->baseUrl("plugins/iCheck/icheck.min.js"); ?>" type="text/javascript"></script>

<script type="text/javascript">
$(function () {
  $("#datemask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
  $("[data-mask]").inputmask();
  $('.dinheiro').maskMoney({thousands: '', decimal: ','});
  $('.inteiro').maskMoney({thousands: '', decimal: ''});
  $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
    checkboxClass: 'icheckbox_minimal-red',
    radioClass: 'iradio_minimal-red'
  });
});
</script>