<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Comprar Crédito
        <small>efetuar recarga</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="<?php echo $this->baseUrl("/"); ?>"><i class="fa fa-dashboard"></i> Início</a></li>
        <li class="active"> Comprar Crédito</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
     <div class="row">
          <div class="col-xs-12">
           <div class="box box-danger">
            <div class="box-body">
                <p class="lead">Digite o valor:
                <input type="text" name="ValorCreditar" size="10"/></p>
                     <p class="lead">Selecione a forma de para Pagamento:</p>
                     <!-- radio -->
                  <div class="form-group">
                    <label>
                      <input type="radio" name="r2" class="minimal-red" checked/>
                      Cartão de Crédito
                    </label>
                    <label>
                      <input type="radio" name="r2" class="minimal-red"/>
                      Boleto Bancário
                    </label>
                  </div>

                  <!-- Minimal red style -->
                <div class="form-group">
                     <img src="<?php echo $this->baseUrl("dist/img/credit/visa.png"); ?>" alt="Visa"/>
                     <img src="<?php echo $this->baseUrl("dist/img/credit/mastercard.png"); ?>" alt="Mastercard"/>
                     <img src="<?php echo $this->baseUrl("dist/img/credit/american-express.png"); ?>" alt="American Express"/>
                     <img src="<?php echo $this->baseUrl("dist/img/credit/paypal2.png"); ?>" alt="Paypal"/>
                 </div>
            </div><!-- /.box-body -->
             <div class="register-box-body">
              <p class="lead">Preencha os Dados</p>
               <form action="index.html" method="post">
                <div class="form-group has-feedback">
                 <input type="text" name="NomeTitular" size="80" placeholder="Nome do Titular..."/>
                </div>
           <div class="form-group has-feedback">
            <input type="text" name="NumeroCartao" size="80" placeholder="Número do Cartão..."/>
           </div>
           <div class="form-group has-feedback">
            <input type="text" name="DataValidade" size="80" placeholder="Data de Validade..."/>
           </div>
           <div class="form-group has-feedback">
            <input type="text" name="CodigoSeguranca" size="80" placeholder="Código de Segurança..."/>
           </div>

             <div class="row">
               <div class="col-xs-4">
                   <button class="btn btn-success pull-left"><i class="fa fa-credit-card"></i>Confirmar Compra</button>
               </div><!-- /.col -->
              </div>
             </form>
            </div><!-- /.form-box -->
           </div><!-- /.box -->
          </div><!-- /.col -->
         </div><!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->