<!-- iCheck for checkboxes and radio inputs -->
<link href="<?php echo $this->baseUrl("plugins/iCheck/all.css"); ?>" rel="stylesheet" type="text/css" />
<style type="text/css">
#mask {
  position:absolute;
  left:0;
  top:0;
  z-index:9000;
  background-color:#000;
  display:none;
}

.window {
  position:absolute;
  top: auto;
  bottom: auto;
  right: auto;
  left: auto;
  display:none;
  z-index:9999;
}
.modal {
  background: transparent!important;
}
</style>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        <?php if ($this->usarioLogado->perfil == 'cliente') : ?>
        Minha Conta
        <small>editar informações</small>
        <?php else : ?>
        Clientes
        <small>editar cliente</small>
        <?php endif; ?>
      </h1>
      <ol class="breadcrumb">
        <li><a href="<?php echo $this->baseUrl("/"); ?>"><i class="fa fa-dashboard"></i> Início</a></li>
        <?php if ($this->usarioLogado->perfil == 'cliente') : ?>
        <li><a href="<?php echo $this->url(array('controller' => 'funcionario'), null, 1); ?>">Minha Conta</a></li>
        <li class="active">editar informações</li>
        <?php else : ?>
        <li><a href="<?php echo $this->url(array('controller' => 'funcionario'), null, 1); ?>">Cliente</a></li>
        <li class="active">editar</li>
        <?php endif; ?>
      </ol>
    </section>

    <div class="modal window modal-danger">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><i class="icon fa fa-warning"></i> Atenção!</h4>
          </div>
          <div class="modal-body">
            <?php if ($this->usarioLogado->perfil == 'cliente') : ?>
            <p>Você tem certeza que deseja <strong>Encerrar</strong> sua conta?</p>
            <?php else : ?>
            <p>Você tem certeza que deseja <strong>Inativar</strong> esse Cliente?</p>
            <?php endif; ?>
          </div>
          <div class="modal-footer buttons">
            <button type="button" class="btn btn-outline">Sim</button>
            <button type="button" class="btn btn-outline close2">Não</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <!-- Máscara para cobrir a tela -->
    <div id="mask"></div>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="box box-danger">
            <div class="box-header">
              <?php if ($this->usarioLogado->perfil == 'cliente') : ?>
              <h3 class="box-title">Editar Informações</h3>
              <?php else : ?>
              <h3 class="box-title">Editar Cliente</h3>
              <?php endif; ?>
            </div>
            <div class="box-body">
              <div class="form-group">
                <!-- form start -->
                <form action="" method="post">
                  <div class="form-group">
                    <label>
                      <input type="radio" name="r2" class="minimal-red" checked/> Pessoa Física
                    </label>
                    <label>
                      <input type="radio" name="r2" class="minimal-red" disabled/> Pessoa Jurídica
                    </label>
                  </div>
                  <label>Nome</label>
                  <div class="input-group margin-bottom col-md-6">
                    <div class="input-group-addon">
                      <i class="fa fa-user"></i>
                    </div>
                    <input type="text" name="nome" value="José Paulo" class="form-control" placeholder="Nome" />
                  </div><!-- /.input group -->
                  <label>E-mail</label>
                  <div class="input-group margin-bottom col-md-6">
                    <div class="input-group-addon">
                      <i class="fa fa-envelope"></i>
                    </div>
                    <input type="text" name="email" value="jose.paulo@gmail.com" class="form-control" placeholder="E-mail" />
                  </div><!-- /.input group -->
                  <label>Telefone</label>
                  <div class="input-group margin-bottom col-md-3">
                    <div class="input-group-addon">
                      <i class="fa fa-phone"></i>
                    </div>
                    <input type="text" name="telefone" value="(48) 9669-6789" class="form-control" placeholder="Telefone" data-inputmask='"mask": "(99) 9999-9999"' data-mask />
                  </div><!-- /.input group -->
                  <div class="box">
                    <div class="box-header">
                      <h3 class="box-title">Dados do Documento</h3>
                    </div>
                    <div id="pessoaFisica" class="box-body">
                      <div class="row">
                        <div class="col-xs-3">
                          <label>CPF</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="cpf" value="844.614.208-25" class="form-control" placeholder="CPF" data-inputmask='"mask": "999.999.999-99"' data-mask />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-xs-3">
                          <label>RG</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="rg" value="5.614.208" class="form-control" placeholder="RG" />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-xs-4">
                          <label>Data de Nascimento</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" name="dataNascimento" value="21/10/1986" class="form-control" placeholder="Data de Nascimento" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask />
                          </div><!-- /.input group -->
                        </div>
                      </div>
                    </div><!-- /.box-body -->
                    <div id="pessoaJuridica" class="box-body" style="display: none;">
                      <div class="row">
                        <div class="col-md-4">
                          <label>CNPJ</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="cnpj" value="81.361.861/0001-05" class="form-control" placeholder="CNPJ" data-inputmask='"mask": "99.999.999/9999-99"' data-mask />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-xs-4">
                          <label>Data de Fundação</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" name="dataFundacao" value="10/11/2014" class="form-control" placeholder="Data de Fundação" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask />
                          </div><!-- /.input group -->
                        </div>
                      </div>
                    </div><!-- /.box-body -->
                  </div><!-- /.box -->

                  <label>Login</label>
                  <div class="input-group margin-bottom col-md-5">
                    <div class="input-group-addon">
                      <i class="fa fa-user"></i>
                    </div>
                    <input type="text" name="login" value="jose.paulo" class="form-control" placeholder="Login" />
                  </div><!-- /.input group -->
                  <div class="row">
                    <div class="col-xs-12 margin-bottom">
                      <button type="submit" class="btn btn-primary">Alterar</button>
                      <?php if ($this->usarioLogado->perfil == 'cliente') : ?>
                      <button type="submit" class="btn btn-warning">Alterar Senha</button>
                      <button type="button" class="btn btn-danger inativar">Encerrar Conta</button>
                      <?php else : ?>
                      <button type="submit" class="btn btn-warning">Gerar Nova Senha</button>
                      <button type="button" class="btn btn-danger inativar">Inativar</button>
                      <?php endif; ?>
                    </div><!-- /.col -->
                  </div>
                </form>
              </div>
            </div>
          </div><!-- /.box -->
        </div><!-- /.col -->
      </div>   <!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- InputMask -->
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.date.extensions.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.extensions.js"); ?>" type="text/javascript"></script>

<!-- iCheck 1.0.1 -->
<script src="<?php echo $this->baseUrl("plugins/iCheck/icheck.min.js"); ?>" type="text/javascript"></script>

<script type="text/javascript">
$(function () {
  $("#datemask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
  $("[data-mask]").inputmask();
  $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
    checkboxClass: 'icheckbox_minimal-red',
    radioClass: 'iradio_minimal-red'
  });
  $('.inativar').click(function(e) {
    e.preventDefault();

    var id = '.modal';

    var maskHeight = $(document).height();
    var maskWidth = $(window).width();

    $('#mask').css({'width':maskWidth,'height':maskHeight});

    $('#mask').fadeIn(1000);
    $('#mask').fadeTo("slow",0.8);

    var winH = $(window).height();
    var winW = $(window).width();

    $(id).css('top',  winH/2-$(id).height()/3);
    $(id).css('left', winW/2-$(id).width()/2);

    $(id).fadeIn(2000);
  });

  $('.window .close, .window .close2').click(function (e) {
    e.preventDefault();
    $('#mask').hide();
    $('.window').hide();
  });

  $('#mask').click(function () {
    $(this).hide();
    $('.window').hide();
  });
});
</script>