<!-- daterange picker -->
<link href="<?php echo $this->baseUrl("plugins/daterangepicker/daterangepicker-bs3.css"); ?>" rel="stylesheet" type="text/css" />

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
                <form action="" method="post">

                  <div class="form-group">
                    <label>Selecione o Período:</label>
                    <div class="input-group" style="width: 655px;">
                      <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                      </div>
                      <input type="text" name="data" class="form-control pull-right" id="reservation" />
                    </div><!-- /.input group -->
                  </div><!-- /.form group -->

                  <div class="col-md-3">
                    <label>Valor</label>
                    <div class="input-group">
                      <div class="input-group-addon">
                        R$
                      </div>
                      <input type="text" name="valor" class="form-control dinheiro" placeholder="Valor" required />
                    </div><!-- /.input group -->
                  </div>

                  <div class="col-md-3">
                    <label>Satus</label>
                    <div class="input-group">
                      <select name="status" >
                        <option value="entrada">Entrada</option>
                        <option value="saida">Saída</option>
                        <option value="caneclado">Cancelado</option>
                      </select>
                    </div><!-- /.input group -->
                  </div>

                  <div class="col-md-3">
                    <label>Estacionamento</label>
                    <div class="input-group">
                      <select name="id_estacionamento" >
                        <?php foreach($this->estacionamentos as $estacionamento): ?>
                        <option value="<?php echo $estacionamento['id']; ?>"><?php echo $estacionamento['nome']; ?></option>
                        <?php endforeach; ?>
                      </select>
                    </div><!-- /.input group -->
                  </div>

                  <div class="col-md-3">
                    <label>Veiculo</label>
                    <div class="input-group">
                      <select name="id_veiculo" >
                        <?php foreach($this->veiculos as $veiculo): ?>
                        <option value="<?php echo $veiculo['id']; ?>"><?php echo $veiculo['placa']; ?></option>
                        <?php endforeach; ?>
                      </select>
                    </div><!-- /.input group -->
                  </div>

                  <div class="row">
                    <div class="col-md-12 margin-bottom">
                      <button type="submit" class="btn btn-success">Cadastrar</button>
                    </div><!-- /.col -->
                  </div>
                </form>
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- InputMask -->
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.date.extensions.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.extensions.js"); ?>" type="text/javascript"></script>

<!-- date-range-picker -->
<script src="<?php echo $this->baseUrl("plugins/daterangepicker/daterangepicker.js"); ?>" type="text/javascript"></script>

<script type="text/javascript">
$(function () {
  $("#datemask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
  $("[data-mask]").inputmask();
  $('#reservation').daterangepicker({timePicker: true, timePickerIncrement: 30, format: 'MM/DD/YYYY h:mm'});
});
</script>