<!-- DATA TABLES -->
<link href="<?php echo $this->baseUrl("plugins/datatables/dataTables.bootstrap.css"); ?>" rel="stylesheet" type="text/css" />
<style type="text/css">
#mask {
  position:absolute;
  left:0;
  top:0;
  z-index:9000;
  background-color:#000;
  display:none;
}
.window {
  position:absolute;
  top: auto;
  bottom: auto;
  right: auto;
  left: auto;
  display:none;
  z-index:9999;
}
.modal {
  background: transparent!important;
}
</style>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Clientes
        <small>lista de clientes</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="<?php echo $this->baseUrl("/"); ?>"><i class="fa fa-dashboard"></i> Início</a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'cliente'), null, 1); ?>">Clientes</a></li>
        <li class="active">lista</li>
      </ol>
    </section>

    <div class="modal window modal-danger">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><i class="icon fa fa-warning"></i> Atenção!</h4>
          </div>
          <div class="modal-body">
            <p>Você tem certeza que deseja <strong>Inativar</strong> esse Cliente?</p>
          </div>
          <div class="modal-footer buttons">
            <button type="button" class="btn btn-outline">Sim</button>
            <button type="button" class="btn btn-outline close2">Não</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <!-- Máscara para cobrir a tela -->
    <div id="mask"></div>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box box-danger">
            <div class="box-header">
              <a href="<?php echo $this->url(array('controller' => 'cliente', 'action' => 'new'), null, 1); ?>">
                <button type="button" class="btn btn-danger">Novo Cliente</button>
              </a>
            </div><!-- /.box-header -->
            <div class="box-body">
              <table id="tabelaClientes" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Nome</th>
                    <th>E-mail</th>
                    <th>Telefone</th>
                    <th>Login</th>
                    <th>Ações</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>Pedro Costa</td>
                    <td>pedro@gmail.com</td>
                    <td>(48) 9999-9878</td>
                    <td>pedro.costa</td>
                    <td class="col-sm-2">
                      <a href="<?php echo $this->url(array('controller' => 'cliente', 'action' => 'edit'), null, 1); ?>"><span class="label label-primary">Editar</span></a>
                      <a href="<?php echo $this->url(array('controller' => 'veiculo'), null, 1); ?>"><span class="label label-info">Automóveis</span></a>
                      <?php if ($this->usuarioLogado->perfil == 'master' || $this->usuarioLogado->perfil == 'funcionario') : ?>
                      <a href="<?php echo $this->url(array('controller' => 'relatorio', 'action' => 'movimentacaoclienteadministrador'), null, 1); ?>"><span class="label label-success">Movimentações</span></a>
                      <?php else : ?>
                      <a href="<?php echo $this->url(array('controller' => 'relatorio', 'action' => 'movimentacaocliente'), null, 1); ?>"><span class="label label-success">Movimentações</span></a>
                      <?php endif; ?>
                      <a href="" ><span class="label label-danger inativar">Inativar</span></a>
                    </td>
                  </tr>
                  <tr>
                    <td>Maria Tereza Souza</td>
                    <td>maria.souza@gmail.com</td>
                    <td>(48) 9669-4275</td>
                    <td>maria.souza</td>
                    <td class="col-sm-2">
                      <a href="<?php echo $this->url(array('controller' => 'cliente', 'action' => 'edit'), null, 1); ?>"><span class="label label-primary">Editar</span></a>
                      <a href="<?php echo $this->url(array('controller' => 'veiculo'), null, 1); ?>"><span class="label label-info">Automóveis</span></a>
                      <?php if ($this->usuarioLogado->perfil == 'master' || $this->usuarioLogado->perfil == 'funcionario') : ?>
                      <a href="<?php echo $this->url(array('controller' => 'relatorio', 'action' => 'movimentacaoclienteadministrador'), null, 1); ?>"><span class="label label-success">Movimentações</span></a>
                      <?php else : ?>
                      <a href="<?php echo $this->url(array('controller' => 'relatorio', 'action' => 'movimentacaocliente'), null, 1); ?>"><span class="label label-success">Movimentações</span></a>
                      <?php endif; ?>
                      <a href="" ><span class="label label-danger inativar">Inativar</span></a>
                    </td>
                  </tr>
                  <tr>
                    <td>Júlio Antunes</td>
                    <td>julio.antunes@gmail.com</td>
                    <td>(48) 8856-9654</td>
                    <td>julio.antunes</td>
                    <td class="col-sm-2">
                      <a href="<?php echo $this->url(array('controller' => 'cliente', 'action' => 'edit'), null, 1); ?>"><span class="label label-primary">Editar</span></a>
                      <a href="<?php echo $this->url(array('controller' => 'veiculo'), null, 1); ?>"><span class="label label-info">Automóveis</span></a>
                      <?php if ($this->usuarioLogado->perfil == 'master' || $this->usuarioLogado->perfil == 'funcionario') : ?>
                      <a href="<?php echo $this->url(array('controller' => 'relatorio', 'action' => 'movimentacaoclienteadministrador'), null, 1); ?>"><span class="label label-success">Movimentações</span></a>
                      <?php else : ?>
                      <a href="<?php echo $this->url(array('controller' => 'relatorio', 'action' => 'movimentacaocliente'), null, 1); ?>"><span class="label label-success">Movimentações</span></a>
                      <?php endif; ?>
                      <a href="" ><span class="label label-danger inativar">Inativar</span></a>
                    </td>
                  </tr>
                  <tr>
                    <td>Roberto Amaral</td>
                    <td>roberto.amaral@gmail.com</td>
                    <td>(48) 8896-4521</td>
                    <td>roberto.amaral</td>
                    <td class="col-sm-2">
                      <a href="<?php echo $this->url(array('controller' => 'cliente', 'action' => 'edit'), null, 1); ?>"><span class="label label-primary">Editar</span></a>
                      <a href="<?php echo $this->url(array('controller' => 'veiculo'), null, 1); ?>"><span class="label label-info">Automóveis</span></a>
                      <?php if ($this->usuarioLogado->perfil == 'master' || $this->usuarioLogado->perfil == 'funcionario') : ?>
                      <a href="<?php echo $this->url(array('controller' => 'relatorio', 'action' => 'movimentacaoclienteadministrador'), null, 1); ?>"><span class="label label-success">Movimentações</span></a>
                      <?php else : ?>
                      <a href="<?php echo $this->url(array('controller' => 'relatorio', 'action' => 'movimentacaocliente'), null, 1); ?>"><span class="label label-success">Movimentações</span></a>
                      <?php endif; ?>
                      <a href="" ><span class="label label-danger inativar">Inativar</span></a>
                    </td>
                  </tr>
                  <tr>
                    <td>Renato Felisbino</td>
                    <td>renato.felisbino@gmail.com</td>
                    <td>(48) 8154-8961</td>
                    <td>renato.felisbino</td>
                    <td class="col-sm-2">
                      <a href="<?php echo $this->url(array('controller' => 'cliente', 'action' => 'edit'), null, 1); ?>"><span class="label label-primary">Editar</span></a>
                      <a href="<?php echo $this->url(array('controller' => 'veiculo'), null, 1); ?>"><span class="label label-info">Automóveis</span></a>
                      <?php if ($this->usuarioLogado->perfil == 'master' || $this->usuarioLogado->perfil == 'funcionario') : ?>
                      <a href="<?php echo $this->url(array('controller' => 'relatorio', 'action' => 'movimentacaoclienteadministrador'), null, 1); ?>"><span class="label label-success">Movimentações</span></a>
                      <?php else : ?>
                      <a href="<?php echo $this->url(array('controller' => 'relatorio', 'action' => 'movimentacaocliente'), null, 1); ?>"><span class="label label-success">Movimentações</span></a>
                      <?php endif; ?>
                      <a href="" ><span class="label label-danger inativar">Inativar</span></a>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div><!-- /.box-body -->
          </div><!-- /.box -->
        </div><!-- /.col -->
      </div><!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- DATA TABES SCRIPT -->
<script src="<?php echo $this->baseUrl("plugins/datatables/jquery.dataTables.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/datatables/dataTables.bootstrap.js"); ?>" type="text/javascript"></script>

<script type="text/javascript">
$(function () {
  $("#tabelaClientes").dataTable();
  $('.inativar').click(function(e) {
    e.preventDefault();

    var id = '.modal';

    var maskHeight = $(document).height();
    var maskWidth = $(window).width();

    $('#mask').css({'width':maskWidth,'height':maskHeight});

    $('#mask').fadeIn(1000);
    $('#mask').fadeTo("slow",0.8);

    var winH = $(window).height();
    var winW = $(window).width();

    $(id).css('top',  winH/2-$(id).height()/3);
    $(id).css('left', winW/2-$(id).width()/2);

    $(id).fadeIn(2000);
  });

  $('.window .close, .window .close2').click(function (e) {
    e.preventDefault();
    $('#mask').hide();
    $('.window').hide();
  });

  $('#mask').click(function () {
    $(this).hide();
    $('.window').hide();
  });
});
</script>