<!-- DATA TABLES -->
<link href="<?php echo $this->baseUrl("plugins/datatables/dataTables.bootstrap.css"); ?>" rel="stylesheet" type="text/css" />

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Clientes
        <small>lista de clientes</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="<?php echo $this->baseUrl("/"); ?>"><i class="fa fa-dashboard"></i> Início</a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'cliente'), null, 1); ?>">Clientes</a></li>
        <li class="active">lista</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box box-danger">
            <div class="box-header">
              <a href="<?php echo $this->url(array('controller' => 'cliente', 'action' => 'new'), null, 1); ?>">
                <button type="button" class="btn btn-danger">Novo Cliente</button>
              </a>
            </div><!-- /.box-header -->
            <div class="box-body">
              <table id="tabelaClientes" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Nome</th>
                    <th>E-mail</th>
                    <th>Telefone</th>
                    <th>Login</th>
                    <th>Ações</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>Pedro Costa</td>
                    <td>pedro@gmail.com</td>
                    <td>(48) 9999-9878</td>
                    <td>pedro.costa</td>
                    <td class="col-sm-2">
                      <a class="text-red" href="/cliente/edit"><span class="label label-primary">Editar</span></a>
                      <a class="text-red" href="/cliente/edit"><span class="label label-info">Automóveis</span></a>
                      <a class="text-red" href="/cliente/edit"><span class="label label-success">Movimentações</span></a>
                      <a class="text-red" href=""><span class="label label-danger">Inativar</span></a>
                    </td>
                  </tr>
                  <tr>
                    <td>Maria Tereza Souza</td>
                    <td>maria.souza@gmail.com</td>
                    <td>(48) 9669-4275</td>
                    <td>maria.souza</td>
                    <td class="col-sm-2">
                      <a class="text-red" href="/cliente/edit"><span class="label label-primary">Editar</span></a>
                      <a class="text-red" href="/cliente/edit"><span class="label label-info">Automóveis</span></a>
                      <a class="text-red" href="/cliente/edit"><span class="label label-success">Movimentações</span></a>
                      <a class="text-red" href=""><span class="label label-danger">Inativar</span></a>
                    </td>
                  </tr>
                  <tr>
                    <td>Júlio Antunes</td>
                    <td>julio.antunes@gmail.com</td>
                    <td>(48) 8856-9654</td>
                    <td>julio.antunes</td>
                    <td class="col-sm-2">
                      <a class="text-red" href="/cliente/edit"><span class="label label-primary">Editar</span></a>
                      <a class="text-red" href="/cliente/edit"><span class="label label-info">Automóveis</span></a>
                      <a class="text-red" href="/cliente/edit"><span class="label label-success">Movimentações</span></a>
                      <a class="text-red" href=""><span class="label label-danger">Inativar</span></a>
                    </td>
                  </tr>
                  <tr>
                    <td>Roberto Amaral</td>
                    <td>roberto.amaral@gmail.com</td>
                    <td>(48) 8896-4521</td>
                    <td>roberto.amaral</td>
                    <td class="col-sm-2">
                      <a class="text-red" href="/cliente/edit"><span class="label label-primary">Editar</span></a>
                      <a class="text-red" href="/cliente/edit"><span class="label label-info">Automóveis</span></a>
                      <a class="text-red" href="/cliente/edit"><span class="label label-success">Movimentações</span></a>
                      <a class="text-red" href=""><span class="label label-danger">Inativar</span></a>
                    </td>
                  </tr>
                  <tr>
                    <td>Renato Felisbino</td>
                    <td>renato.felisbino@gmail.com</td>
                    <td>(48) 8154-8961</td>
                    <td>renato.felisbino</td>
                    <td class="col-sm-2">
                      <a class="text-red" href="/cliente/edit"><span class="label label-primary">Editar</span></a>
                      <a class="text-red" href="/cliente/edit"><span class="label label-info">Automóveis</span></a>
                      <a class="text-red" href="/cliente/edit"><span class="label label-success">Movimentações</span></a>
                      <a class="text-red" href=""><span class="label label-danger">Inativar</span></a>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div><!-- /.box-body -->
          </div><!-- /.box -->
        </div><!-- /.col -->
      </div><!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- DATA TABES SCRIPT -->
<script src="<?php echo $this->baseUrl("plugins/datatables/jquery.dataTables.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/datatables/dataTables.bootstrap.js"); ?>" type="text/javascript"></script>

<script type="text/javascript">
$(function () {
    $("#tabelaClientes").dataTable();
});
</script>