<!-- iCheck for checkboxes and radio inputs -->
<link href="<?php echo $this->baseUrl("plugins/iCheck/all.css"); ?>" rel="stylesheet" type="text/css" />

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Clientes
        <small>novo cliente</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="<?php echo $this->baseUrl("/"); ?>"><i class="fa fa-dashboard"></i> Início</a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'cliente'), null, 1); ?>">Clientes</a></li>
        <li class="active">novo</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="box box-danger">
            <div class="box-header">
              <h3 class="box-title">Novo Cliente</h3>
            </div>
            <div class="box-body">
              <div class="form-group">
                <!-- form start -->
                <form action="" method="post">
                <div class="form-group">
                    <label class="tipoPessoa">
                      <input type="radio" name="tipoPessoa" value="pessoaFisica" class="minimal-red" checked /> Pessoa Física
                    </label>
                    <label class="tipoPessoa">
                      <input type="radio" name="tipoPessoa" value="pessoaJuridica" class="minimal-red tipoPessoa" /> Pessoa Jurídica
                    </label>
                  </div>
                  <label>Nome</label>
                  <div class="input-group margin-bottom col-md-6">
                    <div class="input-group-addon">
                      <i class="fa fa-user"></i>
                    </div>
                    <input type="text" name="nome" class="form-control" placeholder="Nome" />
                  </div><!-- /.input group -->
                  <label>E-mail</label>
                  <div class="input-group margin-bottom col-md-6">
                    <div class="input-group-addon">
                      <i class="fa fa-envelope"></i>
                    </div>
                    <input type="text" name="email" class="form-control" placeholder="E-mail" />
                  </div><!-- /.input group -->
                  <label>Telefone</label>
                  <div class="input-group margin-bottom col-md-3">
                    <div class="input-group-addon">
                      <i class="fa fa-phone"></i>
                    </div>
                    <input type="text" name="telefone" class="form-control" placeholder="Telefone" data-inputmask='"mask": "(99) 9999-9999"' data-mask />
                  </div><!-- /.input group -->
                  <div class="box">
                    <div class="box-header">
                      <h3 class="box-title">Dados do Documento</h3>
                    </div>
                    <div id="pessoaFisica" class="box-body">
                      <div class="row">
                        <div class="col-xs-3">
                          <label>CPF</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="cpf" class="form-control" placeholder="CPF" data-inputmask='"mask": "999.999.999-99"' data-mask />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-xs-3">
                          <label>RG</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="rg" class="form-control" placeholder="RG" />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-xs-4">
                          <label>Data de Nascimento</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" name="dataNascimento" class="form-control" placeholder="Data de Nascimento" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask />
                          </div><!-- /.input group -->
                        </div>
                      </div>
                    </div><!-- /.box-body -->
                    <div id="pessoaJuridica" class="box-body" style="display: none;">
                      <div class="row">
                        <div class="col-md-4">
                          <label>CNPJ</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="cnpj" class="form-control" placeholder="CNPJ" data-inputmask='"mask": "99.999.999/9999-99"' data-mask />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-xs-4">
                          <label>Data de Fundação</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" name="dataFundacao" class="form-control" placeholder="Data de Fundação" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask />
                          </div><!-- /.input group -->
                        </div>
                      </div>
                    </div><!-- /.box-body -->
                  </div><!-- /.box -->
                  <label>Login</label>
                  <div class="input-group margin-bottom col-md-5">
                    <div class="input-group-addon">
                      <i class="fa fa-user"></i>
                    </div>
                    <input type="text" name="login" class="form-control" placeholder="Login" />
                  </div><!-- /.input group -->
                  <div class="row">
                    <div class="col-xs-4 margin-bottom">
                      <button type="submit" class="btn btn-success">Cadastrar</button>
                    </div><!-- /.col -->
                  </div>
                </form>
              </div>
            </div>
          </div><!-- /.box -->
        </div><!-- /.col -->
      </div>   <!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- InputMask -->
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.date.extensions.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.extensions.js"); ?>" type="text/javascript"></script>

<!-- iCheck 1.0.1 -->
<script src="<?php echo $this->baseUrl("plugins/iCheck/icheck.min.js"); ?>" type="text/javascript"></script>

<script type="text/javascript">
$(function () {
  $("#datemask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
  $("[data-mask]").inputmask();
  $('input[type="radio"].minimal-red').iCheck({
    radioClass: 'iradio_minimal-red'
  });
  $('.tipoPessoa').click(function () {
    if ($(this).find('input').val() === 'pessoaFisica') {
      $('#pessoaJuridica').hide();
      $('#pessoaFisica').show();
    } else {
      $('#pessoaFisica').hide();
      $('#pessoaJuridica').show();
    }
  });
  $('.iCheck-helper').click(function () {
    if ($(this).parent('div').find('input').val() === 'pessoaFisica') {
      $('#pessoaJuridica').hide();
      $('#pessoaFisica').show();
    } else {
      $('#pessoaFisica').hide();
      $('#pessoaJuridica').show();
    }
  });
});
</script>