<!-- iCheck for checkboxes and radio inputs -->
<link href="<?php echo $this->baseUrl("plugins/iCheck/all.css"); ?>" rel="stylesheet" type="text/css" />

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Clientes
        <small>novo</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="<?php echo $this->baseUrl("/"); ?>"><i class="fa fa-dashboard"></i> Início</a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'cliente'), null, 1); ?>">Clientes</a></li>
        <li class="active">novo</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <?php if ($this->erro) : ?>
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h4><i class="icon fa fa-warning"></i> Atenção!</h4>
          <?php echo $this->erro; ?>
        </div>
      <?php endif; ?>

      <div class="row">
        <div class="col-md-12">
          <div class="box box-danger">
            <div class="box-header">
              <h3 class="box-title">Novo Cliente</h3>
            </div>
            <div class="box-body">
              <div class="form-group">
                <!-- form start -->
                <form action="" method="post">
                <div class="form-group">
                    <label class="tipoPessoa">
                      <input type="radio" name="tipo" value="fisica" class="minimal-red tipoPessoa" <?php if (!isset($_POST['tipo']) || $_POST['tipo'] == 'fisica') echo 'checked'; ?> /> Pessoa Física
                    </label>
                    <label class="tipoPessoa">
                      <input type="radio" name="tipo" value="juridica" class="minimal-red tipoPessoa" <?php if (isset($_POST['tipo']) && $_POST['tipo'] == 'juridica') echo 'checked'; ?> /> Pessoa Jurídica
                    </label>
                  </div>
                  <label>Nome</label>
                  <div class="input-group margin-bottom col-md-6">
                    <div class="input-group-addon">
                      <i class="fa fa-user"></i>
                    </div>
                    <input type="text" name="nome" value="<?php echo $this->form->nome->getValue(); ?>" class="form-control" placeholder="Nome" required />
                  </div><!-- /.input group -->
                  <label>E-mail</label>
                  <div class="input-group margin-bottom col-md-6">
                    <div class="input-group-addon">
                      <i class="fa fa-envelope"></i>
                    </div>
                    <input type="text" name="email" value="<?php echo $this->form->email->getValue(); ?>" class="form-control" placeholder="E-mail" required />
                  </div><!-- /.input group -->
                  <label>Telefone</label>
                  <div class="input-group margin-bottom col-md-3">
                    <div class="input-group-addon">
                      <i class="fa fa-phone"></i>
                    </div>
                    <input type="text" name="telefone" value="<?php echo $this->form->telefone->getValue(); ?>" class="form-control" placeholder="Telefone" data-inputmask='"mask": "(99) 9999-9999"' data-mask required />
                  </div><!-- /.input group -->
                  <div class="box">
                    <div class="box-header">
                      <h3 class="box-title">Dados do Documento</h3>
                    </div>
                    <div id="pessoaFisica" class="box-body" <?php if (isset($_POST['tipo']) && $_POST['tipo'] == 'juridica') echo 'style="display: none;"'; ?> >
                      <div class="row">
                        <div class="col-md-4">
                          <label>CPF</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="cpf" value="<?php echo $this->form->cpf->getValue(); ?>" class="form-control" placeholder="CPF" data-inputmask='"mask": "999.999.999-99"' data-mask required />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-md-3">
                          <label>RG</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="rg" value="<?php echo $this->form->rg->getValue(); ?>" class="form-control" placeholder="RG" required />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-md-4">
                          <label>Data de Nascimento</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" name="data_nascimento" value="<?php echo $this->formatoData($this->form->data_nascimento->getValue()); ?>" class="form-control" placeholder="Data de Nascimento" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask required />
                          </div><!-- /.input group -->
                        </div>
                      </div>
                    </div><!-- /.box-body -->
                    <div id="pessoaJuridica" class="box-body" <?php if (!isset($_POST['tipo']) || $_POST['tipo'] == 'fisica') echo 'style="display: none;"'; ?> >
                      <div class="row">
                        <div class="col-md-4">
                          <label>CNPJ</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="cnpj" value="<?php echo $this->form->cnpj->getValue(); ?>" class="form-control" placeholder="CNPJ" data-inputmask='"mask": "99.999.999/9999-99"' data-mask />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-md-4">
                          <label>Data de Fundação</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" name="data_fundacao" value="<?php echo $this->formatoData($this->form->data_fundacao->getValue()); ?>" class="form-control" placeholder="Data de Fundação" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask />
                          </div><!-- /.input group -->
                        </div>
                      </div>
                    </div><!-- /.box-body -->
                  </div><!-- /.box -->
                  <label>Login</label>
                  <div class="input-group margin-bottom col-md-5">
                    <div class="input-group-addon">
                      <i class="fa fa-user"></i>
                    </div>
                    <input type="text" name="login" value="<?php echo $this->form->login->getValue(); ?>" class="form-control" placeholder="Login" />
                  </div><!-- /.input group -->
                  <div class="row">
                    <div class="col-md-12 margin-bottom">
                      <button type="submit" class="btn btn-success">Cadastrar</button>
                    </div><!-- /.col -->
                  </div>
                </form>
              </div>
            </div>
          </div><!-- /.box -->
        </div><!-- /.col -->
      </div>   <!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- InputMask -->
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.date.extensions.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.extensions.js"); ?>" type="text/javascript"></script>

<!-- iCheck 1.0.1 -->
<script src="<?php echo $this->baseUrl("plugins/iCheck/icheck.min.js"); ?>" type="text/javascript"></script>

<script type="text/javascript">
$(function () {
  $("#datemask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
  $("[data-mask]").inputmask();
  $('input[type="radio"].minimal-red').iCheck({
    radioClass: 'iradio_minimal-red'
  });
  $('.tipoPessoa').click(function () {
    if ($(this).find('input').val() === 'fisica') {
      $('#pessoaJuridica').hide();
      $('#pessoaFisica').show();
    } else {
      $('#pessoaFisica').hide();
      $('#pessoaJuridica').show();
    }
    alteraObrigatoriedade($(this).find('input').val());
  });
  $('.iCheck-helper').click(function () {
    if ($(this).parent('div').find('input').val() === 'fisica') {
      $('#pessoaJuridica').hide();
      $('#pessoaFisica').show();
    } else {
      $('#pessoaFisica').hide();
      $('#pessoaJuridica').show();
    }
    alteraObrigatoriedade($(this).parent('div').find('input').val());
  });

  function alteraObrigatoriedade(tipo) {
    if (tipo === 'fisica') {
      $('input:text[name="cpf"]').attr("required", true);
      $('input:text[name="rg"]').attr("required", true);
      $('input:text[name="data_nascimento"]').attr("required", true);
      $('input:text[name="cnpj"]').removeAttr("required");
      $('input:text[name="data_fundacao"]').removeAttr("required");
    } else {
      $('input:text[name="cnpj"]').attr("required", true);
      $('input:text[name="data_fundacao"]').attr("required", true);
      $('input:text[name="cpf"]').removeAttr("required");
      $('input:text[name="rg"]').removeAttr("required");
      $('input:text[name="data_nascimento"]').removeAttr("required");
    }
  }
});
</script>