<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Página Inicial
      <small>Gerenciamento</small>
    </h1>
    <ol class="breadcrumb">
      <li><i class="fa fa-dashboard"></i> Página Inicial</li>
      <li class="active">Gerenciamento</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-green">
          <div class="inner">
            <h3><sup style="font-size: 20px">R$</sup> <?php echo $this->formatoDinheiro($this->cliente['saldo']); ?></h3>
            <p>Saldo do Crédito</p>
          </div>
          <div class="icon">
            <i class="ion ion-stats-bars"></i>
          </div>
          <a href="#" class="small-box-footer">Comprar Crédito <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div><!-- ./col -->
    </div><!-- /.row -->

    <div class="row">
      <div class="col-md-8">
        <div class="box box-info">
          <div class="box-header with-border">
            <h3 class="box-title">Últimas Movimentações</h3>
          </div><!-- /.box-header -->
          <div class="box-body">
            <div class="table-responsive">
              <table class="table no-margin">
                <thead>
                  <tr>
                    <th>Placa</th>
                    <th>Entrada / Saida</th>
                    <th>Data e Hora</th>
                    <th>Valor Debitado</th>
                    <th>Saldo</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td><a href="">ABC4545</a></td>
                    <td><span class="label label-danger">Saída</span></td>
                    <td>13/05/2015 12:06</td>
                    <td><span class="text-red">R$ 8,00</span></td>
                    <td><span class="text-green">R$ 74,00</span></td>
                  </tr>
                  <tr>
                    <td><a href="">ABC4545</a></td>
                    <td><span class="label label-success">Entrada</span></td>
                    <td>13/05/2015 08:15</td>
                    <td><span class="text-red"></span></td>
                    <td><span class="text-green">R$ 82,00</span></td>
                  </tr>
                  <tr>
                    <td><a href="">ABC4545</a></td>
                    <td><span class="label label-warning">Cancelado</span></td>
                    <td>12/05/2015 09:30</td>
                    <td><span class="text-red"></span></td>
                    <td><span class="text-green">R$ 82,00</span></td>
                  </tr>
                  <tr>
                    <td><a href="">ABC4545</a></td>
                    <td><span class="label label-danger">Saída</span></td>
                    <td>11/05/2015 18:36</td>
                    <td><span class="text-red">R$ 10,00</span></td>
                    <td><span class="text-green">R$ 82,00</span></td>
                  </tr>
                  <tr>
                    <td><a href="">ABC4545</a></td>
                    <td><span class="label label-success">Entrada</span></td>
                    <td>11/05/2015 13:26</td>
                    <td><span class="text-red"></span></td>
                    <td><span class="text-green">R$ 92,00</span></td>
                  </tr>
                  <tr>
                    <td><a href="">ABC4545</a></td>
                    <td><span class="label label-danger">Saída</span></td>
                    <td>11/05/2015 12:11</td>
                    <td><span class="text-red">R$ 8,00</span></td>
                    <td><span class="text-green">R$ 92,00</span></td>
                  </tr>
                  <tr>
                    <td><a href="">ABC4545</a></td>
                    <td><span class="label label-success">Entrada</span></td>
                    <td>11/05/2015 08:30</td>
                    <td><span class="text-red"></span></td>
                    <td><span class="text-green">R$ 100,00</span></td>
                  </tr>
                </tbody>
              </table>
            </div><!-- /.table-responsive -->
          </div><!-- /.box-body -->
          <div class="box-footer clearfix">
            <a href="<?php echo $this->url(array('controller' => 'relatorio', 'action' => 'movimentacaocliente'), null, 1); ?>" class="btn btn-sm btn-info btn-flat pull-right">Ver Todas Movimentações</a>
          </div><!-- /.box-footer -->
        </div><!-- /.box -->
      </div><!-- /.col -->
      <div class='col-md-4'>
        <div class="box box-info">
          <div class="box-header with-border">
            <h3 class="box-title">Meus Veículos</h3>
          </div><!-- /.box-header -->
          <div class="box-body">
            <div class="table-responsive">
              <table class="table no-margin">
                <thead>
                  <tr>
                    <th>Placa</th>
                    <th>Cor</th>
                    <th>Marca</th>
                    <th>Modelo</th>
                  </tr>
                </thead>
                <tbody>
                  <?php foreach($this->veiculos as $veiculo): ?>
                  <tr>
                    <td><a href=""><?php echo $veiculo['placa']; ?></a></td>
                    <td><div class='<?php echo $veiculo['cor']; ?> color-palette'><span>&nbsp</span></div></td>
                    <td><?php echo $veiculo['marca']; ?></td>
                    <td><?php echo $veiculo['modelo']; ?></td>
                  </tr>
                  <?php endforeach; ?>
                </tbody>
              </table>
            </div><!-- /.table-responsive -->
          </div><!-- /.box-body -->
          <div class="box-footer clearfix">
            <a href="<?php echo $this->url(array('controller' => 'veiculo'), null, 1); ?>" class="btn btn-sm btn-info btn-flat pull-right">Meus Veículos</a>
          </div><!-- /.box-footer -->
        </div><!-- /.box -->
        <div class="box box-info">
          <div class="box-header with-border">
            <h3 class="box-title">Estacionamentos Ultilizados</h3>
          </div><!-- /.box-header -->
          <div class="box-body">
            <div class="row">
              <div class="col-md-8">
                <div class="chart-responsive">
                  <canvas id="pieChart" height="150"></canvas>
                </div><!-- ./chart-responsive -->
              </div><!-- /.col -->
              <div class="col-md-4">
                <ul class="chart-legend clearfix">
                  <li><i class="fa fa-circle-o text-red"></i> Estacionamento 1</li>
                  <li><i class="fa fa-circle-o text-green"></i> Estacionamento 2</li>
                  <li><i class="fa fa-circle-o text-yellow"></i> Estacionamento 3</li>
                  <li><i class="fa fa-circle-o text-aqua"></i> Estacionamento 4</li>
                </ul>
              </div><!-- /.col -->
            </div><!-- /.row -->
          </div><!-- /.box-body -->
        </div><!-- /.box -->
      </div><!-- /.col -->
    </div><!-- /.row -->
  </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- ChartJS 1.0.1 -->
<script src="<?php echo $this->baseUrl("plugins/chartjs/Chart.min.js"); ?>" type="text/javascript"></script>

<script type="text/javascript">
$(function () {
  //-------------
  //- PIE CHART -
  //-------------
  // Get context with jQuery - using jQuery's .get() method.
  var pieChartCanvas = $("#pieChart").get(0).getContext("2d");
  var pieChart = new Chart(pieChartCanvas);
  var PieData = [
    {
      value: 50,
      color: "#f56954",
      highlight: "#f56954",
      label: "Estacionamento 1"
    },
    {
      value: 30,
      color: "#00a65a",
      highlight: "#00a65a",
      label: "Estacionamento 2"
    },
    {
      value: 10,
      color: "#f39c12",
      highlight: "#f39c12",
      label: "Estacionamento 3"
    },
    {
      value: 2,
      color: "#00c0ef",
      highlight: "#00c0ef",
      label: "Estacionamento 4"
    }
  ];
  var pieOptions = {
    //Boolean - Whether we should show a stroke on each segment
    segmentShowStroke: true,
    //String - The colour of each segment stroke
    segmentStrokeColor: "#fff",
    //Number - The width of each segment stroke
    segmentStrokeWidth: 1,
    //Number - The percentage of the chart that we cut out of the middle
    percentageInnerCutout: 50, // This is 0 for Pie charts
    //Number - Amount of animation steps
    animationSteps: 100,
    //String - Animation easing effect
    animationEasing: "easeOutBounce",
    //Boolean - Whether we animate the rotation of the Doughnut
    animateRotate: true,
    //Boolean - Whether we animate scaling the Doughnut from the centre
    animateScale: false,
    //Boolean - whether to make the chart responsive to window resizing
    responsive: true,
    // Boolean - whether to maintain the starting aspect ratio or not when responsive, if set to false, will take up entire container
    maintainAspectRatio: false,
    //String - A legend template
    legendTemplate: "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<segments.length; i++){%><li><span style=\"background-color:<%=segments[i].fillColor%>\"></span><%if(segments[i].label){%><%=segments[i].label%><%}%></li><%}%></ul>",
    //String - A tooltip template
    tooltipTemplate: "<%=value %> vezes <%=label%>"
  };
  //Create pie or douhnut chart
  // You can switch between pie and douhnut using the method below.
  pieChart.Doughnut(PieData, pieOptions);
  //-----------------
  //- END PIE CHART -
});
</script>