<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Página Inicial
      <small>Gerenciamento</small>
    </h1>
    <ol class="breadcrumb">
      <li><i class="fa fa-dashboard"></i> Página Inicial</li>
      <li class="active">Gerenciamento</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-green">
          <div class="inner">
            <h3><sup style="font-size: 20px">R$</sup> <?php echo $this->formatoDinheiro($this->cliente['saldo']); ?></h3>
            <p>Saldo do Crédito</p>
          </div>
          <div class="icon">
            <i class="ion ion-stats-bars"></i>
          </div>
          <a href="#" class="small-box-footer">Comprar Crédito <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div><!-- ./col -->
    </div><!-- /.row -->

    <div class="row">
      <div class="col-md-8">
        <div class="box box-info">
          <div class="box-header with-border">
            <h3 class="box-title">Últimas Movimentações</h3>
          </div><!-- /.box-header -->
          <div class="box-body">
            <div class="table-responsive">
              <table class="table no-margin">
                <thead>
                  <tr>
                    <th>Placa</th>
                    <th>Entrada / Saida</th>
                    <th>Data e Hora</th>
                    <th>Valor Debitado</th>
                  </tr>
                </thead>
                <tbody>
                  <?php foreach($this->movimentacoes as $movimentacao): ?>
                   <tr>
                     <td><?php echo $movimentacao['placa']; ?></td>
                     <td><span class="label <?php echo ($movimentacao['status'] == 'Entrada') ? "label-success" : "label-danger"; ?>"><?php echo $movimentacao['status']; ?></span></td>
                     <td><?php echo (!empty($movimentacao['saida'])) ? $this->formatoData($movimentacao['saida'],true) : $this->formatoData($movimentacao['entrada'],true); ?></td>
                     <td><span class="text-red"><?php echo (!empty($movimentacao['valor'])) ? "R$ ".$this->formatoDinheiro($movimentacao['valor']) : ''; ?></span></td>
                   </tr>
                   <?php endforeach; ?>
                </tbody>
              </table>
            </div><!-- /.table-responsive -->
          </div><!-- /.box-body -->
          <div class="box-footer clearfix">
            <a href="<?php echo $this->url(array('controller' => 'relatorio', 'action' => 'movimentacaocliente', 'id' =>$this->cliente['id']), null, 1); ?>" class="btn btn-sm btn-info btn-flat pull-right">Ver Todas Movimentações</a>
          </div><!-- /.box-footer -->
        </div><!-- /.box -->
      </div><!-- /.col -->
      <div class='col-md-4'>
        <div class="box box-info">
          <div class="box-header with-border">
            <h3 class="box-title">Meus Veículos</h3>
          </div><!-- /.box-header -->
          <div class="box-body">
            <div class="table-responsive">
              <table class="table no-margin">
                <thead>
                  <tr>
                    <th>Marca</th>
                    <th>Modelo</th>
                    <th>Cor</th>
                    <th>Placa</th>
                  </tr>
                </thead>
                <tbody>
                  <?php foreach($this->veiculos as $veiculo): ?>
                  <tr>
                    <td><?php echo $veiculo['marca']; ?></td>
                    <td><?php echo $veiculo['modelo']; ?></td>
                    <td><div class='<?php echo $veiculo['cor']; ?> color-palette'><span>&nbsp</span></div></td>
                    <td><?php echo $veiculo['placa']; ?></td>
                  </tr>
                  <?php endforeach; ?>
                </tbody>
              </table>
            </div><!-- /.table-responsive -->
          </div><!-- /.box-body -->
          <div class="box-footer clearfix">
            <a href="<?php echo $this->url(array('controller' => 'cliente', 'action' => 'veiculos', 'id' => $this->cliente['id']), null, 1); ?>" class="btn btn-sm btn-info btn-flat pull-right">Meus Veículos</a>
          </div><!-- /.box-footer -->
        </div><!-- /.box -->
        <div class="box box-info">
          <div class="box-header with-border">
            <h3 class="box-title">Estacionamentos Ultilizados</h3>
          </div><!-- /.box-header -->
          <div class="box-body">
            <div class="row">
              <div class="col-md-8">
                <div class="chart-responsive">
                  <canvas id="pieChart" height="150"></canvas>
                </div><!-- ./chart-responsive -->
              </div><!-- /.col -->
              <div class="col-md-4">
                <ul class="chart-legend clearfix">
                  <?php foreach($this->estacionamentoUsados as $estacionamento): ?>
                  <li style="color: <?php echo $estacionamento['cor']; ?>"><i class="fa fa-circle-o"></i> <?php echo $estacionamento['nome']; ?></li>
                  <?php endforeach; ?>
                </ul>
              </div><!-- /.col -->
            </div><!-- /.row -->
          </div><!-- /.box-body -->
        </div><!-- /.box -->
      </div><!-- /.col -->
    </div><!-- /.row -->
  </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- ChartJS 1.0.1 -->
<script src="<?php echo $this->baseUrl("plugins/chartjs/Chart.min.js"); ?>" type="text/javascript"></script>

<script type="text/javascript">
$(function () {
  //-------------
  //- PIE CHART -
  //-------------
  // Get context with jQuery - using jQuery's .get() method.
  var pieChartCanvas = $("#pieChart").get(0).getContext("2d");
  var pieChart = new Chart(pieChartCanvas);
  var PieData = [<?php echo $this->usoEstacionamento; ?>];
  var pieOptions = {
    //Boolean - Whether we should show a stroke on each segment
    segmentShowStroke: true,
    //String - The colour of each segment stroke
    segmentStrokeColor: "#fff",
    //Number - The width of each segment stroke
    segmentStrokeWidth: 1,
    //Number - The percentage of the chart that we cut out of the middle
    percentageInnerCutout: 50, // This is 0 for Pie charts
    //Number - Amount of animation steps
    animationSteps: 100,
    //String - Animation easing effect
    animationEasing: "easeOutBounce",
    //Boolean - Whether we animate the rotation of the Doughnut
    animateRotate: true,
    //Boolean - Whether we animate scaling the Doughnut from the centre
    animateScale: false,
    //Boolean - whether to make the chart responsive to window resizing
    responsive: true,
    // Boolean - whether to maintain the starting aspect ratio or not when responsive, if set to false, will take up entire container
    maintainAspectRatio: false,
    //String - A legend template
    legendTemplate: "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<segments.length; i++){%><li><span style=\"background-color:<%=segments[i].fillColor%>\"></span><%if(segments[i].label){%><%=segments[i].label%><%}%></li><%}%></ul>",
    //String - A tooltip template
    tooltipTemplate: "<%=value %> vezes <%=label%>"
  };
  //Create pie or douhnut chart
  // You can switch between pie and douhnut using the method below.
  pieChart.Doughnut(PieData, pieOptions);
  //-----------------
  //- END PIE CHART -
});
</script>