<!-- DATA TABLES -->
<link href="<?php echo $this->baseUrl("plugins/datatables/dataTables.bootstrap.css"); ?>" rel="stylesheet" type="text/css" />
<style type="text/css">
#vagas .vaga {
  margin: 3px;
}
</style>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Página Inicial
      <small>Gerenciamento</small>
    </h1>
    <ol class="breadcrumb">
      <li><i class="fa fa-dashboard"></i> Página Inicial</li>
      <li class="active">Gerenciamento</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Small boxes (Stat box) -->
            <div class="row">
              <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-blue">
                  <div class="inner">
                    <h3 id="vagaDisponivel">0</h3>
                    <p>Vagas Disponíveis</p>
                  </div>
                  <div class="icon">
                    <i class="ion ion-pie-graph"></i>
                  </div>
                </div>
              </div><!-- ./col -->
              <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-yellow">
                  <div class="inner">
                    <h3 id="vagaOcupada">0</h3>
                    <p>Vagas Ocupadas</p>
                  </div>
                  <div class="icon">
                    <i class="ion ion-pie-graph"></i>
                  </div>
                </div>
              </div><!-- ./col -->
            </div><!-- /.row -->

          <!--TABELA DE VAGAS-->
          <div class="row">
            <div class="col-md-6">
              <div class="box box-danger">
                <div class="box-header">
                  <h3 class="box-title">Vagas</h3>
                  <div style="float: right;">
                    <a class="btn btn-primary" >&nbsp</a> Vaga Livre
                    <a class="btn btn-warning" >&nbsp</a> Vaga Ocupada
                  </div>
                </div>
                <div class="box-body pad table-responsive">
                  <div id="vagas">
                    <div class="box">
                      <div class="box-header">
                        <h3 class="box-title">Vagas Avulsas</h3>
                      </div>
                      <div class="box-body">
                        <a class="btn btn-primary vaga livreva">001</a>
                        <a class="btn btn-primary vaga livreva">002</a>
                        <a class="btn btn-primary vaga livreva">003</a>
                        <a class="btn btn-primary vaga livreva">004</a>
                        <a class="btn btn-primary vaga livreva">005</a>
                        <a class="btn btn-primary vaga livreva">006</a>
                        <a class="btn btn-primary vaga livreva">007</a>
                        <a class="btn btn-primary vaga livreva">008</a>
                        <a class="btn btn-primary vaga livreva">009</a>
                        <a class="btn btn-primary vaga livreva">010</a>
                        <a class="btn btn-primary vaga livreva">011</a>
                        <a class="btn btn-primary vaga livreva">012</a>
                        <a class="btn btn-primary vaga livreva">013</a>
                        <a class="btn btn-primary vaga livreva">014</a>
                        <a class="btn btn-primary vaga livreva">015</a>
                        <a class="btn btn-primary vaga livreva">016</a>
                        <a class="btn btn-primary vaga livreva">017</a>
                        <a class="btn btn-primary vaga livreva">018</a>
                        <a class="btn btn-primary vaga livreva">019</a>
                        <a class="btn btn-primary vaga livreva">020</a>
                        <a class="btn btn-primary vaga livreva">021</a>
                        <a class="btn btn-primary vaga livreva">022</a>
                        <a class="btn btn-primary vaga livreva">023</a>
                        <a class="btn btn-primary vaga livreva">024</a>
                        <a class="btn btn-primary vaga livreva">025</a>
                        <a class="btn btn-primary vaga livreva">026</a>
                        <a class="btn btn-primary vaga livreva">027</a>
                        <a class="btn btn-primary vaga livreva">028</a>
                        <a class="btn btn-primary vaga livreva">029</a>
                        <a class="btn btn-primary vaga livreva">030</a>
                        <a class="btn btn-primary vaga livreva">031</a>
                        <a class="btn btn-primary vaga livreva">032</a>
                        <a class="btn btn-primary vaga livreva">033</a>
                        <a class="btn btn-primary vaga livreva">034</a>
                        <a class="btn btn-primary vaga livreva">035</a>
                        <a class="btn btn-primary vaga livreva">036</a>
                        <a class="btn btn-primary vaga livreva">037</a>
                        <a class="btn btn-primary vaga livreva">038</a>
                        <a class="btn btn-primary vaga livreva">039</a>
                        <a class="btn btn-primary vaga livreva">040</a>
                        <a class="btn btn-primary vaga livreva">041</a>
                        <a class="btn btn-primary vaga livreva">042</a>
                        <a class="btn btn-primary vaga livreva">043</a>
                        <a class="btn btn-primary vaga livreva">044</a>
                        <a class="btn btn-primary vaga livreva">045</a>
                        <a class="btn btn-primary vaga livreva">046</a>
                        <a class="btn btn-primary vaga livreva">047</a>
                        <a class="btn btn-primary vaga livreva">048</a>
                        <a class="btn btn-primary vaga livreva">049</a>
                        <a class="btn btn-primary vaga livreva">050</a>
                        <a class="btn btn-primary vaga livreva">051</a>
                        <a class="btn btn-primary vaga livreva">052</a>
                        <a class="btn btn-primary vaga livreva">053</a>
                        <a class="btn btn-primary vaga livreva">054</a>
                        <a class="btn btn-primary vaga livreva">055</a>
                        <a class="btn btn-primary vaga livreva">056</a>
                        <a class="btn btn-primary vaga livreva">057</a>
                        <a class="btn btn-primary vaga livreva">058</a>
                        <a class="btn btn-primary vaga livreva">059</a>
                        <a class="btn btn-primary vaga livreva">060</a>
                      </div>
                    </div>
                    <div class="box">
                      <div class="box-header">
                        <h3 class="box-title">Vagas Idosis e Deficientes Físicos</h3>
                      </div>
                      <div class="box-body">
                        <a class="btn btn-primary vaga livreve">061</a>
                        <a class="btn btn-primary vaga livreve">062</a>
                        <a class="btn btn-primary vaga livreve">063</a>
                        <a class="btn btn-primary vaga livreve">064</a>
                        <a class="btn btn-primary vaga livreve">065</a>
                        <a class="btn btn-primary vaga livreve">066</a>
                        <a class="btn btn-primary vaga livreve">067</a>
                        <a class="btn btn-primary vaga livreve">068</a>
                        <a class="btn btn-primary vaga livreve">069</a>
                        <a class="btn btn-primary vaga livreve">070</a>
                        <a class="btn btn-primary vaga livreve">071</a>
                        <a class="btn btn-primary vaga livreve">072</a>
                        <a class="btn btn-primary vaga livreve">073</a>
                        <a class="btn btn-primary vaga livreve">074</a>
                        <a class="btn btn-primary vaga livreve">075</a>
                        <a class="btn btn-primary vaga livreve">076</a>
                        <a class="btn btn-primary vaga livreve">077</a>
                        <a class="btn btn-primary vaga livreve">078</a>
                        <a class="btn btn-primary vaga livreve">079</a>
                        <a class="btn btn-primary vaga livreve">080</a>
                      </div>
                    </div>
                    <div class="box">
                      <div class="box-header">
                        <h3 class="box-title">Vagas Aluguel</h3>
                      </div>
                      <div class="box-body">
                        <a class="btn btn-primary vaga livrevl">081</a>
                        <a class="btn btn-primary vaga livrevl">082</a>
                        <a class="btn btn-primary vaga livrevl">083</a>
                        <a class="btn btn-primary vaga livrevl">084</a>
                        <a class="btn btn-primary vaga livrevl">085</a>
                        <a class="btn btn-primary vaga livrevl">086</a>
                        <a class="btn btn-primary vaga livrevl">087</a>
                        <a class="btn btn-primary vaga livrevl">088</a>
                        <a class="btn btn-primary vaga livrevl">089</a>
                        <a class="btn btn-primary vaga livrevl">090</a>
                        <a class="btn btn-primary vaga livrevl">091</a>
                        <a class="btn btn-primary vaga livrevl">092</a>
                        <a class="btn btn-primary vaga livrevl">093</a>
                        <a class="btn btn-primary vaga livrevl">094</a>
                        <a class="btn btn-primary vaga livrevl">095</a>
                        <a class="btn btn-primary vaga livrevl">096</a>
                        <a class="btn btn-primary vaga livrevl">097</a>
                        <a class="btn btn-primary vaga livrevl">098</a>
                        <a class="btn btn-primary vaga livrevl">099</a>
                        <a class="btn btn-primary vaga livrevl">100</a>
                      </div>
                    </div>
                  </div>
                </div><!-- /.box -->
              </div>
            </div><!-- /.col -->
            <div class="col-md-6">
              <div class="box box-danger">
                <div class="box-header">
                  <h3 class="box-title">Grupos</h3>
                </div>
                <div class="box-body">
                  <table class="table table-striped">
                    <thead>
                      <tr>
                        <th style="width: 200px" >Grupo de Vaga</th>
                        <th style="width: 180px">Num. de Vagas do Grupo</th>
                        <th style="width: 200px">Num. de Vagas Disponíveis</th>
                        <th style="width: 180px">Num. de Vagas Ocupadas</th>
                        <th>Ocupação</th>
                        <th style="width: 40px">Porcentagem</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Vagas Avulsas</td>
                        <td>60</td>
                        <td><span id="nVAl">60</span></td>
                        <td><span id="nVAo">0</span></td>
                        <td>
                          <div class="progress progress-xs">
                            <div id="bVAo" class="progress-bar progress-bar-green" style="width: 0%"></div>
                          </div>
                        </td>
                        <td><span id="pVAo" class="badge bg-green">0,00%</span></td>
                      </tr>
                      <tr>
                        <td>Vagas Idosis e Deficientes Físicos</td>
                        <td>20</td>
                        <td><span id="nVEl">20</span></td>
                        <td><span id="nVEo">0</span></td>
                        <td>
                          <div class="progress progress-xs">
                            <div id="bVEo" class="progress-bar progress-bar-yellow" style="width: 0%"></div>
                          </div>
                        </td>
                        <td><span id="pVEo" class="badge bg-yellow">0,00%</span></td>
                      </tr>
                      <tr>
                        <td>Vagas Aluguel</td>
                        <td>20</td>
                        <td><span id="nVLl">20</span></td>
                        <td><span id="nVLo">0</span></td>
                        <td>
                          <div class="progress progress-xs progress-striped active">
                            <div id="bVLo" class="progress-bar progress-bar-primary" style="width: 0%"></div>
                          </div>
                        </td>
                        <td><span id="pVLo" class="badge bg-light-blue">0,00%</span></td>
                      </tr>
                    </tbody>
                  </table>
                </div><!-- /.box-body -->
              </div>
              <div class="box box-danger">
                <div class="box-header">
                  <h3 class="box-title">Últimas Movimentações</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="example2" class="table table-bordered table-striped table-hover">
                    <thead>
                      <tr>
                        <th>Placa</th>
                        <th>Cliente</th>
                        <th>Entrada / Saida</th>
                        <th>Data e Hora</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td><a href="">DEF1234</a></td>
                        <td>Marcelo Matos</td>
                        <td><span class="label label-danger">Saída</span></td>
                        <td>13/05/2015 20:01</td>
                      </tr>
                      <tr>
                        <td><a href="">DEF1234</a></td>
                        <td>Marcelo Matos</td>
                        <td><span class="label label-success">Entrada</span></td>
                        <td>13/05/2015 19:26</td>
                      </tr>
                      <tr>
                        <td><a href="">MNB4321</a></td>
                        <td>Maria Rocha</td>
                        <td><span class="label label-danger">Saída</span></td>
                        <td>13/05/2015 18:06</td>
                      </tr>
                      <tr>
                        <td><a href="">ABC4545</a></td>
                        <td>John Doe</td>
                        <td><span class="label label-danger">Saída</span></td>
                        <td>13/05/2015 17:30</td>
                      </tr>
                      <tr>
                        <td><a href="">JHG5648</a></td>
                        <td>Pedro</td>
                        <td><span class="label label-danger">Saída</span></td>
                        <td>13/05/2015 16:45</td>
                      </tr>
                      <tr>
                        <td><a href="">JHG5648</a></td>
                        <td>Pedro</td>
                        <td><span class="label label-success">Entrada</span></td>
                        <td>13/05/2015 13:26</td>
                      </tr>
                      <tr>
                        <td><a href="">MNB4321</a></td>
                        <td>Maria Rocha</td>
                        <td><span class="label label-success">Entrada</span></td>
                        <td>13/05/2015 13:21</td>
                      </tr>
                      <tr>
                        <td><a href="">ABC4545</a></td>
                        <td>John Doe</td>
                        <td><span class="label label-success">Entrada</span></td>
                        <td>13/05/2015 13:10</td>
                      </tr>
                      <tr>
                        <td><a href="">ABC4545</a></td>
                        <td>John Doe</td>
                        <td><span class="label label-danger">Saída</span></td>
                        <td>13/05/2015 12:06</td>
                      </tr>
                      <tr>
                        <td><a href="">ABC4545</a></td>
                        <td>John Doe</td>
                        <td><span class="label label-success">Entrada</span></td>
                        <td>13/05/2015 08:06</td>
                      </tr>
                    </tbody>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- ./row -->

          <div class="box box-danger">
            <div class="box-header">
              <h3 class="box-title">Estacionados</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped table-hover">
                <thead>
                  <tr>
                    <th>Vaga</th>
                    <th>Grupo de Vaga</th>
                    <th>Placa</th>
                    <th>Cliente</th>
                    <th>Créditos Disponíveis</th>
                    <th>Hora de Chegada</th>
                    <th>Tempo Utilizado</th>
                    <th>Valor Gasto</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>40</td>
                    <td>Avulso</td>
                    <td><a href="">ABC4545</a></td>
                    <td>John Doe</td>
                    <td>R$200,00</td>
                    <td>14:00</td>
                    <td>1:24</td>
                    <td>R$3,00</td>
                  </tr>
                  <tr>
                    <td>40</td>
                    <td>Avulso</td>
                    <td><a href="">ABC4545</a></td>
                    <td>John Doe</td>
                    <td>R$200,00</td>
                    <td>14:00</td>
                    <td>1:24</td>
                    <td>R$3,00</td>
                  </tr>
                  <tr>
                    <td>40</td>
                    <td>Avulso</td>
                    <td><a href="">ABC4545</a></td>
                    <td>John Doe</td>
                    <td>R$200,00</td>
                    <td>14:00</td>
                    <td>1:24</td>
                    <td>R$3,00</td>
                  </tr>
                  <tr>
                    <td>40</td>
                    <td>Avulso</td>
                    <td><a href="">ABC4545</a></td>
                    <td>John Doe</td>
                    <td>R$200,00</td>
                    <td>14:00</td>
                    <td>1:24</td>
                    <td>R$3,00</td>
                  </tr>
                </tbody>
              </table>
            </div><!-- /.box-body -->
          </div><!-- /.box -->
  </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- DATA TABES SCRIPT -->
<script src="<?php echo $this->baseUrl("plugins/datatables/jquery.dataTables.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/datatables/dataTables.bootstrap.js"); ?>" type="text/javascript"></script>

<!-- page script -->
<script type="text/javascript">
  $(function () {
    $("#example1").dataTable();
    $('#example2').dataTable();

    var livre = $(".livreva").length + $(".livreve").length + $(".livrevl").length;
    var ocupada = $(".ocupadava").length + $(".ocupadave").length + $(".ocupadavl").length;
    $('#vagaDisponivel').html(livre);
    $('#vagaOcupada').html(ocupada);

    setInterval(function () {
      var index = Math.floor((Math.random() * 200));

      $('.vaga:eq(' + index + ')').toggleClass('btn-warning');
      $('.vaga:eq(' + index + ')').toggleClass('btn-primary');

      if (index < 60) {
        $('.vaga:eq(' + index + ')').toggleClass('livreva');
        $('.vaga:eq(' + index + ')').toggleClass('ocupadava');
        atualizaVA();
      } else if (index >= 60 && index < 80) {
        $('.vaga:eq(' + index + ')').toggleClass('livreve');
        $('.vaga:eq(' + index + ')').toggleClass('ocupadave');
        atualizaVE();
      } else {
        $('.vaga:eq(' + index + ')').toggleClass('livrevl');
        $('.vaga:eq(' + index + ')').toggleClass('ocupadavl');
        atualizaVL();
      }

      var livre = $(".livreva").length + $(".livreve").length + $(".livrevl").length;
      var ocupada = $(".ocupadava").length + $(".ocupadave").length + $(".ocupadavl").length;
      $('#vagaDisponivel').html(livre);
      $('#vagaOcupada').html(ocupada);

    }, 1000);

    function atualizaVA() {
      var valivre = $(".livreva").length;
      var vaocupada = $(".ocupadava").length;
      var vaper = ((vaocupada * 100) / (valivre + vaocupada));

      $('#nVAl').text(valivre);
      $('#nVAo').text(vaocupada);
      $('#bVAo').css("width", vaper + '%');
      $('#pVAo').text(vaper.toFixed(2).replace(".", ",") + '%');
    }

    function atualizaVE() {
      var velivre = $(".livreve").length;
      var veocupada = $(".ocupadave").length;
      var veper = ((veocupada * 100) / (velivre + veocupada));

      $('#nVEl').text(velivre);
      $('#nVEo').text(veocupada);
      $('#bVEo').css("width", veper + '%');
      $('#pVEo').text(veper.toFixed(2).replace(".", ",") + '%');
    }

    function atualizaVL() {
      var vllivre = $(".livrevl").length;
      var vlocupada = $(".ocupadavl").length;
      var vlper = ((vlocupada * 100) / (vllivre + vlocupada)) ;

      $('#nVLl').text(vllivre);
      $('#nVLo').text(vlocupada);
      $('#bVLo').css("width", vlper + '%');
      $('#pVLo').text(vlper.toFixed(2).replace(".", ",") + '%');
    }
  });
</script>