<!-- DATA TABLES -->
<link href="<?php echo $this->baseUrl("plugins/datatables/dataTables.bootstrap.css"); ?>" rel="stylesheet" type="text/css" />
<style type="text/css">
#vagas .vaga {
  margin: 3px;
}
</style>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      <?php echo $this->estacionamento['nome']; ?>
      <small>Gerenciamento</small>
    </h1>
    <ol class="breadcrumb">
      <li><i class="fa fa-dashboard"></i> Página Inicial</li>
      <li class="active">Gerenciamento</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Small boxes (Stat box) -->
            <div class="row">
              <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-blue">
                  <div class="inner">
                    <h3 id="vagaDisponivel">0</h3>
                    <p>Vagas Disponíveis</p>
                  </div>
                  <div class="icon">
                    <i class="ion ion-pie-graph"></i>
                  </div>
                </div>
              </div><!-- ./col -->
              <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-yellow">
                  <div class="inner">
                    <h3 id="vagaOcupada">0</h3>
                    <p>Vagas Ocupadas</p>
                  </div>
                  <div class="icon">
                    <i class="ion ion-pie-graph"></i>
                  </div>
                </div>
              </div><!-- ./col -->
            </div><!-- /.row -->

          <!--TABELA DE VAGAS-->
          <div class="row">
            <div class="col-md-6">
              <div class="box box-danger">
                <div class="box-header">
                  <h3 class="box-title">Vagas</h3>
                  <div style="float: right;">
                    <a class="btn btn-primary" >&nbsp</a> Vaga Livre
                    <a class="btn btn-warning" >&nbsp</a> Vaga Ocupada
                  </div>
                </div>
                <div class="box-body pad table-responsive">
                  <div id="vagas">
                    <div class="box">
                      <div class="box-header">
                        <h3 class="box-title">Vagas Comuns</h3>
                      </div>
                      <div class="box-body">
                        <?php for ($i = 1; $i <= $this->estacionamento['nr_vaga_comum']; $i++): ?>
                        <a class="btn btn-primary vaga livreva"><?php echo str_pad($i, 3, "0", STR_PAD_LEFT);?></a>
                        <?php endfor; ?>
                      </div>
                    </div>
                    <div class="box">
                      <div class="box-header">
                        <h3 class="box-title">Vagas Especiais</h3>
                      </div>
                      <div class="box-body">
                        <?php for ($i = (1 + $this->estacionamento['nr_vaga_comum']); $i <= ($this->estacionamento['nr_vaga_comum'] + $this->estacionamento['nr_vaga_especial']); $i++): ?>
                        <a class="btn btn-primary vaga livreve"><?php echo str_pad($i, 3, "0", STR_PAD_LEFT);?></a>
                        <?php endfor; ?>
                      </div>
                    </div>
                    <div class="box">
                      <div class="box-header">
                        <h3 class="box-title">Vagas Aluguéis</h3>
                      </div>
                      <div class="box-body">
                        <?php for ($i = (1 + $this->estacionamento['nr_vaga_comum'] + $this->estacionamento['nr_vaga_especial']); $i <= ($this->estacionamento['nr_vaga_comum'] + $this->estacionamento['nr_vaga_especial'] + $this->estacionamento['nr_vaga_aluguel']); $i++): ?>
                        <a class="btn btn-primary vaga livrevl"><?php echo str_pad($i, 3, "0", STR_PAD_LEFT);?></a>
                        <?php endfor; ?>
                      </div>
                    </div>
                  </div>
                </div><!-- /.box -->
              </div>
            </div><!-- /.col -->
            <div class="col-md-6">
              <div class="box box-danger">
                <div class="box-header">
                  <h3 class="box-title">Grupos</h3>
                </div>
                <div class="box-body">
                  <table class="table table-striped">
                    <thead>
                      <tr>
                        <th style="width: 200px" >Grupo de Vaga</th>
                        <th style="width: 180px">Num. de Vagas do Grupo</th>
                        <th style="width: 200px">Num. de Vagas Disponíveis</th>
                        <th style="width: 180px">Num. de Vagas Ocupadas</th>
                        <th>Ocupação</th>
                        <th style="width: 40px">Porcentagem</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Vagas Comuns</td>
                        <td><?php echo $this->estacionamento['nr_vaga_comum']; ?></td>
                        <td><span id="nVAl"><?php echo $this->estacionamento['nr_vaga_comum']; ?></span></td>
                        <td><span id="nVAo">0</span></td>
                        <td>
                          <div class="progress progress-xs">
                            <div id="bVAo" class="progress-bar progress-bar-green" style="width: 0%"></div>
                          </div>
                        </td>
                        <td><span id="pVAo" class="badge bg-green">0,00%</span></td>
                      </tr>
                      <tr>
                        <td>Vagas Especiais</td>
                        <td><?php echo $this->estacionamento['nr_vaga_especial']; ?></td>
                        <td><span id="nVEl"><?php echo $this->estacionamento['nr_vaga_especial']; ?></span></td>
                        <td><span id="nVEo">0</span></td>
                        <td>
                          <div class="progress progress-xs">
                            <div id="bVEo" class="progress-bar progress-bar-yellow" style="width: 0%"></div>
                          </div>
                        </td>
                        <td><span id="pVEo" class="badge bg-yellow">0,00%</span></td>
                      </tr>
                      <tr>
                        <td>Vagas Aluguéis</td>
                        <td><?php echo $this->estacionamento['nr_vaga_aluguel']; ?></td>
                        <td><span id="nVLl"><?php echo $this->estacionamento['nr_vaga_aluguel']; ?></span></td>
                        <td><span id="nVLo">0</span></td>
                        <td>
                          <div class="progress progress-xs progress-striped active">
                            <div id="bVLo" class="progress-bar progress-bar-primary" style="width: 0%"></div>
                          </div>
                        </td>
                        <td><span id="pVLo" class="badge bg-light-blue">0,00%</span></td>
                      </tr>
                    </tbody>
                  </table>
                </div><!-- /.box-body -->
              </div>
              <div class="box box-danger">
                <div class="box-header">
                  <h3 class="box-title">Últimas Movimentações</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="example2" class="table table-bordered table-striped table-hover">
                    <thead>
                      <tr>
                        <th>Placa</th>
                        <th>Cliente</th>
                        <th>Entrada / Saida</th>
                        <th>Data e Hora</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php foreach($this->movimentacoes as $movimentacao): ?>
                      <tr>
                        <td><?php echo $movimentacao['placa']; ?></td>
                        <td><?php echo $movimentacao['nome']; ?></td>
                        <td><span class="label <?php echo ($movimentacao['status'] == 'Entrada') ? "label-success" : "label-danger"; ?>"><?php echo $movimentacao['status']; ?></span></td>
                        <td><?php echo (!empty($movimentacao['saida'])) ? $this->formatoData($movimentacao['saida'],true) : $this->formatoData($movimentacao['entrada'],true); ?></td>
                      </tr>
                      <?php endforeach; ?>
                    </tbody>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- ./row -->
  </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- DATA TABES SCRIPT -->
<script src="<?php echo $this->baseUrl("plugins/datatables/jquery.dataTables.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/datatables/dataTables.bootstrap.js"); ?>" type="text/javascript"></script>

<!-- page script -->
<script type="text/javascript">
  $(function () {
    $("#example1").dataTable();
    $('#example2').dataTable();

    var livre = $(".livreva").length + $(".livreve").length + $(".livrevl").length;
    var ocupada = $(".ocupadava").length + $(".ocupadave").length + $(".ocupadavl").length;
    $('#vagaDisponivel').html(livre);
    $('#vagaOcupada').html(ocupada);

    setInterval(function () {
      var index = Math.floor((Math.random() * 200));

      $('.vaga:eq(' + index + ')').toggleClass('btn-warning');
      $('.vaga:eq(' + index + ')').toggleClass('btn-primary');

      if (index < 60) {
        $('.vaga:eq(' + index + ')').toggleClass('livreva');
        $('.vaga:eq(' + index + ')').toggleClass('ocupadava');
        atualizaVA();
      } else if (index >= 60 && index < 80) {
        $('.vaga:eq(' + index + ')').toggleClass('livreve');
        $('.vaga:eq(' + index + ')').toggleClass('ocupadave');
        atualizaVE();
      } else {
        $('.vaga:eq(' + index + ')').toggleClass('livrevl');
        $('.vaga:eq(' + index + ')').toggleClass('ocupadavl');
        atualizaVL();
      }

      var livre = $(".livreva").length + $(".livreve").length + $(".livrevl").length;
      var ocupada = $(".ocupadava").length + $(".ocupadave").length + $(".ocupadavl").length;
      $('#vagaDisponivel').html(livre);
      $('#vagaOcupada').html(ocupada);

    }, 1000);

    function atualizaVA() {
      var valivre = $(".livreva").length;
      var vaocupada = $(".ocupadava").length;
      var vaper = ((vaocupada * 100) / (valivre + vaocupada));

      $('#nVAl').text(valivre);
      $('#nVAo').text(vaocupada);
      $('#bVAo').css("width", vaper + '%');
      $('#pVAo').text(vaper.toFixed(2).replace(".", ",") + '%');
    }

    function atualizaVE() {
      var velivre = $(".livreve").length;
      var veocupada = $(".ocupadave").length;
      var veper = ((veocupada * 100) / (velivre + veocupada));

      $('#nVEl').text(velivre);
      $('#nVEo').text(veocupada);
      $('#bVEo').css("width", veper + '%');
      $('#pVEo').text(veper.toFixed(2).replace(".", ",") + '%');
    }

    function atualizaVL() {
      var vllivre = $(".livrevl").length;
      var vlocupada = $(".ocupadavl").length;
      var vlper = ((vlocupada * 100) / (vllivre + vlocupada)) ;

      $('#nVLl').text(vllivre);
      $('#nVLo').text(vlocupada);
      $('#bVLo').css("width", vlper + '%');
      $('#pVLo').text(vlper.toFixed(2).replace(".", ",") + '%');
    }
  });
</script>