<div class="sed">
    <div class="container">
        <div class="sed1">
            <div class="col-md-4 sed-top">
                <div class="sed-left">
                    <div class="sed-con">
                        <i class="han"></i>
                    </div>
                    <div class="sed-data">
                        <h3>Sed viverra lectus</h3>
                        <h4>Vestibulum viverra ante</h4>
                    </div>
                    <div class="clearfix"> </div>
                </div>
                <p>Pellentesque fermentum  lipsu interdum ipsum, ut gravida justo sollicit ed sit am cenas dignissim ante vel enim hendrerit </p>
                <a href="#" class="read">READ ...</a>
            </div>
            <div class="col-md-4 sed-top">
                <div class="sed-left">
                    <div class="sed-con">
                        <i class="devi"></i>
                    </div>
                    <div class="sed-data">
                        <h3>Sed viverra lectus</h3>
                        <h4>Vestibulum viverra ante</h4>
                    </div>
                    <div class="clearfix"> </div>
                </div>
                <p>Pellentesque fermentum  lipsu interdum ipsum, ut gravida justo sollicit ed sit am cenas dignissim ante vel enim hendrerit </p>
                <a href="#" class="read">READ ...</a>
            </div>
            <div class="col-md-4 sed-bottom">
                <div class="sed-left">
                    <div class="sed-con">
                        <i class="pap"></i>
                    </div>
                    <div class="sed-data">
                        <h3>Sed viverra lectus</h3>
                        <h4>Vestibulum viverra ante</h4>
                    </div>
                    <div class="clearfix"> </div>
                </div>
                <p>Pellentesque fermentum  lipsu interdum ipsum, ut gravida justo sollicit ed sit am cenas dignissim ante vel enim hendrerit  </p>
                <a href="#" class="read">READ ...</a>
            </div>
            <div class="clearfix"> </div>
        </div>
        <div class="sed2">
            <div class="col-md-4 sed-top">
                <div class="sed-left">
                    <div class="sed-con">
                        <i class="solu"></i>
                    </div>
                    <div class="sed-data">
                        <h3>Sed viverra lectus</h3>
                        <h4>Vestibulum viverra ante</h4>
                    </div>
                    <div class="clearfix"> </div>
                </div>
                <p>Pellentesque fermentum  lipsu interdum ipsum, ut gravida justo sollicit ed sit am cenas dignissim ante vel enim hendrerit </p>
                <a href="#" class="read">READ ...</a>
            </div>
            <div class="col-md-4 sed-top">
                <div class="sed-left">
                    <div class="sed-con">
                        <i class="ranb"></i>
                    </div>
                    <div class="sed-data">
                        <h3>Sed viverra lectus</h3>
                        <h4>Vestibulum viverra ante</h4>
                    </div>
                    <div class="clearfix"> </div>
                </div>
                <p>Pellentesque fermentum  lipsu interdum ipsum, ut gravida justo sollicit ed sit am cenas dignissim ante vel enim hendrerit </p>
                <a href="#" class="read">READ ...</a>
            </div>
            <div class="col-md-4 sed-bottom">
                <div class="sed-left">
                    <div class="sed-con">
                        <i class="sett"></i>
                    </div>
                    <div class="sed-data">
                        <h3>Sed viverra lectus</h3>
                        <h4>Vestibulum viverra ante</h4>
                    </div>
                    <div class="clearfix"> </div>
                </div>
                <p>Pellentesque fermentum  lipsu interdum ipsum, ut gravida justo sollicit ed sit am cenas dignissim ante vel enim hendrerit </p>
                <a href="#" class="read">READ ...</a>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>