<!-- DATA TABLES -->
<link href="<?php echo $this->baseUrl("plugins/datatables/dataTables.bootstrap.css"); ?>" rel="stylesheet" type="text/css" />

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Página Inicial
      <small>Gerenciamento</small>
    </h1>
    <ol class="breadcrumb">
      <li class="active"><i class="fa fa-dashboard"></i> Página Inicial</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-md-3">
        <div class="small-box bg-red-gradient">
          <div class="inner">
            <h3><?php echo $this->quantidadeEstacionamento; ?></h3>
            <p>Número de Estacionamentos</p>
          </div>
          <div class="icon">
            <i class="ion ion-stats-bars"></i>
          </div>
          <a href="<?php echo $this->url(array('controller' => 'estacionamento'), null, 1); ?>" class="small-box-footer"> Lista de Estacionamentos <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
      <div class="col-md-3">
       <div class="small-box bg-green-gradient">
         <div class="inner">
           <h3><?php echo $this->quantidadeFuncionario; ?></h3>
           <p>Número de Funcionários</p>
         </div>
         <div class="icon">
           <i class="ion ion-ios-people-outline"></i>
         </div>
         <a href="<?php echo $this->url(array('controller' => 'funcionario'), null, 1); ?>" class="small-box-footer"> Lista de Funcionários <i class="fa fa-arrow-circle-right"></i></a>
       </div>
      </div>
    </div><!-- /.row -->
    <div class="row">
      <div class="col-md-6">
        <div class="box box-primary">
          <div class="box-header">
            <i class="fa fa-bar-chart-o"></i>
            <h3 class="box-title">Funcionários por Estacionamento</h3>
          </div>
          <div class="box-body">
            <div id="quant-funcionario" style="height: 300px;"></div>
          </div><!-- /.box-body-->
        </div><!-- /.box -->
      </div>
      <div class="col-md-6">
        <div class="box box-primary">
          <div class="box-header">
            <i class="fa fa-bar-chart-o"></i>
            <h3 class="box-title">% Salários por Estacionamento</h3>
          </div>
          <div class="box-body">
            <div id="perc-salario" style="height: 300px;"></div>
          </div><!-- /.box-body-->
        </div><!-- /.box -->
      </div>
      <div class="col-md-6">
        <div class="box box-primary">
          <div class="box-header">
            <i class="fa fa-bar-chart-o"></i>
            <h3 class="box-title">Movimentação Mensal</h3>
          </div>
          <div class="box-body">
            <div id="bar-chart" style="height: 153px;"></div>
          </div><!-- /.box-body-->
        </div>
      </div>
    </div><!-- /.row -->
  </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- FLOT CHARTS -->
<script src="<?php echo $this->baseUrl("plugins/flot/jquery.flot.min.js"); ?>"  type="text/javascript"></script>
<!-- FLOT PIE PLUGIN - also used to draw donut charts -->
<script src="<?php echo $this->baseUrl("plugins/flot/jquery.flot.pie.min.js"); ?>" type="text/javascript"></script>
<!-- FLOT CATEGORIES PLUGIN - Used to draw bar charts -->
<script src="<?php echo $this->baseUrl("plugins/flot/jquery.flot.categories.min.js"); ?>" type="text/javascript"></script>

<!-- page script -->
<script type="text/javascript">
$(function () {
  /*
  * BAR CHART
  * ---------
  */
  var bar_data = {
    data: [["January", 10], ["February", 8], ["March", 4], ["April", 13], ["May", 17], ["June", 9]],
    color: "#3c8dbc"
  };
  $.plot("#bar-chart", [bar_data], {
    grid: {
      borderWidth: 1,
      borderColor: "#f3f3f3",
      tickColor: "#f3f3f3"
    },
    series: {
      bars: {
        show: true,
        barWidth: 0.5,
        align: "center"
      }
    },
    xaxis: {
      mode: "categories",
      tickLength: 0
    }
  });
  /* END BAR CHART */

  /*
   * DONUT CHART
   */
  var grafico1 = [<?php echo $this->dadosGraficoSalarios; ?>];
  $.plot("#perc-salario", grafico1, {
    series: {
      pie: {
        show: true,
        radius: 1,
        innerRadius: 0.5,
        label: {
          show: true,
          radius: 2 / 3,
          formatter: labelFormatter,
          threshold: 0
        }

      }
    },
    legend: {
      show: true
    }
  });
  /*
   * END DONUT CHART
   */
  /*
   * DONUT CHART
   */
  var grafico2 = [<?php echo $this->dadosGraficoQuantFuncionarios; ?>];
  $.plot("#quant-funcionario", grafico2, {
    series: {
      pie: {
        show: true,
        radius: 1,
        innerRadius: 0.5,
        label: {
          show: true,
          radius: 2 / 3,
          formatter: labelFormatter,
          threshold: 0
        }

      }
    },
    legend: {
      show: true
    }
  });
  /*
   * END DONUT CHART
   */
  function labelFormatter(label, series) {
    return "<div style='font-size:13px; text-align:center; padding:2px; color: #fff; font-weight: 600;'>" + label + "<br/>" + Math.round(series.percent) + "%</div>";
  }
});
</script>