<!-- DATA TABLES -->
<link href="<?php echo $this->baseUrl("plugins/datatables/dataTables.bootstrap.css"); ?>" rel="stylesheet" type="text/css" />

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Veículos
        <small>novo e lista veículos</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="<?php echo $this->baseUrl("/"); ?>"><i class="fa fa-dashboard"></i> Início</a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'funcionario'), null, 1); ?>">Veículos</a></li>
        <li class="active">novo / lista</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="box box-danger">
            <div class="box-header">
              <h3 class="box-title">Novo Veículo</h3>
            </div>
            <div class="box-body">
              <div class="form-group">
                <!-- form start -->
                <form action="" method="post">
                  <label>Marca/Fabricante</label>
                  <div class="input-group margin-bottom col-md-4">
                    <select name="marca" class="form-control">
                      <option>-- Selecione a Marca/Fabricante --</option>
                      <option>Estacionamento 1</option>
                      <option>Estacionamento 2</option>
                      <option>Estacionamento 3</option>
                      <option>Estacionamento 4</option>
                    </select>
                  </div><!-- /.input group -->
                  <label>Modelo</label>
                  <div class="input-group margin-bottom col-md-4">
                    <select name="modelo" class="form-control">
                      <option>-- Selecione o Modelo --</option>
                      <option>Estacionamento 1</option>
                      <option>Estacionamento 2</option>
                      <option>Estacionamento 3</option>
                      <option>Estacionamento 4</option>
                    </select>
                  </div><!-- /.input group -->
                  <label>Cor</label>
                  <div class="input-group margin-bottom col-md-4">
                    <input type="text" name="cor" class="form-control" placeholder="Cor" />
                  </div><!-- /.input group -->
                  <label>Placa</label>
                  <div class="input-group margin-bottom col-md-2">
                    <input type="text" name="placa" class="form-control" placeholder="Placa" />
                  </div><!-- /.input group -->
                  <div class="row">
                    <div class="col-xs-4 margin-bottom">
                      <button type="submit" class="btn btn-success">Cadastrar</button>
                    </div><!-- /.col -->
                  </div>
                </form>
              </div>
            </div>
          </div><!-- /.box -->
        </div><!-- /.col -->
      </div>   <!-- /.row -->
      <div class="row">
        <div class="col-md-12">
          <div class="box box-danger">
            <div class="box-header">
              <h3 class="box-title">Veículos Cadastrados</h3>
            </div>
            <div class="box-body">
              <table id="tabelaAutomovel" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Placa</th>
                    <th>Modelo</th>
                    <th>Marca/Fabricante</th>
                    <th>Cor</th>
                    <th>Opções</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>IRS1836</td>
                    <td>Ford</td>
                    <td>Ecosport</td>
                    <td>Vermelho</td>
                    <td class="col-sm-2">
                      <a class="text-red" href=""><span class="label label-primary">Editar</span></a>
                      <a class="text-red" href=""><span class="label label-danger">Inativar</span></a>
                    </td>
                  </tr>
                  <tr>
                    <td>MKO2376</td>
                    <td>Renault</td>
                    <td>Sandeiro</td>
                    <td>Preto</td>
                    <td class="col-sm-2">
                      <a class="text-red" href="/cliente/edit"><span class="label label-primary">Editar</span></a>
                      <a class="text-red" href=""><span class="label label-danger">Inativar</span></a>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div><!-- /.box-body -->
          </div><!-- /.box -->
        </div><!-- /.col -->
      </div>   <!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- DATA TABES SCRIPT -->
<script src="<?php echo $this->baseUrl("plugins/datatables/jquery.dataTables.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/datatables/dataTables.bootstrap.js"); ?>" type="text/javascript"></script>

<!-- InputMask -->
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.date.extensions.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.extensions.js"); ?>" type="text/javascript"></script>

<script type="text/javascript">
  $(function () {
    $("#tabelaAutomovel").dataTable();
    $("#datemask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
    $("[data-mask]").inputmask();
  });
</script>