<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Funcionários
        <small>editar funcionário</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="<?php echo $this->baseUrl("/"); ?>"><i class="fa fa-dashboard"></i> Início</a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'funcionario'), null, 1); ?>">Funcionários</a></li>
        <li class="active">editar</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="box box-danger">
            <div class="box-header">
              <h3 class="box-title">Editar Funcionário</h3>
            </div>
            <div class="box-body">
              <div class="form-group">
                <!-- form start -->
                <form action="" method="post">
                  <label>Nome</label>
                  <div class="input-group margin-bottom col-md-4">
                    <div class="input-group-addon">
                      <i class="fa fa-user"></i>
                    </div>
                    <input type="text" name="nome" value="José Paulo" class="form-control" placeholder="Nome" />
                  </div><!-- /.input group -->
                  <label>E-mail</label>
                  <div class="input-group margin-bottom col-md-4">
                    <div class="input-group-addon">
                      <i class="fa fa-envelope"></i>
                    </div>
                    <input type="text" name="email" value="jose.paulo@gmail.com" class="form-control" placeholder="E-mail" />
                  </div><!-- /.input group -->
                  <label>Telefone</label>
                  <div class="input-group margin-bottom col-md-2">
                    <div class="input-group-addon">
                      <i class="fa fa-phone"></i>
                    </div>
                    <input type="text" name="telefone" value="(48) 9669-6789" class="form-control" placeholder="Telefone" data-inputmask='"mask": "(99) 9999-9999"' data-mask />
                  </div><!-- /.input group -->
                  <label>CPF</label>
                  <div class="input-group margin-bottom col-md-2">
                    <div class="input-group-addon">
                      <i class="fa fa-edit"></i>
                    </div>
                    <input type="text" name="cpf" value="844.614.208-25" class="form-control" placeholder="CPF" data-inputmask='"mask": "999.999.999-99"' data-mask />
                  </div><!-- /.input group -->
                  <label>RG</label>
                  <div class="input-group margin-bottom col-md-2">
                    <div class="input-group-addon">
                      <i class="fa fa-edit"></i>
                    </div>
                    <input type="text" name="rg" value="5.614.208" class="form-control" placeholder="RG" />
                  </div><!-- /.input group -->
                  <label>Data de Nascimento</label>
                  <div class="input-group margin-bottom col-md-2">
                    <div class="input-group-addon">
                      <i class="fa fa-calendar"></i>
                    </div>
                    <input type="text" name="dataNascimento" value="21/10/1986" class="form-control" placeholder="Data de Nascimento" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask />
                  </div><!-- /.input group -->
                  <label>Matrícula</label>
                  <div class="input-group margin-bottom col-md-2">
                    <div class="input-group-addon">
                      <i class="fa fa-edit"></i>
                    </div>
                    <input type="text" name="matricula" value="69587" class="form-control" placeholder="Matrícula" />
                  </div><!-- /.input group -->
                  <label>Data de Admissão</label>
                  <div class="input-group margin-bottom col-md-2">
                    <div class="input-group-addon">
                      <i class="fa fa-calendar"></i>
                    </div>
                    <input type="text" name="dataAdmissao" value="15/11/2014" class="form-control" placeholder="Data de Admissão" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask />
                  </div><!-- /.input group -->
                  <label>Salário</label>
                  <div class="input-group margin-bottom col-md-2">
                    <div class="input-group-addon">
                      <i class="fa">R$</i>
                    </div>
                    <input type="text" name="salario" value="1.500,00" class="form-control" placeholder="Salário" />
                  </div><!-- /.input group -->
                  <label>Login</label>
                  <div class="input-group margin-bottom col-md-2">
                    <div class="input-group-addon">
                      <i class="fa fa-user"></i>
                    </div>
                    <input type="text" name="login" value="jose.paulo" class="form-control" placeholder="Login" />
                  </div><!-- /.input group -->
                  <label>Estacionamento</label>
                  <div class="input-group margin-bottom col-md-2">
                    <div class="input-group-addon">
                      <i class="fa fa-edit"></i>
                    </div>
                    <select name="estacionamento" class="form-control">
                      <option>-- Selecione o Estacionamento --</option>
                      <option>Estacionamento 1</option>
                      <option>Estacionamento 2</option>
                      <option>Estacionamento 3</option>
                      <option>Estacionamento 4</option>
                    </select>
                  </div><!-- /.input group -->
                  <div class="row">
                    <div class="col-xs-12 margin-bottom">
                      <button type="submit" class="btn btn-danger">Alterar</button>
                      <button type="submit" class="btn btn-success">Gerar Nova Senha</button>
                      <button type="submit" class="btn btn-warning">Inativar</button>
                    </div><!-- /.col -->
                  </div>
                </form>
              </div>
            </div>
          </div><!-- /.box -->
        </div><!-- /.col -->
      </div>   <!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->