<style type="text/css">
#mask {
  position:absolute;
  left:0;
  top:0;
  z-index:9000;
  background-color:#000;
  display:none;
}

.window {
  position:absolute;
  top: auto;
  bottom: auto;
  right: auto;
  left: auto;
  display:none;
  z-index:9999;
}
.modal {
  background: transparent!important;
}
</style>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Funcionários
        <small>editar</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="<?php echo $this->baseUrl("/"); ?>"><i class="fa fa-dashboard"></i> Início</a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'funcionario'), null, 1); ?>">Funcionários</a></li>
        <li class="active">editar</li>
      </ol>
    </section>

    <div class="modal window">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><i class="icon fa fa-warning"></i> Atenção!</h4>
          </div>
          <div class="modal-body">
          </div>
          <div class="modal-footer buttons">
            <input type="hidden" id="status" />
            <button id="alterarStatus" type="button" class="btn btn-outline">Sim</button>
            <button type="button" class="btn btn-outline close2">Não</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <!-- Máscara para cobrir a tela -->
    <div id="mask"></div>

    <!-- Main content -->
    <section class="content">

    <?php if ($this->sucesso) : ?>
      <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <h4><i class="icon fa fa-check"></i> Sucesso!</h4>
        <?php echo $this->sucesso; ?>
      </div>
    <?php endif; ?>
    <?php if ($this->novo) : ?>
      <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <h4><i class="icon fa fa-check"></i> Sucesso!</h4>
        <?php echo $this->novo; ?>
      </div>
    <?php endif; ?>
    <?php if ($this->erro) : ?>
      <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <h4><i class="icon fa fa-warning"></i> Atenção!</h4>
        <?php echo $this->erro; ?>
      </div>
    <?php endif; ?>

      <div class="row">
        <div class="col-md-12">
          <div class="box box-danger">
            <div class="box-header">
              <h3 class="box-title">Editar Funcionário</h3>
            </div>
            <div class="box-body">
              <div class="form-group">
                <!-- form start -->
                <input type="hidden" id="id" value="<?php echo $this->funcionario['id']; ?>" />
                <form action="" method="post">
                  <label>Nome</label>
                  <div class="input-group margin-bottom col-md-6">
                    <div class="input-group-addon">
                      <i class="fa fa-user"></i>
                    </div>
                    <input type="text" id="nome" name="nome" value="<?php echo $this->form->nome->getValue(); ?>" class="form-control" placeholder="Nome" required />
                  </div><!-- /.input group -->
                  <label>E-mail</label>
                  <div class="input-group margin-bottom col-md-6">
                    <div class="input-group-addon">
                      <i class="fa fa-envelope"></i>
                    </div>
                    <input type="text" id="email" name="email" value="<?php echo $this->form->email->getValue(); ?>" class="form-control" placeholder="E-mail" required />
                  </div><!-- /.input group -->
                  <label>Telefone</label>
                  <div class="input-group margin-bottom col-md-3">
                    <div class="input-group-addon">
                      <i class="fa fa-phone"></i>
                    </div>
                    <input type="text" name="telefone" value="<?php echo $this->form->telefone->getValue(); ?>" class="form-control" placeholder="Telefone" data-inputmask='"mask": "(99) 9999-9999"' data-mask required />
                  </div><!-- /.input group -->
                  <div class="box">
                    <div class="box-header">
                      <h3 class="box-title">Dados do Documento</h3>
                    </div>
                    <div class="box-body">
                      <div class="row">
                        <div class="col-md-4">
                          <label>CPF</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="cpf" value="<?php echo $this->form->cpf->getValue(); ?>" class="form-control" placeholder="CPF" data-inputmask='"mask": "999.999.999-99"' data-mask required />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-md-3">
                          <label>RG</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="rg" value="<?php echo $this->form->rg->getValue(); ?>" class="form-control" placeholder="RG" required />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-md-4">
                          <label>Data de Nascimento</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" name="data_nascimento" value="<?php echo $this->formatoData($this->form->data_nascimento->getValue()); ?>" class="form-control" placeholder="Data de Nascimento" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask required />
                          </div><!-- /.input group -->
                        </div>
                      </div>
                    </div><!-- /.box-body -->
                  </div><!-- /.box -->

                  <div class="box">
                    <div class="box-header">
                      <h3 class="box-title">Dados de Funcionário</h3>
                    </div>
                    <div class="box-body">
                      <div class="row">
                        <div class="col-md-3">
                          <label>Matrícula</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="matricula" value="<?php echo $this->form->matricula->getValue(); ?>" class="form-control inteiro" placeholder="Matrícula" />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-md-4">
                          <label>Data de Admissão</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" name="data_admissao" value="<?php echo $this->formatoData($this->form->data_admissao->getValue()); ?>" class="form-control" placeholder="Data de Admissão" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask required />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-md-3">
                          <label>Salário</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              R$
                            </div>
                            <input type="text" name="salario" value="<?php echo $this->formatoDinheiro($this->form->salario->getValue()); ?>" class="form-control dinheiro" placeholder="Salário" required />
                          </div><!-- /.input group -->
                        </div>
                      </div>
                    </div><!-- /.box-body -->
                  </div><!-- /.box -->

                  <label>Login</label>
                  <div class="input-group margin-bottom col-md-5">
                    <div class="input-group-addon">
                      <i class="fa fa-user"></i>
                    </div>
                    <input type="text" name="login" value="<?php echo $this->form->login->getValue(); ?>" class="form-control" placeholder="Login" required />
                  </div><!-- /.input group -->
                  <label>Estacionamento</label>
                  <div class="input-group margin-bottom col-md-5">
                    <?php echo $this->form->id_estacionamento; ?>
                  </div><!-- /.input group -->
                  <div class="row">
                    <div class="col-md-12 margin-bottom">
                      <?php if ($this->funcionario['ativo'] == true) : ?>
                      <button type="submit" class="btn btn-primary">Alterar</button>
                      <button type="submit" class="btn btn-warning">Gerar Nova Senha</button>
                      <button type="button" class="btn btn-danger status">Inativar</button>
                      <?php else : ?>
                      <button type="button" class="btn btn-success status">Ativar</button>
                      <?php endif; ?>
                    </div><!-- /.col -->
                  </div>
                </form>
              </div>
            </div>
          </div><!-- /.box -->
        </div><!-- /.col -->
      </div>   <!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- InputMask -->
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.date.extensions.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.extensions.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.maskMoney.js"); ?>" ></script>

<script type="text/javascript">
$(function () {
  $("#datemask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
  $("[data-mask]").inputmask();
  $('.inteiro').maskMoney({thousands: '', decimal: ''});
  $('.dinheiro').maskMoney({thousands: '', decimal: ','});
  $('.status').click(function(e) {
    e.preventDefault();

    var acao = $(this).text();
    $('#status').val(acao);

    if (acao === 'Ativar') {
      $('.modal').addClass('modal-success');
      $('.modal').removeClass('modal-danger');
    } else {
      $('.modal').addClass('modal-danger');
      $('.modal').removeClass('modal-success');
    }

    $('.modal-body').html('<p>Você tem certeza que deseja <strong>' + acao + '</strong> o(a) Funcionário(a) ' + $('#nome').val() + '?</p>');
    var id = '.modal';

    var maskHeight = $(document).height();
    var maskWidth = $(window).width();

    $('#mask').css({'width':maskWidth,'height':maskHeight});

    $('#mask').fadeIn(1000);
    $('#mask').fadeTo("slow",0.8);

    var winH = $(window).height();
    var winW = $(window).width();

    $(id).css('top',  winH/2-$(id).height()/3);
    $(id).css('left', winW/2-$(id).width()/2);

    $(id).fadeIn(2000);
    return false;
  });

  $('#alterarStatus').click(function() {
    var id = parseInt($('#id').val());
    var status = $('#status').val() === 'Ativar' ? '1' : '0';
    $.ajax({
      type: "GET",
      url: '/funcionario/alterastatus/id/' + id + '/status/' + status,
        success: function(dados) {
          location.reload(true);
        }
    });
  });

  $('.window .close, .window .close2').click(function (e) {
    e.preventDefault();
    $('#mask').hide();
    $('.window').hide();
  });

  $('#mask').click(function () {
    $(this).hide();
    $('.window').hide();
  });
});
</script>