<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Funcionários
        <small>lista de funcionários</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="<?php echo $this->baseUrl("/"); ?>"><i class="fa fa-dashboard"></i> Início</a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'funcionario'), null, 1); ?>">Funcionários</a></li>
        <li class="active">lista</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box box-danger">
            <div class="box-header">
              <a href="<?php echo $this->url(array('controller' => 'funcionario', 'action' => 'new'), null, 1); ?>">
                <button type="button" class="btn btn-danger">Novo Funcionário</button>
              </a>
            </div><!-- /.box-header -->
            <div class="box-body">
              <table id="tabelaFuncionarios" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Nome</th>
                    <th>CPF</th>
                    <th>Estacionamento</th>
                    <th>Ações</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>Pedro</td>
                    <td>788.993.822-55</td>
                    <td>Estacionamento 1</td>
                    <td class="col-sm-2">
                      <a class="text-red" href=""><span class="label label-warning">Editar</span></a>
                      <a class="text-red" href=""><span class="label label-danger">Inativar</span></a>
                    </td>
                  </tr>
                  <tr>
                    <td>João</td>
                    <td>100.060.954-53</td>
                    <td>Estacionamento 1</td>
                    <td class="col-sm-2">
                      <a class="text-red" href=""><span class="label label-warning">Editar</span></a>
                      <a class="text-red" href=""><span class="label label-danger">Inativar</span></a>
                    </td>
                  </tr>
                  <tr>
                    <td>Maria</td>
                    <td>973.717.214-03</td>
                    <td>Estacionamento 2</td>
                    <td class="col-sm-2">
                      <a class="text-red" href=""><span class="label label-warning">Editar</span></a>
                      <a class="text-red" href=""><span class="label label-danger">Inativar</span></a>
                    </td>
                  </tr>
                  <tr>
                    <td>Antônio</td>
                    <td>863.738.515-08</td>
                    <td>Estacionamento 3</td>
                    <td class="col-sm-2">
                      <a class="text-red" href=""><span class="label label-warning">Editar</span></a>
                      <a class="text-red" href=""><span class="label label-danger">Inativar</span></a>
                    </td>
                  </tr>
                  <tr>
                    <td>José Paulo</td>
                    <td>844.614.208-25</td>
                    <td>Estacionamento 4</td>
                    <td class="col-sm-2">
                      <a class="text-red" href=""><span class="label label-warning">Editar</span></a>
                      <a class="text-red" href=""><span class="label label-danger">Inativar</span></a>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div><!-- /.box-body -->
          </div><!-- /.box -->
        </div><!-- /.col -->
      </div><!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->
<script type="text/javascript">
$(function () {
    $("#tabelaFuncionarios").dataTable();
});
</script>