<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Funcionários
        <small>novo funcionário</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="<?php echo $this->baseUrl("/"); ?>"><i class="fa fa-dashboard"></i> Início</a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'funcionario'), null, 1); ?>">Funcionários</a></li>
        <li class="active">novo</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="box box-danger">
            <div class="box-header">
              <h3 class="box-title">Novo Funcionário</h3>
            </div>
            <div class="box-body">
                <!-- form start -->
                <form action="" method="post">
                  <label>Nome</label>
                  <div class="input-group margin-bottom col-md-6">
                    <div class="input-group-addon">
                      <i class="fa fa-user"></i>
                    </div>
                    <input type="text" name="nome" class="form-control" placeholder="Nome" />
                  </div><!-- /.input group -->
                  <label>E-mail</label>
                  <div class="input-group margin-bottom col-md-6">
                    <div class="input-group-addon">
                      <i class="fa fa-envelope"></i>
                    </div>
                    <input type="text" name="email" class="form-control" placeholder="E-mail" />
                  </div><!-- /.input group -->
                  <label>Telefone</label>
                  <div class="input-group margin-bottom col-md-3">
                    <div class="input-group-addon">
                      <i class="fa fa-phone"></i>
                    </div>
                    <input type="text" name="telefone" class="form-control" placeholder="Telefone" data-inputmask='"mask": "(99) 9999-9999"' data-mask />
                  </div><!-- /.input group -->
                                    <div class="box">
                    <div class="box-header">
                      <h3 class="box-title">Dados do Documento</h3>
                    </div>
                    <div class="box-body">
                      <div class="row">
                        <div class="col-xs-3">
                          <label>CPF</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="cpf" class="form-control" placeholder="CPF" data-inputmask='"mask": "999.999.999-99"' data-mask />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-xs-3">
                          <label>RG</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="rg" class="form-control" placeholder="RG" />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-xs-4">
                          <label>Data de Nascimento</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" name="dataNascimento" class="form-control" placeholder="Data de Nascimento" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask />
                          </div><!-- /.input group -->
                        </div>
                      </div>
                    </div><!-- /.box-body -->
                  </div><!-- /.box -->
                  <div class="box">
                    <div class="box-header">
                      <h3 class="box-title">Dados de Funcionário</h3>
                    </div>
                    <div class="box-body">
                      <div class="row">
                        <div class="col-xs-3">
                          <label>Matrícula</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="matricula" class="form-control inteiro" placeholder="Matrícula" />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-xs-4">
                          <label>Data de Admissão</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" name="dataAdmissao" class="form-control" placeholder="Data de Admissão" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-xs-3">
                          <label>Salário</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              R$
                            </div>
                            <input type="text" name="salario" class="form-control dinheiro" placeholder="Salário" />
                          </div><!-- /.input group -->
                        </div>
                      </div>
                    </div><!-- /.box-body -->
                  </div><!-- /.box -->
                  <label>Login</label>
                  <div class="input-group margin-bottom col-md-5">
                    <div class="input-group-addon">
                      <i class="fa fa-user"></i>
                    </div>
                    <input type="text" name="login" class="form-control" placeholder="Login" />
                  </div><!-- /.input group -->
                  <label>Estacionamento</label>
                  <div class="input-group margin-bottom col-md-5">
                    <div class="input-group-addon">
                      <i class="fa fa-edit"></i>
                    </div>
                    <select name="estacionamento" class="form-control">
                      <option>-- Selecione o Estacionamento --</option>
                      <option >Estacionamento 1</option>
                      <option>Estacionamento 2</option>
                      <option>Estacionamento 3</option>
                      <option>Estacionamento 4</option>
                    </select>
                  </div><!-- /.input group -->
                  <div class="row">
                    <div class="col-xs-4 margin-bottom">
                      <button type="submit" class="btn btn-success">Cadastrar</button>
                    </div><!-- /.col -->
                  </div>
                </form>
            </div>
          </div><!-- /.box -->
        </div><!-- /.col -->
      </div>   <!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- InputMask -->
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.date.extensions.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.extensions.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.maskMoney.js"); ?>" ></script>

<script type="text/javascript">
$(function () {
  $("#datemask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
  $("[data-mask]").inputmask();
  $('.inteiro').maskMoney({thousands: '', decimal: ''});
  $('.dinheiro').maskMoney({thousands: '', decimal: ','});
});
</script>