<!DOCTYPE html>
<html>
  <head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>

    <link href="<?php echo $this->baseUrl("images/favicon.ico"); ?>" rel="shortcut icon" />
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <!-- Bootstrap 3.3.2 -->
    <link href="<?php echo $this->baseUrl("bootstrap/css/bootstrap.min.css"); ?>" rel="stylesheet" type="text/css" />
    <!-- FontAwesome 4.3.0 -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons 2.0.0 -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="<?php echo $this->baseUrl("dist/css/AdminLTE.min.css"); ?>" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link href="<?php echo $this->baseUrl("dist/css/skins/skin-red.min.css"); ?>" rel="stylesheet" type="text/css" />
    <!-- iCheck -->
    <link href="<?php echo $this->baseUrl("plugins/iCheck/all.css"); ?>" rel="stylesheet" type="text/css" />
    <!-- Morris chart -->
    <link href="<?php echo $this->baseUrl("plugins/morris/morris.css"); ?>" rel="stylesheet" type="text/css" />
    <!-- jvectormap -->
    <link href="<?php echo $this->baseUrl("plugins/jvectormap/jquery-jvectormap-1.2.2.css"); ?>" rel="stylesheet" type="text/css" />
    <!-- DATA TABLES -->
    <link href="<?php echo $this->baseUrl("plugins/datatables/dataTables.bootstrap.css"); ?>" rel="stylesheet" type="text/css" />
    <!-- Date Picker -->
    <link href="<?php echo $this->baseUrl("plugins/datepicker/datepicker3.css"); ?>" rel="stylesheet" type="text/css" />
    <!-- Daterange picker -->
    <link href="<?php echo $this->baseUrl("plugins/daterangepicker/daterangepicker-bs3.css"); ?>" rel="stylesheet" type="text/css" />
    <!-- bootstrap wysihtml5 - text editor -->
    <link href="<?php echo $this->baseUrl("plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css"); ?>" rel="stylesheet" type="text/css" />

    <script type="text/javascript">
        var BASEURL = "<?php echo $this->baseUrl("/"); ?>";
    </script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="skin-red">
    <div class="wrapper">
      <header class="main-header">
        <!-- Logo -->
        <a href="<?php echo $this->baseUrl("/admin"); ?>" class="logo"><b>NZN</b></a></a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
               <!-- Notifications: style can be found in dropdown.less -->
              <li class="dropdown notifications-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-bell-o"></i>
                  <span class="label label-warning">3</span>
                </a>
                <ul class="dropdown-menu">
                  <li class="header">Você tem 3 novas notificações</li>
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <ul class="menu">
                      <li>
                        <a href="#">
                          <i class="fa fa-warning text-yellow"></i> Seu saldo está baixo.
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-shopping-cart text-green"></i> Foi efetuado uma recarga de <b>R$ 25,00</b>.
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-user text-red"></i> Dados pessois atualizados.
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li class="footer"><a href="#">Ver todas</a></li>
                </ul>
              </li>
              <!-- User Account: style can be found in dropdown.less -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <img src="<?php echo $this->baseUrl("dist/img/avatar5.png"); ?>" class="user-image" alt="User Image"/>
                  <span class="hidden-xs">Alexander Pierce</span>
                </a>
                <ul class="dropdown-menu">
                  <!-- User image -->
                  <li class="user-header">
                    <img src="<?php echo $this->baseUrl("dist/img/avatar5.png"); ?>" class="img-circle" alt="User Image" />
                    <p>
                      Alexander Pierce
                      <small>Último acesso: 13/05/2015 18:50</small>
                    </p>
                  </li>
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-left">
                      <a href="#" class="btn btn-default btn-flat">Ver perfil</a>
                    </div>
                    <div class="pull-right">
                      <a href="#" class="btn btn-default btn-flat">Sair</a>
                    </div>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- sidebar menu: : style can be found in sidebar.less -->
          <ul class="sidebar-menu">
            <li class="header">Menu</li>

            <li class="active treeview">
              <a href="#">
                <i class="fa fa-dashboard"></i> <span>Página Inicial</span></i>
              </a>
            </li>

            <!-- Menu Master -->
            <li class="treeview">
              <a href="#">
                <i class="fa fa-edit"></i> <span>Estacionamentos</span>
              </a>
            </li>
            <li class="active treeview">
              <a href="<?php echo $this->url(array('controller' => 'funcionario'), null, 1); ?>">
                <i class="fa fa-edit"></i> <span>Funcionários</span>
              </a>
            </li>
            <!-- End Menu Master -->

            <!-- Menu Administrador -->
            <li class="treeview">
              <a href="#">
                <i class="fa fa-edit"></i> <span>Clientes</span>
              </a>
            </li>
            <li class="treeview">
              <a href="#">
                <i class="fa fa-laptop"></i> <span>Configurar Estacionamento</span>
              </a>
            </li>
            <!-- End Menu Administrador -->

            <!-- Menu Cliente
            <li class="treeview">
              <a href="#">
                <i class="fa fa-user"></i> <span>Minha Conta</span>
              </a>
            </li>
            <li class="treeview">
              <a href="#">
                <i class="fa fa-dashboard"></i> <span>Meus Veículos</span>
              </a>
            </li>
            <li class="treeview">
              <a href="#">
                <i class="fa fa-shopping-cart"></i> <span>Comprar Crédito</span>
              </a>
            </li>
            <li class="treeview">
              <a href="#">
                <i class="fa fa-table"></i> <span>Minhas Movimentações</span>
              </a>
            </li>
            <!-- End Menu Cliente -->

            <!-- Relatórios -->
            <li class="treeview">
              <a href="#">
                <i class="fa fa-dashboard"></i> <span>Relatórios</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li><a href=""><i class="fa fa-table"></i> Movimentações Estacionamento</a></li>
                <li><a href=""><i class="fa fa-table"></i> Receita</a></li>
                <li><a href=""><i class="fa fa-table"></i> Movimentações Cliente</a></li>
              </ul>
            </li>
            <!-- End Relatórios -->
          </ul>
        </section>
        <!-- /.sidebar -->
      </aside>

      <?php echo $this->Layout()->content; ?>

      <footer class="main-footer text-center" style="margin-left: 0;">
        <strong>Copyright &copy; 2015 <a class="text-red" href="http://nznestacionamentos.esy.es">NZN Estacionamentos</a>.</strong> All rights reserved. | Desenvolvido por <a class="text-red" href="http://rrca.esy.es/">RRCA</a> - Rodrigo Ribeiro
      </footer>
    </div><!-- ./wrapper -->

    <!-- jQuery 2.1.3 -->
    <script src="<?php echo $this->baseUrl("plugins/jQuery/jQuery-2.1.3.min.js"); ?>" ></script>
    <!-- jQuery UI 1.11.2 -->
    <script src="http://code.jquery.com/ui/1.11.2/jquery-ui.min.js" type="text/javascript"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="<?php echo $this->baseUrl("bootstrap/js/bootstrap.min.js"); ?>" type="text/javascript"></script>
    <!-- Morris.js charts -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js" ></script>
    <script src="<?php echo $this->baseUrl("plugins/morris/morris.min.js"); ?>" type="text/javascript"></script>
    <!-- Sparkline -->
    <script src="<?php echo $this->baseUrl("plugins/sparkline/jquery.sparkline.min.js"); ?>" type="text/javascript"></script>
    <!-- jvectormap -->
    <script src="<?php echo $this->baseUrl("plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl("plugins/jvectormap/jquery-jvectormap-world-mill-en.js"); ?>" type="text/javascript"></script>
    <!-- jQuery Knob Chart -->
    <script src="<?php echo $this->baseUrl("plugins/knob/jquery.knob.js"); ?>" type="text/javascript"></script>
    <!-- DATA TABES SCRIPT -->
    <script src="<?php echo $this->baseUrl("plugins/datatables/jquery.dataTables.js"); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl("plugins/datatables/dataTables.bootstrap.js"); ?>" type="text/javascript"></script>
    <!-- daterangepicker -->
    <script src="<?php echo $this->baseUrl("plugins/daterangepicker/daterangepicker.js"); ?>" type="text/javascript"></script>
    <!-- datepicker -->
    <script src="<?php echo $this->baseUrl("plugins/datepicker/bootstrap-datepicker.js"); ?>" type="text/javascript"></script>
    <!-- InputMask -->
    <script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.js"); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.date.extensions.js"); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.extensions.js"); ?>" type="text/javascript"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="<?php echo $this->baseUrl("plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"); ?>" type="text/javascript"></script>
    <!-- iCheck -->
    <script src="<?php echo $this->baseUrl("plugins/iCheck/icheck.min.js"); ?>" type="text/javascript"></script>
    <!-- Slimscroll -->
    <script src="<?php echo $this->baseUrl("plugins/slimScroll/jquery.slimscroll.min.js"); ?>" type="text/javascript"></script>
    <!-- FastClick -->
    <script src="<?php echo $this->baseUrl("plugins/fastclick/fastclick.min.js"); ?>" ></script>
    <script type="text/javascript">
      $(function () {
        $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
          checkboxClass: 'icheckbox_minimal-red',
          radioClass: 'iradio_minimal-red'
        });
        $("[data-mask]").inputmask();
      });
    </script>
  </body>
</html>