<!DOCTYPE HTML>
<html>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>

        <link href="<?php echo $this->baseUrl("images/favicon.ico"); ?>" rel="shortcut icon" />
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="<?php echo $this->baseUrl("css/bootstrap.css"); ?>" rel="stylesheet" type="text/css" media="all">
        <link href="<?php echo $this->baseUrl("css/style.css"); ?>" rel="stylesheet" type="text/css" media="all" />
        <link href="<?php echo $this->baseUrl("css/flexslider.css"); ?>" rel="stylesheet" type="text/css" media="screen" />

        <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
        <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900' rel='stylesheet' type='text/css'>

        <script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.min.js"); ?>"></script>
        <script type="text/javascript">
            var BASEURL = "<?php echo $this->baseUrl("/"); ?>";
        </script>
    </head>
    <body>
        <div class="banner">
            <div class="banner-top">
                <div class="logo">
                    <a href="<?php echo $this->baseUrl("/"); ?>">
                        <img src="<?php echo $this->baseUrl("images/logo.png"); ?>" class="img-responsive" alt="" />
                    </a>
                </div>
                <!--
                <div class="social">
                    <ul>
                        <li><a href="#"><i class="star"></i></a></li>
                        <li><a href="#"><i class="cam"></i></a></li>
                        <li><a href="#"><i class="vid"></i></a></li>
                        <li><a href="#"><i class="fb"></i></a></li>
                        <li><a href="#"><i class="twt"></i></a></li>
                        <li><a href="#"><i class="pp"></i></a></li>
                    </ul>
                </div>
                -->
                <div class="banner-info">
                    <h1>Criamos espaço para as pessoas</h1>
                    <p></p>
                    <a href="#" class="more">Magnaset</a>
                </div>
            </div>
        </div>
        <div class="banner-bottom">
            <div class="container">
                <div class="logo1">
                    <a href="<?php echo $this->baseUrl("/"); ?>">
                        <img src="<?php echo $this->baseUrl("images/logo1.png"); ?>" class="img-responsive" alt="" />
                    </a>
                </div>
                <div class="head-nav">
                    <span class="menu"> </span>
                        <ul class="cl-effect-15">
                            <li class="active"><a href="<?php echo $this->baseUrl("/"); ?>">Página Inicial</a></li>
                            <li><a href="" data-hover="Sobre">Sobre</a></li>
                            <li><a href="" data-hover="Contato">Contato</a></li>
                            <li><a href="<?php echo $this->baseUrl("/admin"); ?>" data-hover="Login">Login</a></li>
                            <div class="clearfix"> </div>
                        </ul>
                </div>
                <div class="clearfix"> </div>
                <!-- script-for-nav -->
                <script>
                        $( "span.menu" ).click(function() {
                          $( ".head-nav ul" ).slideToggle(300, function() {
                                // Animation complete.
                          });
                        });
                </script>
                <!-- script-for-nav -->
            </div>
        </div>

        <?php echo $this->Layout()->content; ?>

        <!-- cullam -->
        <div class="cullam">
            <div class="container">
                <div class="col-md-4 cullam-top">
                    <img src="<?php echo $this->baseUrl("images/img1.jpg"); ?>" class="img-responsive" alt="" />
                    <div class="cula">
                        <h5>Cullam varius faucib lacus </h5>
                        <h6>vitae elem entum facillis nulls sime </h6>
                        <p>Pellentesque fermentum interdum ipsum, ut gravida justo sollicitudin quis  ipsum cursus lobortis in vitae ipsum.</p>
                    </div>
                </div>
                <div class="col-md-4 cullam-top">
                    <h5>Lorem ipsum dolor sit amet</h5>
                    <h6>vitae elem entum facillis nulls sime</h6>
                    <div class="col-md-6 cullam-left">
                        <ul>
                            <li><a href="#"><span> </span>Aenean eu diam</a></li>
                            <li><a href="#"><span> </span>Curabitur grav</a></li>
                            <li><a href="#"><span> </span>Sed sed dolor </a></li>
                            <li><a href="#"><span> </span>Vestibulum eget</a></li>
                            <li><a href="#"><span> </span>In at nisi non</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 cullam-left">
                        <ul>
                            <li><a href="#"><span> </span>Donec at metus</a></li>
                            <li><a href="#"><span> </span>Fusce quis mi</a></li>
                            <li><a href="#"><span> </span>Phasellus tem</a></li>
                            <li><a href="#"><span> </span>Nullam sit amet</a></li>
                            <li><a href="#"><span> </span>Integer et met</a></li>
                        </ul>
                    </div>
                    <div class="clearfix"> </div>
                </div>
                <div class="col-md-4 cullam-top">
                    <img src="<?php echo $this->baseUrl("images/img2.jpg"); ?>" class="img-responsive" alt="" />
                    <div class="cula">
                        <h5>Jonullam varius faucib lacus </h5>
                        <h6>vitae elem entum facillis nulls sime  </h6>
                        <p>Pellentesque fermentum interdum ipsum, ut gravida justo sollicitudin quis  ipsum cursus lobortis in vitae ipsum.</p>
                    </div>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
        <!-- cullam -->
        <!-- venenatis -->
        <div class="venenatis">
            <div class="container">
                <h3>In venenatis arcu vehicula quam laocondimentum sapien faucibus leo tristique pharetra suprino</h3>
                <h4>Aliquam volutpat suscipit ante vel porta sed at ultrices antesuspendisse lobortis sapien vitae augue</h4>
                <ul id="flexiselDemo3">
                    <li>
                        <div class="team1">
                            <img src="<?php echo $this->baseUrl("images/img3.jpg"); ?>" class="img-responsive" alt="" />
                        </div>
                    </li>
                    <li>
                        <div class="team1">
                            <img src="<?php echo $this->baseUrl("images/img4.jpg"); ?>" class="img-responsive" alt="" />
                        </div>
                    </li>
                    <li>
                        <div class="team1">
                            <img src="<?php echo $this->baseUrl("images/img5.jpg"); ?>" class="img-responsive" alt="" />
                        </div>
                    </li>
                    <li>
                        <div class="team1">
                            <img src="<?php echo $this->baseUrl("images/img8.jpg"); ?>" class="img-responsive" alt="" />
                        </div>
                    </li>
                    <li>
                        <div class="team1">
                            <img src="<?php echo $this->baseUrl("images/img6.jpg"); ?>" class="img-responsive" alt="" />
                        </div>
                    </li>
                    <li>
                        <div class="team1">
                        <img src="<?php echo $this->baseUrl("images/img5.jpg"); ?>" class="img-responsive" alt="" />
                        </div>
                    </li>
                </ul>
                <script type="text/javascript">
                $(window).load(function() {
                    $("#flexiselDemo3").flexisel({
                        visibleItems: 6,
                        animationSpeed: 1000,
                        autoPlay: true,
                        autoPlaySpeed: 3000,
                        pauseOnHover: true,
                        enableResponsiveBreakpoints: true,
                        responsiveBreakpoints: {
                            portrait: {
                                changePoint:480,
                                visibleItems: 1
                            },
                            landscape: {
                                changePoint:640,
                                visibleItems: 2
                            },
                            tablet: {
                                changePoint:768,
                                visibleItems: 3
                            }
                        }
                    });
                });
                </script>
                <script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.flexisel.js"); ?>"></script>
            </div>
        </div>
        <!-- venenatis -->
        <!-- footer -->
        <div class="footer">
            <div class="container">
                <p>Copyrights © 2015 NZN Estacionamentos All rights reserved | Desenvolvido por <a href="http://rrca.esy.es/" target="_blank">RRCA</a></p>
            </div>
        </div>
        <!-- footer -->
    </body>
</html>