<!DOCTYPE html>
<html>
  <head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>

    <link href="<?php echo $this->baseUrl("images/favicon.ico"); ?>" rel="shortcut icon" />
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.2 -->
    <link href="<?php echo $this->baseUrl("bootstrap/css/bootstrap.min.css"); ?>" rel="stylesheet" type="text/css" />
    <!-- FontAwesome 4.3.0 -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons 2.0.0 -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="<?php echo $this->baseUrl("dist/css/AdminLTE.min.css"); ?>" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link href="<?php echo $this->baseUrl("dist/css/skins/skin-red.min.css"); ?>" rel="stylesheet" type="text/css" />

    <!-- jQuery 2.1.3 -->
    <script src="<?php echo $this->baseUrl("plugins/jQuery/jQuery-2.1.3.min.js"); ?>" ></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="<?php echo $this->baseUrl("bootstrap/js/bootstrap.min.js"); ?>" type="text/javascript"></script>
    <!-- Slimscroll -->
    <script src="<?php echo $this->baseUrl("plugins/slimScroll/jquery.slimscroll.min.js"); ?>" type="text/javascript"></script>
    <!-- FastClick -->
    <script src="<?php echo $this->baseUrl("plugins/fastclick/fastclick.min.js"); ?>" ></script>
    <!-- AdminLTE App -->
    <script src="<?php echo $this->baseUrl("dist/js/app.min.js"); ?>" type="text/javascript"></script>

    <script type="text/javascript">
        var BASEURL = "<?php echo $this->baseUrl("/"); ?>";
    </script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="skin-red">
    <div class="wrapper">
      <header class="main-header">
        <!-- Logo -->
        <a href="<?php echo $this->url(array('controller' => 'index', 'action' => $this->usarioLogado->perfil), null, 1); ?>" class="logo"><b>NZN</b></a></a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
               <!-- Notifications: style can be found in dropdown.less -->
              <li class="dropdown notifications-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-bell-o"></i>
                  <span class="label label-warning">3</span>
                </a>
                <ul class="dropdown-menu">
                  <li class="header">Você tem 3 novas notificações</li>
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <ul class="menu">
                      <li>
                        <a href="#">
                          <i class="fa fa-warning text-yellow"></i> Seu saldo está baixo.
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-shopping-cart text-green"></i> Foi efetuado uma recarga de <b>R$ 25,00</b>.
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-user text-red"></i> Dados pessois atualizados.
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li class="footer"><a href="#">Ver todas notificações</a></li>
                </ul>
              </li>
              <!-- User Account: style can be found in dropdown.less -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <img src="<?php echo $this->baseUrl("dist/img/avatar5.png"); ?>" class="user-image" alt="User Image"/>
                  <span class="hidden-xs"><?php echo $this->usarioLogado->login; ?></span>
                </a>
                <ul class="dropdown-menu">
                  <!-- User image -->
                  <li class="user-header">
                    <img src="<?php echo $this->baseUrl("dist/img/avatar5.png"); ?>" class="img-circle" alt="User Image" />
                    <p>
                      <?php echo $this->usarioLogado->login; ?>
                      <?php if (isset($this->usarioLogado->ultimo_acesso)) : ?>
                      <small>Último acesso: <?php echo date('H:i:s d/m/Y', strtotime($this->usarioLogado->ultimo_acesso)); ?></small>
                      <?php else: ?>
                      <small>Primeiro Acesso</small>
                      <?php endif; ?>
                    </p>
                  </li>
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <?php if ($this->usarioLogado->perfil == 'cliente') : ?>
                    <div class="pull-left">
                      <a href="<?php echo $this->url(array('controller' => $this->usarioLogado->perfil, 'action' => 'edit'), null, 1); ?>" class="btn btn-default btn-flat">Ver perfil</a>
                    </div>
                    <?php endif; ?>
                    <div class="pull-right">
                      <a href="<?php echo $this->url(array('controller' => 'login', 'action' => 'logout'), null, 1); ?>" class="btn btn-default btn-flat">Sair</a>
                    </div>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- sidebar menu: : style can be found in sidebar.less -->
          <ul class="sidebar-menu">
            <li class="header">Menu</li>

            <li class="active treeview">
              <a href="<?php echo $this->url(array('controller' => 'index', 'action' => $this->usarioLogado->perfil), null, 1); ?>">
                <i class="fa fa-dashboard"></i> <span>Página Inicial</span></i>
              </a>
            </li>
            <?php
              $controler = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
              $action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
            ?>
            <?php if ($this->usarioLogado->perfil == 'master') : ?>
            <!-- Menu Master -->
            <li class="<?php if ($controler == 'estacionamento' && ($action == 'index' || $action == 'new' || $action == 'edit')) echo "active"; ?> treeview">
              <a href="<?php echo $this->url(array('controller' => 'estacionamento'), null, 1); ?>">
                <i class="fa fa-edit"></i> <span>Estacionamentos</span>
              </a>
            </li>
            <li class="<?php if ($controler == 'funcionario' && ($action == 'index' || $action == 'new' || $action == 'edit')) echo "active"; ?> treeview">
              <a href="<?php echo $this->url(array('controller' => 'funcionario'), null, 1); ?>">
                <i class="fa fa-edit"></i> <span>Funcionários</span>
              </a>
            </li>
            <!-- End Menu Master -->
            <?php endif; ?>

            <?php if ($this->usarioLogado->perfil == 'master' || $this->usarioLogado->perfil == 'funcionario') : ?>
            <!-- Menu Funcionario -->
            <li class="<?php if ($controler == 'cliente' && ($action == 'index' || $action == 'new' || $action == 'edit')) echo "active"; ?> treeview">
              <a href="<?php echo $this->url(array('controller' => 'cliente'), null, 1); ?>">
                <i class="fa fa-edit"></i> <span>Clientes</span>
              </a>
            </li>
            <li class="<?php if ($controler == 'estacionamento' && $action == 'configurar') echo "active"; ?> treeview">
              <a href="<?php echo $this->url(array('controller' => 'estacionamento', 'action' => 'configurar'), null, 1); ?>">
                <i class="fa fa-laptop"></i> <span>Configurar Estacionamento</span>
              </a>
            </li>
            <li class="<?php if ($controler == 'cliente' && $action == 'colocarcredito') echo "active"; ?> treeview">
              <a href="<?php echo $this->url(array('controller' => 'cliente', 'action' => 'colocarcredito'), null, 1); ?>">
                <i class="fa fa-shopping-cart"></i> <span>Colocar Crédito Cliente</span>
              </a>
            </li>
            <!-- End Menu Funcionario -->

            <!-- Relatórios -->
            <li class="<?php if ($controler == 'relatorio') echo "active"; ?> treeview">
              <a href="<?php echo $this->url(array('controller' => 'relatorio', 'action' => 'movimentacaocliente'), null, 1); ?>">
                <i class="fa fa-dashboard"></i> <span>Relatórios</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li class="<?php if ($controler == 'relatorio' && $action == 'movimentacaoestacionamento') echo "active"; ?>"><a href="<?php echo $this->url(array('controller' => 'relatorio', 'action' => 'movimentacaoestacionamento'), null, 1); ?>"><i class="fa fa-table"></i> Movimentações Estacionamento</a></li>
                <?php if ($this->usarioLogado->perfil == 'master') : ?>
                <li class="<?php if ($controler == 'relatorio' && $action == 'receita') echo "active"; ?>"><a href="<?php echo $this->url(array('controller' => 'relatorio', 'action' => 'receita'), null, 1); ?>"><i class="fa fa-table"></i> Receita</a></li>
                <?php endif; ?>
                <li class="<?php if ($controler == 'relatorio' && $action == 'movimentacaoclienteadministrador') echo "active"; ?>"><a href="<?php echo $this->url(array('controller' => 'relatorio', 'action' => 'movimentacaoclienteadministrador'), null, 1); ?>"><i class="fa fa-table"></i> Movimentações Cliente</a></li>
              </ul>
            </li>
            <!-- End Relatórios -->
            <?php endif; ?>

            <?php if ($this->usarioLogado->perfil == 'cliente') : ?>
            <!-- Menu Cliente -->
            <li class="<?php if ($controler == 'cliente' && $action == 'edit') echo "active"; ?> treeview">
              <a href="<?php echo $this->url(array('controller' => 'cliente', 'action' => 'edit'), null, 1); ?>">
                <i class="fa fa-user"></i> <span>Minha Conta</span>
              </a>
            </li>
            <li class="<?php if ($controler == 'veiculo' && $action == 'index') echo "active"; ?> treeview">
              <a href="<?php echo $this->url(array('controller' => 'veiculo'), null, 1); ?>">
                <i class="fa fa-dashboard"></i> <span>Meus Veículos</span>
              </a>
            </li>
            <li class="<?php if ($controler == 'cliente' && $action == 'comprarcredito') echo "active"; ?> treeview">
              <a href="<?php echo $this->url(array('controller' => 'cliente', 'action' => 'comprarcredito'), null, 1); ?>">
                <i class="fa fa-shopping-cart"></i> <span>Comprar Crédito</span>
              </a>
            </li>
            <li class="<?php if ($controler == 'estacionamento' && $action == 'consultarvagas') echo "active"; ?> treeview">
              <a href="<?php echo $this->url(array('controller' => 'estacionamento', 'action' => 'consultarvagas'), null, 1); ?>">
                <i class="fa fa-dashboard"></i> <span>Consultar Vagas Disponíveis</span>
              </a>
            </li>
            <li class="<?php if ($controler == 'relatorio' && $action == 'movimentacaocliente') echo "active"; ?> treeview">
              <a href="<?php echo $this->url(array('controller' => 'relatorio', 'action' => 'movimentacaocliente'), null, 1); ?>">
                <i class="fa fa-table"></i> <span>Minhas Movimentações</span>
              </a>
            </li>
            <!-- End Menu Cliente -->
            <?php endif; ?>
          </ul>
        </section>
        <!-- /.sidebar -->
      </aside>

      <?php echo $this->Layout()->content; ?>

      <footer class="main-footer">
        <strong>Copyright &copy; 2015 <a class="text-red" href="http://nznestacionamentos.esy.es">NZN Estacionamentos</a>. All rights reserved.</strong> | Desenvolvido por <a class="text-red" target="_blank" href="http://rrca.esy.es/">RRCA</a>
      </footer>
    </div><!-- ./wrapper -->
  </body>
</html>