  <div class="login-box-body">
    <?php if($this->error): ?>
    <div class='notification'>
        <p class="login-box-msg"><?php echo $this->error; ?></p>
    </div>
    <?php endif; ?>

    <h4>Faça login no NZN Estacionamentos</h4>
    <form action="" method="post">
      <div class="input-group margin-bottom">
        <div class="input-group-addon">
          <i class="fa fa-user"></i>
        </div>
        <input type="text" name="login" class="form-control" placeholder="Login" />
      </div><!-- /.input group -->
      <div class="input-group margin-bottom">
       <div class="input-group-addon">
         <i class="fa fa-lock"></i>
       </div>
       <input type="password" name="senha" class="form-control" placeholder="Senha" />
     </div><!-- /.input group -->
      <div class="row">
        <div class="col-xs-4 margin-bottom">
          <button type="submit" class="btn btn-danger">Entrar</button>
        </div><!-- /.col -->
      </div>
    </form>
    <a href="#" class="text-red">Esqueci minha senha</a><br/>
    <a href="<?php echo $this->baseUrl("/signup"); ?>" class="text-red">Criar uma conta</a>
  </div><!-- /.login-box-body -->