  <div class="login-box-body">
    <?php if($this->error): ?>
    <div class='notification'>
        <p class="login-box-msg"><?php echo $this->error; ?></p>
    </div>
    <?php endif; ?>

    <form action="" method="post">
        <div class="input-group margin-bottom">
          <div class="input-group-addon">
            <i class="fa fa-user"></i>
          </div>
          <input type="text" class="form-control" placeholder="Nome" />
        </div><!-- /.input group -->
        <div class="input-group margin-bottom">
          <div class="input-group-addon">
            <i class="fa fa-envelope"></i>
          </div>
          <input type="text" class="form-control" placeholder="E-mail" />
        </div><!-- /.input group -->
        <div class="input-group margin-bottom">
          <div class="input-group-addon">
            <i class="fa fa-phone"></i>
          </div>
          <input type="text" class="form-control" placeholder="Telefone" data-inputmask='"mask": "(99) 999-9999"' data-mask />
        </div><!-- /.input group -->
        <div class="input-group margin-bottom">
          <div class="input-group-addon">
            <i class="fa fa-edit"></i>
          </div>
          <input type="text" class="form-control" placeholder="CPF" data-inputmask='"mask": "999.999.999-99"' data-mask />
        </div><!-- /.input group -->
        <div class="input-group margin-bottom">
          <div class="input-group-addon">
            <i class="fa fa-edit"></i>
          </div>
          <input type="text" class="form-control" placeholder="RG" />
        </div><!-- /.input group -->
        <div class="input-group margin-bottom">
          <div class="input-group-addon">
            <i class="fa fa-user"></i>
          </div>
          <input type="text" class="form-control" placeholder="Usuario" />
        </div><!-- /.input group -->
        <div class="input-group margin-bottom">
          <div class="input-group-addon">
            <i class="fa fa-lock"></i>
          </div>
          <input type="password" class="form-control" placeholder="Senha" />
        </div><!-- /.input group -->
        <div class="input-group margin-bottom">
          <div class="input-group-addon">
            <i class="fa fa-lock"></i>
          </div>
          <input type="password" class="form-control" placeholder="Confirmar Senha" />
        </div><!-- /.input group -->
      <div class="row">
        <div class="col-xs-12">    
          <div class="checkbox icheck">
            <label>
              <input type="checkbox" class="minimal-red"/> Eu li e concordo com os <a href="#">termos de uso</a>
            </label>
          </div>                        
        </div><!-- /.col -->
        <div class="col-xs-4">
          <?php echo $this->form->submit; ?>
        </div><!-- /.col -->
      </div>
    </form>
  </div><!-- /.login-box-body -->