  <div class="login-box-body">
    <?php if($this->error): ?>
    <div class='notification'>
        <p class="login-box-msg"><?php echo $this->error; ?></p>
    </div>
    <?php endif; ?>

    <h4>Crie sua Conta no NZN Estacionamentos:</h4>
    <form action="" method="post">
        <label>
          <input id="pessoaFisica" type="radio" name="tipoPessoa" value="pessoaFisica" class="minimal-red" checked /> Pessoa Física
          <input id="pessoaJuridica" type="radio" name="tipoPessoa" value="pessoaJuridica" class="minimal-red" /> Pessoa Jurídica
        </label>
        <div class="input-group margin-bottom">
          <div class="input-group-addon">
            <i class="fa fa-user"></i>
          </div>
          <input type="text" name="nome" class="form-control" placeholder="Nome" />
        </div><!-- /.input group -->
        <div class="input-group margin-bottom">
          <div class="input-group-addon">
            <i class="fa fa-envelope"></i>
          </div>
          <input type="text" name="email" class="form-control" placeholder="E-mail" />
        </div><!-- /.input group -->
        <div class="input-group margin-bottom">
          <div class="input-group-addon">
            <i class="fa fa-phone"></i>
          </div>
          <input type="text" name="telefone" class="form-control" placeholder="Telefone" data-inputmask='"mask": "(99) 999-9999"' data-mask />
        </div><!-- /.input group -->
        <div id="cpf" class="input-group margin-bottom">
          <div class="input-group-addon">
            <i class="fa fa-edit"></i>
          </div>
          <input type="text" name="cpf" class="form-control" placeholder="CPF" data-inputmask='"mask": "999.999.999-99"' data-mask />
        </div><!-- /.input group -->
        <div id="rg" class="input-group margin-bottom">
          <div class="input-group-addon">
            <i class="fa fa-edit"></i>
          </div>
          <input type="text" name="rg" class="form-control" placeholder="RG" />
        </div><!-- /.input group -->
        <div id="dataNascimento" class="input-group margin-bottom">
          <div class="input-group-addon">
            <i class="fa fa-calendar"></i>
          </div>
          <input type="text" name="dataNascimento" class="form-control" placeholder="Data de Nascimento" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask />
        </div><!-- /.input group -->
        <div id="cnpj" class="input-group margin-bottom">
          <div class="input-group-addon">
            <i class="fa fa-edit"></i>
          </div>
          <input type="text" name="cnpj" class="form-control" placeholder="CNPJ" data-inputmask='"mask": "99.999.999/9999-99"' data-mask />
        </div><!-- /.input group -->
        <div id="dataFundacao" class="input-group margin-bottom">
          <div class="input-group-addon">
            <i class="fa fa-calendar"></i>
          </div>
          <input type="text" name="dataFundacao" class="form-control" placeholder="Data de Fundação" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask />
        </div><!-- /.input group -->
        <div class="input-group margin-bottom">
          <div class="input-group-addon">
            <i class="fa fa-user"></i>
          </div>
          <input type="text" name="login" class="form-control" placeholder="Usuario" />
        </div><!-- /.input group -->
        <div class="input-group margin-bottom">
          <div class="input-group-addon">
            <i class="fa fa-lock"></i>
          </div>
          <input type="password" name="senha" class="form-control" placeholder="Senha" />
        </div><!-- /.input group -->
        <div class="input-group margin-bottom">
          <div class="input-group-addon">
            <i class="fa fa-lock"></i>
          </div>
          <input type="password" name="confirmarSenha" class="form-control" placeholder="Confirmar Senha" />
        </div><!-- /.input group -->
      <div class="row">
        <div class="col-xs-12">    
          <div class="checkbox icheck">
            <label>
              <input type="checkbox" name="termoUso" class="minimal-red"/> Eu li e concordo com os <a href="#" class="text-red">termos de uso</a>.
            </label>
          </div>
        </div><!-- /.col -->
        <div class="col-xs-4 margin-bottom">
          <button type="submit" class="btn btn-danger">Registrar</button>
        </div><!-- /.col -->
      </div>
    </form>
    <a href="<?php echo $this->baseUrl("/login"); ?>" class="text-red">Já possuo conta</a>
  </div><!-- /.login-box-body -->