<!-- daterange picker -->
<link href="<?php echo $this->baseUrl("plugins/daterangepicker/daterangepicker-bs3.css"); ?>" rel="stylesheet" type="text/css" />
<!-- DATA TABLES -->
<link href="<?php echo $this->baseUrl("plugins/datatables/dataTables.bootstrap.css"); ?>" rel="stylesheet" type="text/css" />

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Relatório
        <small>minhas movimentações</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="<?php echo $this->baseUrl("/"); ?>"><i class="fa fa-dashboard"></i> Início</a></li>
        <li class="active"><a href="">minhas movimentações</a></li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

           <div class="row">
            <div class="col-xs-12">
              <div class="box box-danger">

                  <div class="box-header">
                  <h3 class="box-title">Calendário</h3>
                </div>
                <div class="box-body">
                  <!-- Date range -->
                  <div class="form-group">
                    <label>Selecione o Período:</label>
                    <div class="input-group" style="width: 655px;">
                      <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                      </div>
                      <input type="text" class="form-control pull-right" id="reservation" />
                    </div><!-- /.input group -->
                  </div><!-- /.form group -->

                  <!-- Date and time range -->

                </div><!-- /.box-body -->

                <div class="box-header">
                  <h3 class="box-title">Relatório de Movimentação</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="relatoriocliente" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th>Entrada</th>
                        <th>Saída</th>
                        <th>Placa</th>
                        <th>Valor</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>10/02 - 07:45</td>
                        <td>10/02 - 12:07</td>
                        <td>MXX-1111</td>
                        <td>3,00</td>
                      </tr>
                      <tr>
                        <td>10/02 - 13:25</td>
                        <td>10/02 - 18:10</td>
                        <td>MXX-1111</td>
                        <td>3,00</td>
                      </tr>
                      <tr>
                        <td>11/02 - 07:38</td>
                        <td>11/02 - 12:10</td>
                        <td>MXX-1111</td>
                        <td>3,00</td>
                      </tr>
                      <tr>
                        <td>11/02 - 13:23</td>
                        <td>12/02 - 6:20</td>
                        <td>MXX-1111</td>
                        <td>9,00</td>
                      </tr>
                      <tr>
                        <td>13/02 - 07:54</td>
                        <td>13/02 - 12:18</td>
                        <td>MXK-9999</td>
                        <td>3,00</td>
                      </tr>
                      <tr>
                        <td>13/02 - 12:46</td>
                        <td>13/02 - 17:57</td>
                        <td>MXK-9999</td>
                        <td>3,00</td>

                      </tr>
                    </tbody>
                    <tfoot>
                      <tr>
                        <th>Entrada</th>
                        <th>Saída</th>
                        <th>Placa</th>
                        <th>Valor</th>
                      </tr>
                    </tfoot>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->


          <div class="col-xs-6">
              <div class="table-responsive">
                <table class="table">
                  <tr>
                    <th style="width:50%">Tempo Total:</th>
                    <td>23h 45m</td>
                  </tr>
                  <tr>
                    <th>Gasto Total:</th>
                    <td>R$24.00</td>
                  </tr>
                </table>
              </div>
            </div><!-- /.col -->
             </div><!-- /.row -->
           <!-- this row will not appear when printing -->
          <div class="row no-print">
            <div class="col-xs-12">
              <a href="invoice-print.html" target="_blank" class="btn btn-default"><i class="fa fa-print"></i> Imprimir</a>
              <button class="btn btn-primary pull-right" style="margin-right: 5px;"><i class="fa fa-download"></i> Gerar PDF</button>
            </div>
          </div>

        </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- DATA TABES SCRIPT -->
<script src="<?php echo $this->baseUrl("plugins/datatables/jquery.dataTables.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/datatables/dataTables.bootstrap.js"); ?>" type="text/javascript"></script>
<!-- date-range-picker -->
<script src="<?php echo $this->baseUrl("plugins/daterangepicker/daterangepicker.js"); ?>" type="text/javascript"></script>

<script type="text/javascript">
$(function () {
    $("#relatoriocliente").dataTable();
    $('#reservation').daterangepicker();
});
</script>