<!-- DATA TABLES -->
<link href="<?php echo $this->baseUrl("plugins/datatables/dataTables.bootstrap.css"); ?>" rel="stylesheet" type="text/css" />

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Relatório
        <small>movimentações cliente</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => $this->usarioLogado->perfil), null, 1); ?>"><i class="fa fa-dashboard"></i> Início</a></li>
        <li>Relatório</li>
        <li class="active" >movimentações cliente</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="box box-danger">
            <div class="box-body">
              <table id="tabelaMovimentacoes" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Estacionamento</th>
                    <th>Placa</th>
                    <th>Cliente</th>
                    <th>Entrada / Saida</th>
                    <th>Data e Hora</th>
                    <th>Valor</th>
                  </tr>
                </thead>
                <tbody>
                  <?php foreach($this->movimentacoes as $movimentacao): ?>
                  <tr>
                    <td><?php echo $movimentacao['estacionamento']; ?></td>
                    <td><?php echo $movimentacao['placa']; ?></td>
                    <td><?php echo $movimentacao['nome']; ?></td>
                    <td><span class="label <?php echo ($movimentacao['status'] == 'Entrada') ? "label-success" : "label-danger"; ?>"><?php echo $movimentacao['status']; ?></span></td>
                    <td><?php echo (!empty($movimentacao['saida'])) ? $this->formatoData($movimentacao['saida'],true) : $this->formatoData($movimentacao['entrada'],true); ?></td>
                    <td><span class="text-red"><?php echo (!empty($movimentacao['valor'])) ? "R$ ".$this->formatoDinheiro($movimentacao['valor']) : ''; ?></span></td>
                  </tr>
                  <?php endforeach; ?>
                </tbody>
              </table>
              <div class="row no-print">
                <div class="col-xs-12">
                  <button class="btn btn-default pull-left" style="margin-right: 5px;" onclick="window.print();" ><i class="fa fa-print"></i> Imprimir</button>
                </div>
              </div>
            </div><!-- /.box-body -->
          </div><!-- /.box -->
        </div><!-- /.col -->
      </div><!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- DATA TABES SCRIPT -->
<script src="<?php echo $this->baseUrl("plugins/datatables/jquery.dataTables.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/datatables/dataTables.bootstrap.js"); ?>" type="text/javascript"></script>

<script type="text/javascript">
$(function () {
  $("#tabelaMovimentacoes").dataTable();
});
</script>