<!-- DATA TABLES -->
<link href="<?php echo $this->baseUrl("plugins/datatables/dataTables.bootstrap.css"); ?>" rel="stylesheet" type="text/css" />

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Relatório
        <small>movimentações cliente</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="<?php echo $this->baseUrl("/"); ?>"><i class="fa fa-dashboard"></i> Início</a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'relatorio'), null, 1); ?>">Relatório</a></li>
        <li class="active">movimentações cliente</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

              <div class="row">
            <div class="col-xs-12">

              <div class="box box-danger">
                <div class="box-header">
                  <h3 class="box-title">Relação de Clientes</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th>Clientes</th>
                        <th>Valor Crédito</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Miguel</td>
                        <td class='text-green'>19,00</td>
                      </tr>
                      <tr>
                        <td>Davi</td>
                        <td class='text-green'>16,00</td>
                      <tr>
                        <td>Sophia</td>
                        <td class='text-green'>18,00</td>
                      </tr>
                      <tr>
                        <td>Alice</td>
                        <td class='text-green'>2,00</td>
                      </tr>
                      <tr>
                        <td>Arthur</td>
                        <td class='text-green'>10,00</td>
                      </tr>
                      <tr>
                        <td>Pedro</td>
                        <td class='text-green'>88,00</td>
                      </tr>
                      <tr>
                        <td>Gabriel</td>
                        <td class='text-green'>66,00</td>
                      </tr>
                      <tr>
                        <td>Julia</td>
                        <td class='text-green'>55,00</td>
                      </tr>
                      <tr>
                        <td>Isabella</td>
                        <td class='text-green'>100,00</td>
                      </tr>
                      <tr>
                        <td>Manuela</td>
                        <td class='text-green'>45,00</td>
                      </tr>
                      <tr>
                        <td>Laura</td>
                        <td class='text-green'>45,00</td>
                      </tr>
                      <tr>
                        <td>Bernardo</td>
                        <td class='text-red'>-23,00</td>
                      </tr>
                      <tr>
                        <td>Lucas</td>
                        <td class='text-green'>54,00</td>
                      </tr>
                      <tr>
                        <td>Luiza</td>
                        <td class='text-green'>103,00</td>
                      </tr>
                      <tr>
                        <td>Valentina</td>
                        <td class='text-green'>23,00</td>
                      </tr>
                      <tr>
                        <td>Giovana</td>
                        <td class='text-green'>12,00</td>
                      </tr>
                      <tr>
                        <td>Matheus</td>
                        <td class='text-green'>33,00</td>
                      </tr>
                      <tr>
                        <td>Rafael</td>
                        <td class='text-green'>11,00</td>
                      </tr>
                      <tr>
                        <td>Heitor</td>
                        <td class='text-green'>8,00</td>
                      </tr>
                      <tr>
                        <td>Maria Eduarda</td>
                        <td class='text-green'>12,00</td>
                      </tr>
                      <tr>
                        <td>Helena</td>
                        <td class='text-green'>23,00</td>
                      </tr>
                      <tr>
                        <td>Enzo</td>
                        <td class='text-green'>134,00</td>
                      </tr>
                      <tr>
                        <td>Guilherme</td>
                        <td class='text-green'>80,00</td>
                      </tr>
                      <tr>
                        <td>Nicolas</td>
                        <td class='text-green'>100,00</td>
                      </tr>
                      <tr>
                        <td>Lorenzo</td>
                        <td class='text-green'>50,00</td>
                      </tr>
                      <tr>
                        <td>Beatriz</td>
                        <td class='text-green'>26,00</td>
                      </tr>
                      <tr>
                        <td>Maria Luiza</td>
                        <td class='text-green'>24,00</td>
                      </tr>
                      <tr>
                        <td>Gustavo</td>
                        <td class='text-green'>56,00</td>
                      </tr>
                      <tr>
                        <td>Felipe</td>
                        <td class='text-green'>178,00</td>
                      </tr>
                      <tr>
                        <td>Samuel</td>
                        <td class='text-green'>158,00</td>
                      </tr>
                      <tr>
                        <td>Lara</td>
                        <td class='text-green'>10,00</td>
                      </tr>
                      <tr>
                        <td>Mariana</td>
                        <td class='text-green'>15,00</td>
                      </tr>
                      <tr>
                        <td>Nicole</td>
                        <td class='text-green'>80,00</td>
                      </tr>
                      <tr>
                        <td>Rafaela</td>
                        <td class='text-green'>50,00</td>
                      </tr>
                    </tbody>
                    <tfoot>
                      <tr>
                        <th>Clientes</th>
                        <th>Valor Crédito</th>
                      </tr>
                    </tfoot>
                  </table>
                </div><!-- /.box-body -->

                </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->

           <div class="row">
            <div class="col-xs-12">
              <div class="box box-danger">

                <div class="box-header">
                    <h3 class="box-title">Cliente Selecionado</h3>
                  <input type="text" name="Nome" size="80" />
                </div><!-- /.box-header -->

                <div class="box-body">
                  <!-- Date range -->
                  <div class="form-group">
                      <label>Selecione Data:</label>
                    <div class="input-group" style="width: 655px;">
                      <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                      </div>
                      <input type="text" class="form-control pull-right" id="reservation" />
                    </div><!-- /.input group -->
                  </div><!-- /.form group -->

                  <!-- Date and time range -->

                </div><!-- /.box-body -->

                <div class="box-header">
                  <h3 class="box-footer">Relatório</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="relatoriocliente" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th>Entrada</th>
                        <th>Saída</th>
                        <th>Placa</th>
                        <th>Valor</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>10/02 - 07:45</td>
                        <td>10/02 - 12:07</td>
                        <td>MXX-1111</td>
                        <td>3,00</td>
                      </tr>
                      <tr>
                        <td>10/02 - 13:25</td>
                        <td>10/02 - 18:10</td>
                        <td>MXX-1111</td>
                        <td>3,00</td>
                      </tr>
                      <tr>
                        <td>11/02 - 07:38</td>
                        <td>11/02 - 12:10</td>
                        <td>MXX-1111</td>
                        <td>3,00</td>
                      </tr>
                      <tr>
                        <td>11/02 - 13:23</td>
                        <td>12/02 - 6:20</td>
                        <td>MXX-1111</td>
                        <td>9,00</td>
                      </tr>
                      <tr>
                        <td>13/02 - 07:54</td>
                        <td>13/02 - 12:18</td>
                        <td>MXK-9999</td>
                        <td>3,00</td>
                      </tr>
                      <tr>
                        <td>13/02 - 12:46</td>
                        <td>13/02 - 17:57</td>
                        <td>MXK-9999</td>
                        <td>3,00</td>

                      </tr>
                    </tbody>
                    <tfoot>
                      <tr>
                        <th>Entrada</th>
                        <th>Saída</th>
                        <th>Placa</th>
                        <th>Valor</th>
                      </tr>
                    </tfoot>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->


          <div class="col-xs-6">
              <div class="table-responsive">
                <table class="table">
                  <tr>
                    <th style="width:50%">Tempo Total:</th>
                    <td>23h 45m</td>
                  </tr>
                  <tr>
                    <th>Gasto Total:</th>
                    <td>R$24.00</td>
                  </tr>
                </table>
              </div>
            </div><!-- /.col -->
             </div><!-- /.row -->
           <!-- this row will not appear when printing -->
          <div class="row no-print">
            <div class="col-xs-12">
              <a href="invoice-print.html" target="_blank" class="btn btn-default"><i class="fa fa-print"></i> Imprimir</a>
              <button class="btn btn-primary pull-right" style="margin-right: 5px;"><i class="fa fa-download"></i> Gerar PDF</button>
            </div>
          </div>

        </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- DATA TABES SCRIPT -->
<script src="<?php echo $this->baseUrl("plugins/datatables/jquery.dataTables.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/datatables/dataTables.bootstrap.js"); ?>" type="text/javascript"></script>

<script type="text/javascript">
$(function () {
    $("#relatoriocliente").dataTable();
    $("#example1").dataTable();
});
</script>