<!-- DATA TABLES -->
<link href="<?php echo $this->baseUrl("plugins/datatables/dataTables.bootstrap.css"); ?>" rel="stylesheet" type="text/css" />

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Relatório
      <small>receita</small>
    </h1>
      <ol class="breadcrumb">
        <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => $this->usarioLogado->perfil), null, 1); ?>"><i class="fa fa-dashboard"></i> Início</a></li>
        <li>Relatório</li>
        <li class="active" >receita</li>
      </ol>
    </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-md-6">
        <div class="box box-primary">
          <div class="box-header">
            <i class="fa fa-bar-chart-o"></i>
            <h3 class="box-title">Funcionários por Estacionamento</h3>
          </div>
          <div class="box-body">
            <div id="quant-funcionario" style="height: 300px;"></div>
          </div><!-- /.box-body-->
        </div><!-- /.box -->
      </div>
      <div class="col-md-6">
        <div class="box box-primary">
          <div class="box-header">
            <i class="fa fa-bar-chart-o"></i>
            <h3 class="box-title">% Salários por Estacionamento</h3>
          </div>
          <div class="box-body">
            <div id="perc-salario" style="height: 300px;"></div>
          </div><!-- /.box-body-->
        </div><!-- /.box -->
      </div>
    </div><!-- /.row -->
    <div class="row">
      <div class="col-md-6">
        <div class="box box-primary">
          <div class="box-header">
            <i class="fa fa-bar-chart-o"></i>
            <h3 class="box-title">Receita Mensal Todos Estacionamentos</h3>
          </div>
          <div class="box-body">
            <div id="receita-mes" style="height: 300px;"></div>
          </div><!-- /.box-body-->
        </div>
      </div>
      <div class="col-md-6">
        <div class="box box-primary">
          <div class="box-header">
            <i class="fa fa-bar-chart-o"></i>
            <h3 class="box-title">% Receita por Estacionamento</h3>
          </div>
          <div class="box-body">
            <div id="receita-estacionamento" style="height: 300px;"></div>
          </div><!-- /.box-body-->
        </div><!-- /.box -->
      </div>
    </div><!-- /.row -->
    <div class="row">
      <div class="col-md-6">
        <div class="box box-primary">
          <div class="box-header">
            <i class="fa fa-bar-chart-o"></i>
            <h3 class="box-title">Receita Mensal</h3>
          </div>
          <div class="box-body">
            <div id="receita-mesal" style="height: 300px;"></div>
          </div><!-- /.box-body-->
        </div>
      </div>
      <div class="col-md-6">
        <div class="box box-primary">
          <div class="box-header">
            <i class="fa fa-bar-chart-o"></i>
            <h3 class="box-title">Receita Anual</h3>
          </div>
          <div class="box-body">
            <div id="receita-anual" style="height: 300px;"></div>
          </div><!-- /.box-body-->
        </div><!-- /.box -->
      </div>
    </div><!-- /.row -->
  </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- FLOT CHARTS -->
<script src="<?php echo $this->baseUrl("plugins/flot/jquery.flot.min.js"); ?>"  type="text/javascript"></script>
<!-- FLOT PIE PLUGIN - also used to draw donut charts -->
<script src="<?php echo $this->baseUrl("plugins/flot/jquery.flot.pie.min.js"); ?>" type="text/javascript"></script>
<!-- FLOT CATEGORIES PLUGIN - Used to draw bar charts -->
<script src="<?php echo $this->baseUrl("plugins/flot/jquery.flot.categories.min.js"); ?>" type="text/javascript"></script>

<!-- page script -->
<script type="text/javascript">
$(function () {
  /*
  * BAR CHART
  * ---------
  */

  var grafico5 = {
    data: [<?php echo $this->dadosGraficoValoresMesal; ?>],
    color: "#3c8dbc"
  };
  $.plot("#receita-mesal", [grafico5], {
    grid: {
      borderWidth: 1,
      borderColor: "#f3f3f3",
      tickColor: "#f3f3f3"
    },
    series: {
      bars: {
        show: true,
        barWidth: 0.5,
        align: "center"
      }
    },
    xaxis: {
      mode: "categories",
      tickLength: 0
    }
  });

    var grafico6 = {
    data: [<?php echo $this->dadosGraficoValoresAnual; ?>],
    color: "#3c8dbc"
  };
  $.plot("#receita-anual", [grafico6], {
    grid: {
      borderWidth: 1,
      borderColor: "#f3f3f3",
      tickColor: "#f3f3f3"
    },
    series: {
      bars: {
        show: true,
        barWidth: 0.5,
        align: "center"
      }
    },
    xaxis: {
      mode: "categories",
      tickLength: 0
    }
  });

    $.plot("#receita-mes", [<?php echo $this->dadosGraficoValoresMes; ?>], {
      lines: { show: true },
      points: { show: true },
      xaxis: { tickDecimals: 0},
      legend: { show: true }
    });

  var grafico2 = [<?php echo $this->dadosGraficoValoresEstacionamento; ?>];
  $.plot("#receita-estacionamento", grafico2, {
    series: {
      pie: {
        show: true,
        radius: 1,
        innerRadius: 0.5,
        label: {
          show: true,
          radius: 2 / 3,
          formatter: labelFormatter,
          threshold: 0
        }

      }
    },
    legend: {
      show: true
    }
  });

  var grafico3 = [<?php echo $this->dadosGraficoSalarios; ?>];
  $.plot("#perc-salario", grafico3, {
    series: {
      pie: {
        show: true,
        radius: 1,
        innerRadius: 0.5,
        label: {
          show: true,
          radius: 2 / 3,
          formatter: labelFormatter,
          threshold: 0
        }

      }
    },
    legend: {
      show: true
    }
  });

  var grafico4 = [<?php echo $this->dadosGraficoQuantFuncionarios; ?>];
  $.plot("#quant-funcionario", grafico4, {
    series: {
      pie: {
        show: true,
        radius: 1,
        innerRadius: 0.5,
        label: {
          show: true,
          radius: 2 / 3,
          formatter: labelFormatter,
          threshold: 0
        }

      }
    },
    legend: {
      show: true
    }
  });
  /*
   * END DONUT CHART
   */
  function labelFormatter(label, series) {
    return "<div style='font-size:13px; text-align:center; padding:2px; color: #fff; font-weight: 600;'>" + label + "<br/>" + Math.round(series.percent) + "%</div>";
  }
});
</script>