<!-- DATA TABLES -->
<link href="<?php echo $this->baseUrl("plugins/datatables/dataTables.bootstrap.css"); ?>" rel="stylesheet" type="text/css" />

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Relatório
        <small>receita</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="<?php echo $this->baseUrl("/"); ?>"><i class="fa fa-dashboard"></i> Início</a></li>
        <li>Relatório</li>
        <li class="active">receita</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">

            <div class="box box-danger">
            <div class="box-header">
                   <div class="form-group">
                      <label>Filial</label>
                      <select class="form-control">
                        <option>Tubarão</option>
                        <option>Imbituba</option>
                      </select>
                    </div>
            </div><!-- /.box-body -->
            </div><!-- /.box -->

            <div class="box box-danger">
            <div class="box-header">
                  <div class="form-group">
                    <label>Período</label>
                    <div class="input-group" >
                      <button class="btn btn-default pull-right" id="daterange-btn" style="width: 100px">
                        <i class="fa fa-calendar"></i> Diário<i class="fa fa-caret-down"></i>
                      </button>
                    </div>
                  </div><!-- /.form group -->
            </div><!-- /.box-header -->
            <div class="box-body">
              <table id="tabelaAutomovel" class="table table-bordered table-striped">
                <thead>
                  <tr>
                        <th>Data</th>
                        <th>Total de Horas Utilizadas</th>
                        <th>Hora Do Primeiro Faturamento</th>
                        <th>Hora Do Último Faturamento</th>
                        <th>Faturamento Total</th>
                  </tr>
                </thead>
                <tbody>
                      <tr>
                        <td>01/04/2015</td>
                        <td>120</td>
                        <td>08:30</td>
                        <td>22:40</td>
                        <td>R$2.900</td>
                      </tr>
                      <tr>
                        <td>02/04/2015</td>
                        <td>140</td>
                        <td>07:15</td>
                        <td>23:45</td>
                        <td>R$3.107</td>
                      </tr>
                </tbody>
              </table>
            </div><!-- /.box-body -->
          </div><!-- /.box -->


               <div class="box box-danger">
                <div class="box-header">
                    <h3 class="box-title">Faturamento Por Grupo</h3><br/><br/>
                  <div class="form-group" style="width: 400px">
                    <label>Data Inicial:</label>
                    <div class="input-group">
                      <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                      </div>
                      <input type="text" class="form-control" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask/>
                    </div><!-- /.input group -->
                    <label>Data Final:</label>
                    <div class="input-group">
                      <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                      </div>
                      <input type="text" class="form-control" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask/>
                    </div><!-- /.input group -->
                  </div><!-- /.form group -->
                  <div class="box-tools">
                    <div class="input-group">
                      <input type="text" name="table_search" class="form-control input-sm pull-right" style="width: 150px;" placeholder="Search"/>
                      <div class="input-group-btn">
                        <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
                      </div>
                    </div>
                  </div>
                </div><!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                  <table class="table table-hover">
                    <tr>
                        <th>Grupo</th>
                        <th>Total de Horas Utilizadas</th>
                        <th>Hora Do Primeiro Faturamento</th>
                        <th>Hora Do Último Faturamento</th>
                        <th>Faturamento Total</th>
                    </tr>
                    <tr>
                        <td>Vagas Avulsas</td>
                        <td>24</td>
                        <td>08:30</td>
                        <td>22:40</td>
                        <td>R$600</td>
                      </tr>
                      <tr>
                        <td>Vagas Para Deficientes Físicos<</td>
                        <td>12</td>
                        <td>08:54</td>
                        <td>22:56</td>
                        <td>R$200</td>
                      </tr>
                      <tr>
                        <td>Vaga De Aluguel</td>
                        <td>23</td>
                        <td>07:30</td>
                        <td>23:40</td>
                        <td>R$1000</td>
                      </tr>

                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->

    <!-- Bar chart -->
    <div class="box box-primary">
      <div class="box-header with-border">
        <i class="fa fa-bar-chart-o"></i>
        <h3 class="box-title">Faturamento Diário</h3>
        <div class="box-tools pull-right">
          <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
          <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
      </div>
      <div class="box-body">
        <div id="bar-chart1" style="height: 300px;"></div>
      </div><!-- /.box-body-->
    </div><!-- /.box -->

    <div class="box box-primary">
      <div class="box-header with-border">
        <i class="fa fa-bar-chart-o"></i>
        <h3 class="box-title">Faturamento Mensal</h3>
        <div class="box-tools pull-right">
          <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
          <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
      </div>
      <div class="box-body">
        <div id="bar-chart2" style="height: 300px;"></div>
      </div><!-- /.box-body-->
    </div><!-- /.box -->

    <div class="box box-primary">
      <div class="box-header with-border">
        <i class="fa fa-bar-chart-o"></i>
        <h3 class="box-title">Faturamento Anual</h3>
        <div class="box-tools pull-right">
          <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
          <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
      </div>
      <div class="box-body">
        <div id="bar-chart3" style="height: 300px;"></div>
      </div><!-- /.box-body-->
    </div><!-- /.box -->

</div><!-- /.col -->
      </div><!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- DATA TABES SCRIPT -->
<script src="<?php echo $this->baseUrl("plugins/datatables/jquery.dataTables.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/datatables/dataTables.bootstrap.js"); ?>" type="text/javascript"></script>

<!-- FLOT CHARTS -->
<script src="<?php echo $this->baseUrl("plugins/flot/jquery.flot.min.js"); ?>"  type="text/javascript"></script>
<!-- FLOT CATEGORIES PLUGIN - Used to draw bar charts -->
<script src="<?php echo $this->baseUrl("plugins/flot/jquery.flot.categories.min.js"); ?>" type="text/javascript"></script>

<script type="text/javascript">
$(function () {
    $("#tabelaAutomovel").dataTable();

      /*
   * BAR CHART
   * ---------
   */

  var bar_data1 = {
    data: [["01/05", 20], ["02/05", 60], ["03/05", 250], ["04/05", 79], ["05/05", 65], ["06/05", 148], ["07/05", 100], ["08/05", 52], ["09/05", 89], ["10/05", 156], ["11/05", 200], ["12/05", 50]],
    color: "#3c8dbc"
  };
  $.plot("#bar-chart1", [bar_data1], {
    grid: {
      borderWidth: 1,
      borderColor: "#f3f3f3",
      tickColor: "#f3f3f3"
    },
    series: {
      bars: {
        show: true,
        barWidth: 0.5,
        align: "center"
      }
    },
    xaxis: {
      mode: "categories",
      tickLength: 0
    }
  });
  /* END BAR CHART */

        /*
   * BAR CHART
   * ---------
   */

  var bar_data2 = {
    data: [["January", 5510], ["February", 4600], ["March", 3600], ["April", 6500], ["May", 2300]],
    color: "#3c8dbc"
  };
  $.plot("#bar-chart2", [bar_data2], {
    grid: {
      borderWidth: 1,
      borderColor: "#f3f3f3",
      tickColor: "#f3f3f3"
    },
    series: {
      bars: {
        show: true,
        barWidth: 0.5,
        align: "center"
      }
    },
    xaxis: {
      mode: "categories",
      tickLength: 0
    }
  });
  /* END BAR CHART */

        /*
   * BAR CHART
   * ---------
   */

  var bar_data3 = {
    data: [["2012", 60000], ["2013", 53320], ["2014", 76356], ["2015", 35451]],
    color: "#3c8dbc"
  };
  $.plot("#bar-chart3", [bar_data3], {
    grid: {
      borderWidth: 1,
      borderColor: "#f3f3f3",
      tickColor: "#f3f3f3"
    },
    series: {
      bars: {
        show: true,
        barWidth: 0.5,
        align: "center"
      }
    },
    xaxis: {
      mode: "categories",
      tickLength: 0
    }
  });
  /* END BAR CHART */
});
</script>