<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Vagas Disponíveis
        <small>estacionamento</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="<?php echo $this->baseUrl("/"); ?>"><i class="fa fa-dashboard"></i> Início</a></li>
        <li><a href="">Vagas Disponíveis</a></li>
        <li class="active">editar</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="box box-danger">
            <div class="box-header">
              <h3 class="box-title">Vagas Disponíveis por Estacionamento</h3>
            </div>
            <div class="box-body">
                <!-- select -->
                    <div class="form-group" style="width: 655px;">
                      <label>Selecionar Estacionamento</label>
                      <select class="form-control ">
                        <option>Estacionamento 1</option>
                        <option>Estacionamento 2</option>
                        <option>Estacionamento 3</option>
                        <option>Estacionamento 4</option>
                      </select>
                    </div>

            <!-- info row -->
          <div class="row invoice-info">
            <div class="col-sm-4 invoice-col">
              <address>
                <strong>Estacionamento 1</strong><br>
                R. Januário Alves García, 54<br>
                Centro - Tubarão<br>
                Telefone: (48) 3622-0000<br/>
                Email: filial1@nznestacionamentos.com
              </address>
            </div><!-- /.col -->
            <div class="col-sm-4 invoice-col">
              <address>
                <strong>Estacionamento 2</strong><br>
                R. Lauro Müller, 212<br>
                Centro - Tubarão<br>
                Telefone: (48) 3622-0001<br/>
                Email: filial2@nznestacionamentos.com
              </address>
            </div><!-- /.col -->
            <div class="col-sm-4 invoice-col">
              <address>
                <strong>Estacionamento 3</strong><br>
                Av. Patrício Lima, 365<br>
                Humaitá - Tubarão<br>
                Telefone: (48) 3622-0003<br/>
                Email: filial3@nznestacionamentos.com
              </address>
            </div><!-- /.col -->
            <div class="col-sm-4 invoice-col">
              <address>
                 <strong>Estacionamento 4</strong><br>
                R. Coronel José Martins Cabral, 119<br>
                Centro - Tubarão<br>
                Telefone: (48) 3622-0004<br/>
                Email: filial4@nznestacionamentos.com
              </address>
            </div><!-- /.col -->
          </div><!-- /.row -->


                <div class="box-header">
                  <h3 class="box-title">Vagas Disponíveis</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="relatoriocliente" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th>Tipo de Vaga</th>
                        <th>Quantidade Disponível</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Automóveis</td>
                        <td>35</td>
                      </tr>
                      <tr>
                        <td>Deficientes</td>
                        <td>10</td>
                      </tr>
                      <tr>
                        <td>Idosos</td>
                        <td>12</td>
                      </tr>
                    </tbody>
                  </table>
            </div>
              </div><!-- /.box-body -->
          </div><!-- /.box -->
        </div><!-- /.col -->
      </div>   <!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- InputMask -->
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.date.extensions.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.extensions.js"); ?>" type="text/javascript"></script>

<script type="text/javascript">
  $(function () {
    $("#datemask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
    $("[data-mask]").inputmask();
  });
</script>