<style type="text/css">
#mask {
  position:absolute;
  left:0;
  top:0;
  z-index:9000;
  background-color:#000;
  display:none;
}

.window {
  position:absolute;
  top: auto;
  bottom: auto;
  right: auto;
  left: auto;
  display:none;
  z-index:9999;
}
.modal {
  background: transparent!important;
}
</style>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Estacionamentos
        <small>editar</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="<?php echo $this->baseUrl("/"); ?>"><i class="fa fa-dashboard"></i> Início</a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'estacionamento'), null, 1); ?>">Estacionamentos</a></li>
        <li class="active">editar</li>
      </ol>
    </section>

    <div class="modal window">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><i class="icon fa fa-warning"></i> Atenção!</h4>
          </div>
          <div class="modal-body">
          </div>
          <div class="modal-footer buttons">
            <input type="hidden" id="status" />
            <button id="alterarStatus" type="button" class="btn btn-outline">Sim</button>
            <button type="button" class="btn btn-outline close2">Não</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <!-- Máscara para cobrir a tela -->
    <div id="mask"></div>

    <!-- Main content -->
    <section class="content">

      <?php if ($this->sucesso) : ?>
        <div class="alert alert-success alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h4><i class="icon fa fa-check"></i> Sucesso!</h4>
          <?php echo $this->sucesso; ?>
        </div>
      <?php endif; ?>
      <?php if ($this->novo) : ?>
        <div class="alert alert-success alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h4><i class="icon fa fa-check"></i> Sucesso!</h4>
          <?php echo $this->novo; ?>
        </div>
      <?php endif; ?>
      <?php if ($this->erro) : ?>
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h4><i class="icon fa fa-warning"></i> Atenção!</h4>
          <?php echo $this->erro; ?>
        </div>
      <?php endif; ?>

      <div class="row">
        <div class="col-md-12">
          <div class="box box-danger">
            <div class="box-header">
              <h3 class="box-title">Editar Estacionamento</h3>
            </div>
            <div class="box-body">
              <div class="form-group">
                <!-- form start -->
                <input type="hidden" id="id" value="<?php echo $this->estacionamento['id']; ?>" />
                <form action="" method="post">
                  <label>Nome</label>
                  <div class="input-group margin-bottom col-md-6">
                    <div class="input-group-addon">
                      <i class="fa fa-user"></i>
                    </div>
                    <input type="text" id="nome" name="nome" value="<?php echo $this->form->nome->getValue(); ?>" class="form-control" placeholder="Nome" required />
                  </div><!-- /.input group -->
                  <label>E-mail</label>
                  <div class="input-group margin-bottom col-md-6">
                    <div class="input-group-addon">
                      <i class="fa fa-envelope"></i>
                    </div>
                    <input type="text" id="email" name="email" value="<?php echo $this->form->email->getValue(); ?>" class="form-control" placeholder="E-mail" required />
                  </div><!-- /.input group -->
                  <label>Telefone</label>
                  <div class="input-group margin-bottom col-md-3">
                    <div class="input-group-addon">
                      <i class="fa fa-phone"></i>
                    </div>
                    <input type="text" name="telefone" value="<?php echo $this->form->telefone->getValue(); ?>" class="form-control" placeholder="Telefone" data-inputmask='"mask": "(99) 9999-9999"' data-mask required />
                  </div><!-- /.input group -->
                  <div class="box">
                    <div class="box-header">
                      <h3 class="box-title">Dados do Documento</h3>
                    </div>
                    <div class="box-body">
                      <div class="row">
                        <div class="col-md-4">
                          <label>CNPJ</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="cnpj" value="<?php echo $this->form->cnpj->getValue(); ?>" class="form-control" placeholder="CNPJ" data-inputmask='"mask": "99.999.999/9999-99"' data-mask required />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-md-4">
                          <label>Data de Fundação</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" name="data_fundacao" value="<?php echo $this->formatoData($this->form->data_fundacao->getValue()); ?>" class="form-control" placeholder="Data de Fundação" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask required />
                          </div><!-- /.input group -->
                        </div>
                      </div>
                    </div><!-- /.box-body -->
                  </div><!-- /.box -->
                  <div class="box">
                    <div class="box-header">
                      <h3 class="box-title">Dados de Endereço</h3>
                    </div>
                    <div class="box-body">
                      <div class="row">
                        <div class="col-md-2">
                          <label>CEP</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="cep" value="<?php echo $this->form->cep->getValue(); ?>" class="form-control" placeholder="CEP" data-inputmask='"mask": "99999-999"' data-mask required />
                          </div><!-- /.input group -->
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-4">
                          <label>Logradouro</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="logradouro" value="<?php echo $this->form->logradouro->getValue(); ?>" class="form-control" placeholder="Logradouro" required />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-md-1">
                          <label>Número</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-circle-o"></i>
                            </div>
                            <input type="text" name="numero" value="<?php echo $this->form->numero->getValue(); ?>" class="form-control inteiro" placeholder="Nº" required />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-md-4">
                          <label>Complemento</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="complemento" value="<?php echo $this->form->complemento->getValue(); ?>" class="form-control" placeholder="Complemento" />
                          </div><!-- /.input group -->
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-4">
                          <label>Bairro</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="bairro" value="<?php echo $this->form->bairro->getValue(); ?>" class="form-control" placeholder="Bairro" required />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-md-1">
                          <?php echo $this->form->uf; ?>
                        </div>
                        <div class="col-md-4">
                          <label>Cidade</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="cidade" value="<?php echo $this->form->cidade->getValue(); ?>" class="form-control" placeholder="Cidade" required />
                          </div><!-- /.input group -->
                        </div>
                      </div>
                    </div><!-- /.box-body -->
                  </div><!-- /.box -->
                  <div class="box box-solid">
                    <div class="box-header">
                      <i class="fa fa-bar-chart-o"></i>
                      <h3 class="box-title">Configurar Estacionamento</h3>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                      <div class="row">
                        <div class="col-md-3 col-sm-6 col-xs-6 text-center">
                          <input type="text" name="nr_vaga_comum" value="<?php echo $this->form->nr_vaga_comum->getValue(); ?>" class="knob" data-thickness="0.2" data-angleArc="250" data-angleOffset="-125" data-width="120" data-height="120" data-fgColor="#00A65A"/>
                          <div class="knob-label">Vagas Comuns</div>
                        </div><!-- ./col -->
                        <div class="col-md-3 col-sm-6 col-xs-6 text-center">
                          <input type="text" name="nr_vaga_especial" value="<?php echo $this->form->nr_vaga_especial->getValue(); ?>" class="knob" data-thickness="0.2" data-angleArc="250" data-angleOffset="-125" data-width="120" data-height="120" data-fgColor="#F39C12"/>
                          <div class="knob-label">Vagas Especiais</div>
                        </div><!-- ./col -->
                        <div class="col-md-3 col-sm-6 col-xs-6 text-center">
                          <input type="text" name="nr_vaga_aluguel" value="<?php echo $this->form->nr_vaga_aluguel->getValue(); ?>" class="knob" data-thickness="0.2" data-angleArc="250" data-angleOffset="-125" data-width="120" data-height="120" data-fgColor="#3C8DBC"/>
                          <div class="knob-label">Vagas Aluguéis</div>
                        </div><!-- ./col -->
                      </div><!-- /.row -->
                    </div><!-- /.box-body -->
                  </div><!-- /.box -->
                  <div class="box">
                    <div class="box-header">
                      <h3 class="box-title">Tabela de Preço</h3>
                    </div>
                    <div class="box-body">
                      <div class="row">
                        <div class="col-md-3">
                          <label>Valor</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              R$
                            </div>
                            <input type="text" name="valor" value="2,00" class="form-control dinheiro" placeholder="Valor" />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-md-3">
                          <label>Tempo em Minutos</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-clock-o"></i>
                            </div>
                            <input type="text" name="tempo" value="060" class="form-control inteiro" placeholder="Tempo" />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-md-5">
                          <label>Descrição</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="descricao" value="1 Hora" class="form-control" placeholder="Descrição" />
                          </div><!-- /.input group -->
                        </div>
                      </div>
                    </div><!-- /.box-body -->
                    <!-- <button type="submit" class="btn btn-success pull-right">+ Tabela Preço</button> -->
                  </div><!-- /.box -->
                  <div class="row">
                    <div class="col-md-4 margin-bottom">
                      <button type="submit" class="btn btn-primary">Alterar</button>
                      <button type="button" class="btn btn-danger inativar">Inativar</button>
                    </div><!-- /.col -->
                  </div>
                </form>
              </div>
            </div>
          </div><!-- /.box -->
        </div><!-- /.col -->
      </div>   <!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- InputMask -->
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.date.extensions.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.extensions.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.maskMoney.js"); ?>" ></script>
<!-- jQuery Knob -->
<script src="<?php echo $this->baseUrl("plugins/knob/jquery.knob.js"); ?>" type="text/javascript"></script>

<script type="text/javascript">
$(function () {
  $("#datemask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
  $("[data-mask]").inputmask();
  $('.inteiro').maskMoney({thousands: '', decimal: ''});
  $('.dinheiro').maskMoney({thousands: '', decimal: ','});
  $('.inativar').click(function(e) {
    e.preventDefault();

    var id = '.modal';

    var maskHeight = $(document).height();
    var maskWidth = $(window).width();

    $('#mask').css({'width':maskWidth,'height':maskHeight});

    $('#mask').fadeIn(1000);
    $('#mask').fadeTo("slow",0.8);

    var winH = $(window).height();
    var winW = $(window).width();

    $(id).css('top',  winH/2-$(id).height()/3);
    $(id).css('left', winW/2-$(id).width()/2);

    $(id).fadeIn(2000);
  });

  $('.window .close, .window .close2').click(function (e) {
    e.preventDefault();
    $('#mask').hide();
    $('.window').hide();
  });

  $('#mask').click(function () {
    $(this).hide();
    $('.window').hide();
  });

  /* jQueryKnob */
  $(".knob").knob({
    max: 1000,
    /*change : function (value) {
     //console.log("change : " + value);
     },
     release : function (value) {
     console.log("release : " + value);
     },
     cancel : function () {
     console.log("cancel : " + this.value);
     },*/
    draw: function () {

      // "tron" case
      if (this.$.data('skin') == 'tron') {

        var a = this.angle(this.cv)  // Angle
                , sa = this.startAngle          // Previous start angle
                , sat = this.startAngle         // Start angle
                , ea                            // Previous end angle
                , eat = sat + a                 // End angle
                , r = true;

        this.g.lineWidth = this.lineWidth;

        this.o.cursor
                && (sat = eat - 0.3)
                && (eat = eat + 0.3);

        if (this.o.displayPrevious) {
          ea = this.startAngle + this.angle(this.value);
          this.o.cursor
                  && (sa = ea - 0.3)
                  && (ea = ea + 0.3);
          this.g.beginPath();
          this.g.strokeStyle = this.previousColor;
          this.g.arc(this.xy, this.xy, this.radius - this.lineWidth, sa, ea, false);
          this.g.stroke();
        }

        this.g.beginPath();
        this.g.strokeStyle = r ? this.o.fgColor : this.fgColor;
        this.g.arc(this.xy, this.xy, this.radius - this.lineWidth, sat, eat, false);
        this.g.stroke();

        this.g.lineWidth = 2;
        this.g.beginPath();
        this.g.strokeStyle = this.o.fgColor;
        this.g.arc(this.xy, this.xy, this.radius - this.lineWidth + 1 + this.lineWidth * 2 / 3, 0, 2 * Math.PI, false);
        this.g.stroke();

        return false;
      }
    }
  });
  /* END JQUERY KNOB */
});
</script>