<style type="text/css">
#mask {
  position:absolute;
  left:0;
  top:0;
  z-index:9000;
  background-color:#000;
  display:none;
}

.window {
  position:absolute;
  top: auto;
  bottom: auto;
  right: auto;
  left: auto;
  display:none;
  z-index:9999;
}
.modal {
  background: transparent!important;
}
</style>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Estacionamentos
        <small>editar estacionamento</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="<?php echo $this->baseUrl("/"); ?>"><i class="fa fa-dashboard"></i> Início</a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'estacionamento'), null, 1); ?>">Estacionamentos</a></li>
        <li class="active">editar</li>
      </ol>
    </section>

    <div class="modal window modal-danger">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><i class="icon fa fa-warning"></i> Atenção!</h4>
          </div>
          <div class="modal-body">
            <p>Você tem certeza que deseja <strong>Inativar</strong> esse Estacionamento?</p>
          </div>
          <div class="modal-footer buttons">
            <button type="button" class="btn btn-outline">Sim</button>
            <button type="button" class="btn btn-outline close2">Não</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <!-- Máscara para cobrir a tela -->
    <div id="mask"></div>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="box box-danger">
            <div class="box-header">
              <h3 class="box-title">Editar Estacionamento</h3>
            </div>
            <div class="box-body">
              <div class="form-group">
                <!-- form start -->
                <form action="" method="post">
                  <label>Nome</label>
                  <div class="input-group margin-bottom col-md-6">
                    <div class="input-group-addon">
                      <i class="fa fa-user"></i>
                    </div>
                    <input type="text" name="nome" value="<?php echo $this->form->nome->getValue(); ?>" class="form-control" placeholder="Nome" />
                  </div><!-- /.input group -->
                  <label>Número de Vagas</label>
                  <div class="input-group margin-bottom col-md-3">
                    <div class="input-group-addon">
                      <i class="fa fa-dashboard"></i>
                    </div>
                    <input type="text" name="vagas" value="100" class="form-control inteiro" placeholder="Nº de Vagas" />
                  </div><!-- /.input group -->
                    <div class="box">
                    <div class="box-header">
                      <h3 class="box-title">Dados do Documento</h3>
                    </div>
                    <div class="box-body">
                      <div class="row">
                        <div class="col-md-4">
                          <label>CNPJ</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="cnpj" value="<?php echo $this->form->cnpj->getValue(); ?>" class="form-control" placeholder="CNPJ" data-inputmask='"mask": "99.999.999/9999-99"' data-mask />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-xs-4">
                          <label>Data de Fundação</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" name="dataFundacao" value="<?php echo $this->form->data_fundacao->getValue(); ?>" class="form-control" placeholder="Data de Fundação" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask />
                          </div><!-- /.input group -->
                        </div>
                      </div>
                    </div><!-- /.box-body -->
                  </div><!-- /.box -->
                  <div class="box">
                    <div class="box-header">
                      <h3 class="box-title">Tabela de Preço</h3>
                    </div>
                    <div class="box-body">
                      <div class="row">
                        <div class="col-xs-3">
                          <label>Valor</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              R$
                            </div>
                            <input type="text" name="valor" value="2,00" class="form-control dinheiro" placeholder="Valor" />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-xs-3">
                          <label>Tempo em Minutos</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-clock-o"></i>
                            </div>
                            <input type="text" name="tempo" value="060" class="form-control inteiro" placeholder="Tempo" />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-xs-5">
                          <label>Descrição</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="descricao" value="1 Hora" class="form-control" placeholder="Descrição" />
                          </div><!-- /.input group -->
                        </div>
                      </div>
                    </div><!-- /.box-body -->
                    <button type="submit" class="btn btn-success pull-right">+ Tabela Preço</button>
                  </div><!-- /.box -->
                  <div class="row">
                    <div class="col-xs-4 margin-bottom">
                      <button type="submit" class="btn btn-primary">Alterar</button>
                      <button type="button" class="btn btn-danger inativar">Inativar</button>
                    </div><!-- /.col -->
                  </div>
                </form>
              </div>
            </div>
          </div><!-- /.box -->
        </div><!-- /.col -->
      </div>   <!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- InputMask -->
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.date.extensions.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.extensions.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.maskMoney.js"); ?>" ></script>

<script type="text/javascript">
$(function () {
  $("#datemask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
  $("[data-mask]").inputmask();
  $('.inteiro').maskMoney({thousands: '', decimal: ''});
  $('.dinheiro').maskMoney({thousands: '', decimal: ','});
  $('.inativar').click(function(e) {
    e.preventDefault();

    var id = '.modal';

    var maskHeight = $(document).height();
    var maskWidth = $(window).width();

    $('#mask').css({'width':maskWidth,'height':maskHeight});

    $('#mask').fadeIn(1000);
    $('#mask').fadeTo("slow",0.8);

    var winH = $(window).height();
    var winW = $(window).width();

    $(id).css('top',  winH/2-$(id).height()/3);
    $(id).css('left', winW/2-$(id).width()/2);

    $(id).fadeIn(2000);
  });

  $('.window .close, .window .close2').click(function (e) {
    e.preventDefault();
    $('#mask').hide();
    $('.window').hide();
  });

  $('#mask').click(function () {
    $(this).hide();
    $('.window').hide();
  });
});
</script>