<!-- DATA TABLES -->
<link href="<?php echo $this->baseUrl("plugins/datatables/dataTables.bootstrap.css"); ?>" rel="stylesheet" type="text/css" />
<style type="text/css">
#mask {
  position:absolute;
  left:0;
  top:0;
  z-index:9000;
  background-color:#000;
  display:none;
}
.window {
  position:absolute;
  top: auto;
  bottom: auto;
  right: auto;
  left: auto;
  display:none;
  z-index:9999;
}
.modal {
  background: transparent!important;
}
</style>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Estacionamentos
        <small>lista</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => $this->usarioLogado->perfil), null, 1); ?>"><i class="fa fa-dashboard"></i> Início</a></li>
        <li>Estacionamentos</li>
      </ol>
    </section>

    <div class="modal window">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><i class="icon fa fa-warning"></i> Atenção!</h4>
          </div>
          <div class="modal-body">
          </div>
          <div class="modal-footer buttons">
            <input type="hidden" id="indexAtual" />
            <input type="hidden" id="status" />
            <button id="alterarStatus" type="button" class="btn btn-outline">Sim</button>
            <button type="button" class="btn btn-outline close2">Não</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <!-- Máscara para cobrir a tela -->
    <div id="mask"></div>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box box-danger">
            <div class="box-header">
              <a href="<?php echo $this->url(array('controller' => 'estacionamento', 'action' => 'new'), null, 1); ?>">
                <button type="button" class="btn btn-danger">Novo Estacionamento</button>
              </a>
            </div><!-- /.box-header -->
            <div class="box-body">
              <table id="tabelaEstacionamentos" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Código</th>
                    <th>Nome</th>
                    <th>CNPJ</th>
                    <th>Data Fundação</th>
                    <th>Ações</th>
                  </tr>
                </thead>
                <tbody>
                <?php foreach($this->estacionamentos as $estacionamento): ?>
                  <tr <?php if ($estacionamento['ativo'] == false) echo 'style="background-color: #D5D4D3;"'; ?>>
                    <td><span class="id"><?php echo $estacionamento['id']; ?></span></td>
                    <td><span class="nome"><?php echo $estacionamento['nome']; ?></span></td>
                    <td><?php echo $estacionamento['cnpj']; ?></td>
                    <td><?php echo $this->formatoData($estacionamento['data_fundacao']); ?></td>
                    <td class="col-sm-2 text-center">
                      <?php if ($estacionamento['ativo'] == true) : ?>
                      <a href="<?php echo $this->url(array('controller' => 'estacionamento', 'action' => 'edit', 'id' =>$estacionamento['id']), null, 1); ?>"><span class="label label-primary">Editar</span></a>
                      <a href=""><span class="label label-danger status">Inativar</span></a>
                      <?php else : ?>
                      <a href=""><span class="label label-success status">Ativar</span></a>
                      <?php endif; ?>
                    </td>
                  </tr>
                <?php endforeach;?>
                </tbody>
              </table>
            </div><!-- /.box-body -->
          </div><!-- /.box -->
        </div><!-- /.col -->
      </div><!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- DATA TABES SCRIPT -->
<script src="<?php echo $this->baseUrl("plugins/datatables/jquery.dataTables.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/datatables/dataTables.bootstrap.js"); ?>" type="text/javascript"></script>

<script type="text/javascript">
$(function () {
  $("#tabelaEstacionamentos").dataTable();
  $('.status').click(function(e) {
    e.preventDefault();

    var acao = $(this).text();
    var index = $('.status').index(this);
    $('#indexAtual').val(index);
    $('#status').val(acao);

    if (acao === 'Ativar') {
      $('.modal').addClass('modal-success');
      $('.modal').removeClass('modal-danger');
    } else {
      $('.modal').addClass('modal-danger');
      $('.modal').removeClass('modal-success');
    }

    $('.modal-body').html('<p>Você tem certeza que deseja <strong>' + acao + '</strong> o Estacionamento ' + $('.nome:eq(' + index + ')').text() + '?</p>');
    var id = '.modal';

    var maskHeight = $(document).height();
    var maskWidth = $(window).width();

    $('#mask').css({'width':maskWidth,'height':maskHeight});

    $('#mask').fadeIn(1000);
    $('#mask').fadeTo("slow",0.8);

    var winH = $(window).height();
    var winW = $(window).width();

    $(id).css('top',  winH/2-$(id).height()/3);
    $(id).css('left', winW/2-$(id).width()/2);

    $(id).fadeIn(2000);
    return false;
  });

  $('#alterarStatus').click(function() {
    var index = $('#indexAtual').val();
    var id = parseInt($('.id:eq(' + index + ')').text());
    var status = $('#status').val() === 'Ativar' ? '1' : '0';
    $.ajax({
      type: "GET",
      url: '/estacionamento/alterastatus/id/' + id + '/status/' + status,
        success: function(dados) {
          location.reload(true);
        }
    });
  });

  $('.window .close, .window .close2').click(function (e) {
    e.preventDefault();
    $('#mask').hide();
    $('.window').hide();
  });

  $('#mask').click(function () {
    $(this).hide();
    $('.window').hide();
  });
});
</script>