<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Estacionamentos
        <small>novo estacionamento</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="<?php echo $this->baseUrl("/"); ?>"><i class="fa fa-dashboard"></i> Início</a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'funcionario'), null, 1); ?>">Estacionamentos</a></li>
        <li class="active">novo</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

             <div class="row">
        <div class="col-md-12">
          <div class="box box-danger">
            <div class="box-header">
              <h3 class="box-title">Novo Estacionamento</h3>
            </div>
            <div class="box-body">
              <div class="form-group">
                <!-- form start -->
                <form action="" method="post">
                  <label>Nome</label>
                  <div class="input-group margin-bottom col-md-4">
                    <div class="input-group-addon">
                      <i class="fa fa-user"></i>
                    </div>
                    <input type="text" name="nome" class="form-control" placeholder="Nome" />
                  </div><!-- /.input group -->
                  <label>Administrador</label>
                  <div class="input-group margin-bottom col-md-4">
                    <div class="input-group-addon">
                      <i class="fa fa-user"></i>
                    </div>
                    <input type="text" name="adm" class="form-control" placeholder="Nome do Administrador" />
                  </div><!-- /.input group -->
                  <label>Número de Vagas</label>
                  <div class="input-group margin-bottom col-md-2">
                    <div class="input-group-addon">
                      <i class="fa fa-dashboard"></i>
                    </div>
                    <input type="text" name="vagas" class="form-control" placeholder="Telefone" data-inputmask='"mask": "(99) 9999-9999"' data-mask />
                  </div><!-- /.input group -->
                                    <div class="box">
                    <div class="box-header">
                      <h3 class="box-title">Dados do Documento</h3>
                    </div>
                    <div class="box-body">
                      <div class="row">
                        <div class="col-xs-3">
                          <label>CNPJ</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="cnpj" class="form-control" placeholder="CNPJ" data-inputmask='"mask": "999.999.999-99"' data-mask />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-xs-3">
                          <label>Data de Fundação</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" name="dataFundacao" class="form-control" placeholder="Data de Fundação" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask />
                          </div><!-- /.input group -->
                        </div>
                      </div>
                    </div><!-- /.box-body -->
                  </div><!-- /.box -->
                  <div class="box">
                    <div class="box-header">
                      <h3 class="box-title">Tabela de Preço</h3>
                    </div>
                    <div class="box-body">
                      <div class="row">
                        <div class="col-xs-3">
                          <label>Valor</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa">R$</i>
                            </div>
                            <input type="text" name="valor" class="form-control" placeholder="Valor da Vaga" />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-xs-3">
                          <label>Tempo</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" name="tempo" class="form-control" placeholder="Tempo" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-xs-3">
                          <label>Descrição</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa-star-o"></i>
                            </div>
                            <input type="text" name="descricao" class="form-control" placeholder="Descrição" />
                          </div><!-- /.input group -->
                        </div>
                      </div>
                    </div><!-- /.box-body -->
                  </div><!-- /.box -->
                  <div class="row">
                    <div class="col-xs-4 margin-bottom">
                      <button type="submit" class="btn btn-success">Cadastrar</button>
                    </div><!-- /.col -->
                  </div>
                </form>
              </div>
            </div>
          </div><!-- /.box -->
        </div><!-- /.col -->
      </div>   <!-- /.row -->
        </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- InputMask -->
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.date.extensions.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.extensions.js"); ?>" type="text/javascript"></script>

<script type="text/javascript">
  $(function () {
    $("#datemask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
    $("[data-mask]").inputmask();
  });
</script>