<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Estacionamentos
        <small>novo</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="<?php echo $this->baseUrl("/"); ?>"><i class="fa fa-dashboard"></i> Início</a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'estacionamento'), null, 1); ?>">Estacionamentos</a></li>
        <li class="active">novo</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <?php if ($this->erro) : ?>
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h4><i class="icon fa fa-warning"></i> Atenção!</h4>
          <?php echo $this->erro; ?>
        </div>
      <?php endif; ?>

      <div class="row">
        <div class="col-md-12">
          <div class="box box-danger">
            <div class="box-header">
              <h3 class="box-title">Novo Estacionamento</h3>
            </div>
            <div class="box-body">
              <div class="form-group">
                <!-- form start -->
                <form action="" method="post">
                  <label>Nome</label>
                  <div class="input-group margin-bottom col-md-6">
                    <div class="input-group-addon">
                      <i class="fa fa-user"></i>
                    </div>
                    <input type="text" id="nome" name="nome" value="<?php echo $this->form->nome->getValue(); ?>" class="form-control" placeholder="Nome" required />
                  </div><!-- /.input group -->
                  <label>E-mail</label>
                  <div class="input-group margin-bottom col-md-6">
                    <div class="input-group-addon">
                      <i class="fa fa-envelope"></i>
                    </div>
                    <input type="text" id="email" name="email" value="<?php echo $this->form->email->getValue(); ?>" class="form-control" placeholder="E-mail" required />
                  </div><!-- /.input group -->
                  <label>Telefone</label>
                  <div class="input-group margin-bottom col-md-3">
                    <div class="input-group-addon">
                      <i class="fa fa-phone"></i>
                    </div>
                    <input type="text" name="telefone" value="<?php echo $this->form->telefone->getValue(); ?>" class="form-control" placeholder="Telefone" data-inputmask='"mask": "(99) 9999-9999"' data-mask required />
                  </div><!-- /.input group -->
                  <div class="box">
                    <div class="box-header">
                      <h3 class="box-title">Dados do Documento</h3>
                    </div>
                    <div class="box-body">
                      <div class="row">
                        <div class="col-md-4">
                          <label>CNPJ</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="cnpj" value="<?php echo $this->form->cnpj->getValue(); ?>" class="form-control" placeholder="CNPJ" data-inputmask='"mask": "99.999.999/9999-99"' data-mask required />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-md-4">
                          <label>Data de Fundação</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" name="data_fundacao" value="<?php echo $this->formatoData($this->form->data_fundacao->getValue()); ?>" class="form-control" placeholder="Data de Fundação" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask required />
                          </div><!-- /.input group -->
                        </div>
                      </div>
                    </div><!-- /.box-body -->
                  </div><!-- /.box -->
                  <div class="box">
                    <div class="box-header">
                      <h3 class="box-title">Dados de Endereço</h3>
                    </div>
                    <div class="box-body">
                      <div class="row">
                        <div class="col-md-3">
                          <label>CEP</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="cep" value="<?php echo $this->form->cep->getValue(); ?>" class="form-control" placeholder="CEP" data-inputmask='"mask": "99999-999"' data-mask required />
                          </div><!-- /.input group -->
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-4">
                          <label>Logradouro</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="logradouro" value="<?php echo $this->form->logradouro->getValue(); ?>" class="form-control" placeholder="Logradouro" required />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-md-2">
                          <label>Número</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-circle-o"></i>
                            </div>
                            <input type="text" name="numero" value="<?php echo $this->form->numero->getValue(); ?>" class="form-control inteiro" placeholder="Nº" required />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-md-4">
                          <label>Complemento</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="complemento" value="<?php echo $this->form->complemento->getValue(); ?>" class="form-control" placeholder="Complemento" />
                          </div><!-- /.input group -->
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-4">
                          <label>Bairro</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="bairro" value="<?php echo $this->form->bairro->getValue(); ?>" class="form-control" placeholder="Bairro" required />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-md-2">
                          <?php echo $this->form->uf; ?>
                        </div>
                        <div class="col-md-4">
                          <label>Cidade</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="cidade" value="<?php echo $this->form->cidade->getValue(); ?>" class="form-control" placeholder="Cidade" required />
                          </div><!-- /.input group -->
                        </div>
                      </div>
                    </div><!-- /.box-body -->
                  </div><!-- /.box -->
                  <div class="box box-solid">
                    <div class="box-header">
                      <i class="fa fa-bar-chart-o"></i>
                      <h3 class="box-title">Configurar Estacionamento</h3>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                      <div class="row">
                        <div class="col-md-4 col-sm-4 col-xs-6 text-center">
                          <input type="text" name="nr_vaga_comum" value="<?php echo (isset($_POST['nr_vaga_comum'])) ? $_POST['nr_vaga_comum'] : 0; ?>" class="knob" data-thickness="0.2" data-angleArc="250" data-angleOffset="-125" data-width="120" data-height="120" data-fgColor="#00A65A"/>
                          <div class="knob-label">Vagas Comuns</div>
                        </div><!-- ./col -->
                        <div class="col-md-4 col-sm-4 col-xs-6 text-center">
                          <input type="text" name="nr_vaga_especial" value="<?php echo (isset($_POST['nr_vaga_especial'])) ? $_POST['nr_vaga_comum'] : 0; ?>" class="knob" data-thickness="0.2" data-angleArc="250" data-angleOffset="-125" data-width="120" data-height="120" data-fgColor="#F39C12"/>
                          <div class="knob-label">Vagas Especiais</div>
                        </div><!-- ./col -->
                        <div class="col-md-4 col-sm-4 col-xs-6 text-center">
                          <input type="text" name="nr_vaga_aluguel" value="<?php echo (isset($_POST['nr_vaga_aluguel'])) ? $_POST['nr_vaga_comum'] : 0; ?>" class="knob" data-thickness="0.2" data-angleArc="250" data-angleOffset="-125" data-width="120" data-height="120" data-fgColor="#3C8DBC"/>
                          <div class="knob-label">Vagas Aluguéis</div>
                        </div><!-- ./col -->
                      </div><!-- /.row -->
                    </div><!-- /.box-body -->
                  </div><!-- /.box -->
                  <div class="box">
                    <div class="box-header">
                      <h3 class="box-title">Tabela de Preço</h3>
                    </div>
                    <div class="box-body tabelas margin-bottom">
                      <div class="row tabela">
                        <div class="col-md-5">
                          <label>Descrição</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-edit"></i>
                            </div>
                            <input type="text" name="descricao[]" class="form-control" placeholder="Descrição" required />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-md-3">
                          <label>Tempo em Minutos</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              <i class="fa fa-clock-o"></i>
                            </div>
                            <input type="text" name="tempo[]" class="form-control inteiro" placeholder="Tempo" required />
                          </div><!-- /.input group -->
                        </div>
                        <div class="col-md-3">
                          <label>Valor</label>
                          <div class="input-group">
                            <div class="input-group-addon">
                              R$
                            </div>
                            <input type="text" name="valor[]" class="form-control dinheiro" placeholder="Valor" required />
                          </div><!-- /.input group -->
                        </div>
                      </div>
                    </div><!-- /.box-body -->
                    <button type="submit" class="btn btn-danger margin pull-right remove-tabela">- Tabela Preço</button>
                    <button type="submit" class="btn btn-success margin pull-right add-tabela">+ Tabela Preço</button>
                  </div><!-- /.box -->
                  <div class="row">
                    <div class="col-md-12 margin-bottom">
                      <button type="submit" class="btn btn-success">Cadastrar</button>
                    </div><!-- /.col -->
                  </div>
                </form>
              </div>
            </div>
          </div><!-- /.box -->
        </div><!-- /.col -->
      </div>   <!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- InputMask -->
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.date.extensions.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.inputmask.extensions.js"); ?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl("plugins/input-mask/jquery.maskMoney.js"); ?>" ></script>
<!-- jQuery Knob -->
<script src="<?php echo $this->baseUrl("plugins/knob/jquery.knob.js"); ?>" type="text/javascript"></script>

<script type="text/javascript">
$(function () {
  $("#datemask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
  $("[data-mask]").inputmask();
  $('.inteiro').maskMoney({thousands: '', decimal: ''});
  $('.dinheiro').maskMoney({thousands: '', decimal: ','});
  $('.add-tabela').click(function(e) {
    e.preventDefault();
    $(".tabela:first").clone().appendTo(".tabelas");
    $(".tabela:last").find('input:text').val('');
    $('.inteiro').maskMoney({thousands: '', decimal: ''});
    $('.dinheiro').maskMoney({thousands: '', decimal: ','});
  });
  $('.remove-tabela').click(function(e) {
    e.preventDefault();
    if ($(".tabela").length === 1) {
      alert('O Estacionamento deve conter pelo menos 1 Tabela de Preço!');
    } else {
      $(".tabela:last").remove();
    }
  });
  /* jQueryKnob */
  $(".knob").knob({
    max: 1000,
    /*change : function (value) {
     //console.log("change : " + value);
     },
     release : function (value) {
     console.log("release : " + value);
     },
     cancel : function () {
     console.log("cancel : " + this.value);
     },*/
    draw: function () {

      // "tron" case
      if (this.$.data('skin') == 'tron') {

        var a = this.angle(this.cv)  // Angle
                , sa = this.startAngle          // Previous start angle
                , sat = this.startAngle         // Start angle
                , ea                            // Previous end angle
                , eat = sat + a                 // End angle
                , r = true;

        this.g.lineWidth = this.lineWidth;

        this.o.cursor
                && (sat = eat - 0.3)
                && (eat = eat + 0.3);

        if (this.o.displayPrevious) {
          ea = this.startAngle + this.angle(this.value);
          this.o.cursor
                  && (sa = ea - 0.3)
                  && (ea = ea + 0.3);
          this.g.beginPath();
          this.g.strokeStyle = this.previousColor;
          this.g.arc(this.xy, this.xy, this.radius - this.lineWidth, sa, ea, false);
          this.g.stroke();
        }

        this.g.beginPath();
        this.g.strokeStyle = r ? this.o.fgColor : this.fgColor;
        this.g.arc(this.xy, this.xy, this.radius - this.lineWidth, sat, eat, false);
        this.g.stroke();

        this.g.lineWidth = 2;
        this.g.beginPath();
        this.g.strokeStyle = this.o.fgColor;
        this.g.arc(this.xy, this.xy, this.radius - this.lineWidth + 1 + this.lineWidth * 2 / 3, 0, 2 * Math.PI, false);
        this.g.stroke();

        return false;
      }
    }
  });
  /* END JQUERY KNOB */
});
</script>